// Behaviour spec for the RR-2026-09-08-2 successor documentation comparator.
//
// The comparator's job is to say PASS only when a candidate documentation tree
// differs from its baseline by the ruled-on footer token and the nine
// enumerated anchor corrections, and nothing else. Every test below asserts an
// observable classification, and the negative controls RR-2 names each make one
// small, realistic change and require the comparator to notice it:
//
//   * extra / missing / moved footer tokens
//   * fragment-named files (`global.html#ANNOTATIONS`) with extra content
//   * a changed anchor href, a changed label, a changed occurrence count
//   * any change outside the exact listed anchors
//
// A comparator without these cannot fail, and a comparator that cannot fail is
// not evidence.
import assert from "node:assert/strict";
import test from "node:test";

import {
  FOOTER_TOKEN,
  PERMITTED_ANCHOR_CORRECTIONS,
  PERMITTED_ANCHOR_OCCURRENCE_TOTAL,
  compareDocumentationFile,
  compareDocumentationTrees,
  documentFileName,
  isHtmlDocumentPath,
} from "./compare-doc-anchors.mjs";

function page({ body = "<p>body</p>", footer = FOOTER_TOKEN.baseline } = {}) {
  return [
    "<html><body>",
    body,
    "<footer>",
    `        Documentation generated by ${footer}`,
    "</footer>",
    "</body></html>",
  ].join("\r\n");
}

const ARC_OLD =
  PERMITTED_ANCHOR_CORRECTIONS["ArcGisMapServerImageryProvider.html"][0].old;
const ARC_NEW =
  PERMITTED_ANCHOR_CORRECTIONS["ArcGisMapServerImageryProvider.html"][0].new;

test("the enumerated corrections total exactly nine occurrences across five pages", () => {
  assert.equal(Object.keys(PERMITTED_ANCHOR_CORRECTIONS).length, 5);
  assert.equal(PERMITTED_ANCHOR_OCCURRENCE_TOTAL, 9);
});

test("a fragment-suffixed filename is still an HTML document", () => {
  assert.equal(isHtmlDocumentPath("Build/Documentation/global.html"), true);
  assert.equal(
    isHtmlDocumentPath("Build/Documentation/global.html#ANNOTATIONS"),
    true,
  );
  assert.equal(
    isHtmlDocumentPath("Build/Documentation/global.html#PixelFormat"),
    true,
  );
  assert.equal(isHtmlDocumentPath("Build/Documentation/types.txt"), false);
  assert.equal(isHtmlDocumentPath("Build/Documentation/styles/a.css"), false);
  assert.equal(documentFileName("Build/Documentation/a/b.html"), "b.html");
});

test("identical bytes classify raw-equal", () => {
  const text = page();
  assert.equal(
    compareDocumentationFile({
      path: "Build/Documentation/Anything.html",
      baseline: text,
      candidate: text,
    }).classification,
    "raw-equal",
  );
});

test("only the contextual footer token changing classifies footer-only", () => {
  const result = compareDocumentationFile({
    path: "Build/Documentation/Anything.html",
    baseline: page(),
    candidate: page({ footer: FOOTER_TOKEN.candidate }),
  });
  assert.equal(result.classification, "footer-only");
  assert.equal(result.reason, null);
});

test("a fragment-suffixed page is compared, not skipped", () => {
  const result = compareDocumentationFile({
    path: "Build/Documentation/global.html#ANNOTATIONS",
    baseline: page(),
    candidate: page({ footer: FOOTER_TOKEN.candidate }),
  });
  assert.equal(result.classification, "footer-only");
});

test("the nine enumerated anchor corrections classify anchor-corrected", () => {
  for (const [name, corrections] of Object.entries(
    PERMITTED_ANCHOR_CORRECTIONS,
  )) {
    const oldBody = corrections
      .flatMap((correction) => Array(correction.count).fill(correction.old))
      .join("\r\n");
    const newBody = corrections
      .flatMap((correction) => Array(correction.count).fill(correction.new))
      .join("\r\n");
    const result = compareDocumentationFile({
      path: `Build/Documentation/${name}`,
      baseline: page({ body: oldBody }),
      candidate: page({ body: newBody, footer: FOOTER_TOKEN.candidate }),
    });
    assert.equal(
      result.classification,
      "anchor-corrected",
      `${name}: ${result.reason}`,
    );
    assert.equal(
      result.anchorsApplied.reduce((sum, entry) => sum + entry.count, 0),
      corrections.reduce((sum, entry) => sum + entry.count, 0),
    );
  }
});

// ---------------------------------------------------------------- negative controls

test("NEGATIVE: an extra footer token anywhere on the page is a difference", () => {
  const baseline = page({
    body: `<p>body</p>\r\n${FOOTER_TOKEN.baseline}`,
  });
  const result = compareDocumentationFile({
    path: "Build/Documentation/Anything.html",
    baseline,
    candidate: page({ footer: FOOTER_TOKEN.candidate }),
  });
  assert.equal(result.classification, "different");
  assert.match(result.reason, /baseline footer token is not exactly one/u);
});

test("NEGATIVE: a missing footer token in the candidate is a difference", () => {
  const result = compareDocumentationFile({
    path: "Build/Documentation/Anything.html",
    baseline: page(),
    candidate: page({ footer: "<span>JSDoc</span>" }),
  });
  assert.equal(result.classification, "different");
  assert.match(result.reason, /candidate footer token is not exactly one/u);
});

test("NEGATIVE: a footer token moved out of the <footer> element is a difference", () => {
  const moved = [
    "<html><body>",
    `<p>${FOOTER_TOKEN.candidate}</p>`,
    "<footer>",
    "        Documentation generated by",
    "</footer>",
    "</body></html>",
  ].join("\r\n");
  const result = compareDocumentationFile({
    path: "Build/Documentation/Anything.html",
    baseline: page(),
    candidate: moved,
  });
  assert.equal(result.classification, "different");
  assert.match(result.reason, /not exactly one in one <footer>/u);
});

test("NEGATIVE: a fragment-named file with extra content is a difference, not footer-only", () => {
  const result = compareDocumentationFile({
    path: "Build/Documentation/global.html#ANNOTATIONS",
    baseline: page(),
    candidate: page({
      body: "<p>body</p>\r\n<p>an extra paragraph</p>",
      footer: FOOTER_TOKEN.candidate,
    }),
  });
  assert.equal(result.classification, "different");
  assert.match(result.reason, /no permitted anchor corrections/u);
});

test("NEGATIVE: a changed anchor href on a listed page is a difference", () => {
  const tampered = ARC_NEW.replace(
    "mapping-apis-and-services/security",
    "mapping-apis-and-services/elsewhere",
  );
  const result = compareDocumentationFile({
    path: "Build/Documentation/ArcGisMapServerImageryProvider.html",
    baseline: page({ body: [ARC_OLD, ARC_OLD].join("\r\n") }),
    candidate: page({
      body: [tampered, ARC_NEW].join("\r\n"),
      footer: FOOTER_TOKEN.candidate,
    }),
  });
  assert.equal(result.classification, "different");
  assert.match(result.reason, /corrected anchor in the candidate, found 1/u);
});

test("NEGATIVE: a changed anchor label on a listed page is a difference", () => {
  const tampered = ARC_NEW.replace(
    ">ArcGIS Access Token<",
    ">ArcGIS Access Tokens<",
  );
  const result = compareDocumentationFile({
    path: "Build/Documentation/ArcGisMapServerImageryProvider.html",
    baseline: page({ body: [ARC_OLD, ARC_OLD].join("\r\n") }),
    candidate: page({
      body: [tampered, ARC_NEW].join("\r\n"),
      footer: FOOTER_TOKEN.candidate,
    }),
  });
  assert.equal(result.classification, "different");
  assert.match(result.reason, /corrected anchor in the candidate, found 1/u);
});

test("NEGATIVE: a changed occurrence count of a listed anchor is a difference", () => {
  const result = compareDocumentationFile({
    path: "Build/Documentation/ArcGisMapServerImageryProvider.html",
    baseline: page({ body: [ARC_OLD, ARC_OLD, ARC_OLD].join("\r\n") }),
    candidate: page({
      body: [ARC_NEW, ARC_NEW, ARC_NEW].join("\r\n"),
      footer: FOOTER_TOKEN.candidate,
    }),
  });
  assert.equal(result.classification, "different");
  assert.match(
    result.reason,
    /pre-correction anchor in the baseline, found 3/u,
  );
});

test("NEGATIVE: the pre-correction anchor surviving in the candidate is a difference", () => {
  const result = compareDocumentationFile({
    path: "Build/Documentation/ArcGisMapServerImageryProvider.html",
    baseline: page({ body: [ARC_OLD, ARC_OLD].join("\r\n") }),
    candidate: page({
      body: [ARC_NEW, ARC_NEW, ARC_OLD].join("\r\n"),
      footer: FOOTER_TOKEN.candidate,
    }),
  });
  assert.equal(result.classification, "different");
  assert.match(result.reason, /still appears 1 time\(s\) in the candidate/u);
});

test("NEGATIVE: a change outside the listed anchors on a listed page is a difference", () => {
  const result = compareDocumentationFile({
    path: "Build/Documentation/ArcGisMapServerImageryProvider.html",
    baseline: page({ body: [ARC_OLD, ARC_OLD, "<p>keep</p>"].join("\r\n") }),
    candidate: page({
      body: [ARC_NEW, ARC_NEW, "<p>changed</p>"].join("\r\n"),
      footer: FOOTER_TOKEN.candidate,
    }),
  });
  assert.equal(result.classification, "different");
  assert.match(result.reason, /still differs after the contextual footer/u);
});

test("NEGATIVE: the same anchor correction on an unlisted page is a difference", () => {
  const result = compareDocumentationFile({
    path: "Build/Documentation/SomeOtherClass.html",
    baseline: page({ body: ARC_OLD }),
    candidate: page({ body: ARC_NEW, footer: FOOTER_TOKEN.candidate }),
  });
  assert.equal(result.classification, "different");
  assert.match(result.reason, /no permitted anchor corrections/u);
});

test("NEGATIVE: non-HTML output gets no footer or anchor allowance", () => {
  const result = compareDocumentationFile({
    path: "Build/Documentation/types.txt",
    baseline: '{"a":1}',
    candidate: '{"a":2}',
  });
  assert.equal(result.classification, "different");
  assert.match(result.reason, /must match byte for byte/u);
});

// ----------------------------------------------------------------- tree level

function tree(entries) {
  return new Map(entries);
}

test("a whole tree passes only when the nine corrections are the complete difference", () => {
  const baselineEntries = [
    ["Build/Documentation/index.html", page()],
    ["Build/Documentation/global.html#ANNOTATIONS", page()],
    ["Build/Documentation/types.txt", '{"a":1}'],
  ];
  const candidateEntries = [
    [
      "Build/Documentation/index.html",
      page({ footer: FOOTER_TOKEN.candidate }),
    ],
    [
      "Build/Documentation/global.html#ANNOTATIONS",
      page({ footer: FOOTER_TOKEN.candidate }),
    ],
    ["Build/Documentation/types.txt", '{"a":1}'],
  ];
  for (const [name, corrections] of Object.entries(
    PERMITTED_ANCHOR_CORRECTIONS,
  )) {
    const oldBody = corrections
      .flatMap((correction) => Array(correction.count).fill(correction.old))
      .join("\r\n");
    const newBody = corrections
      .flatMap((correction) => Array(correction.count).fill(correction.new))
      .join("\r\n");
    baselineEntries.push([
      `Build/Documentation/${name}`,
      page({ body: oldBody }),
    ]);
    candidateEntries.push([
      `Build/Documentation/${name}`,
      page({ body: newBody, footer: FOOTER_TOKEN.candidate }),
    ]);
  }

  const passing = compareDocumentationTrees({
    baseline: tree(baselineEntries),
    candidate: tree(candidateEntries),
  });
  assert.equal(passing.status, "PASS", JSON.stringify(passing.counts));
  assert.equal(passing.anchorOccurrences, 9);
  assert.equal(passing.counts.different, 0);
  assert.equal(passing.counts["anchor-corrected"], 5);

  // NEGATIVE: membership must match exactly.
  const extra = compareDocumentationTrees({
    baseline: tree(baselineEntries),
    candidate: tree([
      ...candidateEntries,
      ["Build/Documentation/Surprise.html", page()],
    ]),
  });
  assert.equal(extra.status, "FAIL");
  assert.deepEqual(extra.membership.added, [
    "Build/Documentation/Surprise.html",
  ]);

  const dropped = compareDocumentationTrees({
    baseline: tree(baselineEntries),
    candidate: tree(candidateEntries.slice(1)),
  });
  assert.equal(dropped.status, "FAIL");
  assert.equal(dropped.membership.missing.length, 1);

  // NEGATIVE: a page that should have been corrected but was not leaves the
  // occurrence total short, so the tree cannot pass on counts alone.
  const uncorrected = candidateEntries.map((entry) =>
    entry[0] === "Build/Documentation/IntersectionTests.html"
      ? [entry[0], page({ footer: FOOTER_TOKEN.candidate })]
      : entry,
  );
  const short = compareDocumentationTrees({
    baseline: tree(baselineEntries),
    candidate: tree(uncorrected),
  });
  assert.equal(short.status, "FAIL");
  assert.ok(short.anchorOccurrences < PERMITTED_ANCHOR_OCCURRENCE_TOTAL);
});
