/**
 * (Per-feature pick added in Batch 115.)
 *
 * WebGPU equivalent of `Vector3DTilePolylines` (3D Tiles polylines NOT
 * clamped to terrain). Pairs with `WebGPUVector3DTileClampedPolylinesRenderer`
 * for the terrain-clamped variant.
 *
 * The CPU side (worker-decoded `_currentPositions`, `_previousPositions`,
 * `_nextPositions`, `_expandAndWidth`, `_vertexBatchIds`, `_indices`) is
 * generated by the existing `createVectorTilePolylines` task processor.
 * On the WebGPU path, `Vector3DTilePolylines.update()` keeps those arrays
 * alive (the WebGL `finishVertexArray` is skipped) so this renderer can
 * upload them straight into GPU buffers.
 *
 * **Shipped (Batch 113):**
 *   - WGSL VS port of `Vector3DTilePolylinesVS.glsl` + the screen-space
 *     miter expansion from `PolylineCommon.glsl::getPolylineWindowCoordinatesEC`.
 *   - Per-vertex `previousPosition`, `currentPosition`, `nextPosition`
 *     (vec3, RTC-relative to `_center`), `expandAndWidth` (vec2),
 *     `batchId` (f32) — interleaved into a single 60-byte / vertex stream
 *     so the GroundPrimitive vertex-cache cost amortizes.
 *   - Per-batch color via storage buffer indexed by `batchId`.
 *   - Single DrawCommand emission (the index buffer concatenates all
 *     polylines into one draw).
 *   - `Pass.TRANSLUCENT` matching the WebGL `_command.pass` choice — these
 *     polylines write color but not depth.
 *
 * **Deferred:**
 *   - Near-plane clipping (`clipLineSegmentToNearPlane`). Polylines that
 *     cross the near plane will render with garbage segments. Fix: port
 *     the WebGL clip routine — ~40 LOC of WGSL.
 *   - `POLYLINE_DASH` material variant.
 *
 * **Per-feature pick (Batch 115):**
 *   - A second storage buffer `pickColors[batchId]` is bound at
 *     group(0) binding(2) and uploaded from `batchTable.getPickColor(i)`.
 *   - A second pipeline (`pickPipeline`) shares the same VS but uses a
 *     `pickFS` entry point that returns `pickColors[batchId]`.
 *   - `createCommands` returns `{ colorCommands, pickCommands }`. The
 *     Scene-side `Vector3DTilePolylines.update()` pushes `pickCommands`
 *     when `frameState.passes.pick === true`.
 *
 * @module WebGPUVector3DTilePolylinesRenderer
 * @private
 */
import defined from "../../Core/defined.js";
import Cartesian3 from "../../Core/Cartesian3.js";
import Matrix4 from "../../Core/Matrix4.js";
import Pass from "../Pass.js";
import oneTimeWarning from "../../Core/oneTimeWarning.js";
import SceneMode from "../../Scene/SceneMode.js";
import WebGPUBuffer from "./WebGPUBuffer.js";
import WebGPUDrawCommand from "./WebGPUDrawCommand.js";
import {
  makeBindGroupLayout,
  uniformBuffer,
  storageBuffer,
  Stage,
} from "./WebGPUBindGroupLayoutHelpers.js";
import { ShaderDefine, ShaderSourceId } from "./WebGPUShaderDefines.js";
import { WebGPUShaderModuleCache } from "./WebGPUShaderModuleCache.js";
import { isWebGPULogDepthActive } from "./WebGPULogDepth.js";
// Slice 5c-B Phase 1 (Batch 113) — scene-FB target helper.
import { makeSceneFBTargets } from "./WebGPUSceneFBTargetHelpers.js";

// C-R7-SHADER-MODULE-DEDUP (Batch 163) — per-device module cache.
const _polylineShaderCaches = new WeakMap();

function getPolylineShaderCache(device) {
  let cache = _polylineShaderCaches.get(device);
  if (!cache) {
    cache = new WebGPUShaderModuleCache(device);
    _polylineShaderCaches.set(device, cache);
  }
  return cache;
}

const UNIFORM_BUFFER_SIZE = 256;
const BYTES_PER_BATCH_COLOR = 16;
const INITIAL_BATCH_BUFFER_FEATURES = 64;

const scratchModifiedView = new Matrix4();
const scratchRtcCenter = new Cartesian3();

function buildPolylinePipelineResources(
  device,
  format,
  depthFormat,
  logDepthActive,
  sampleCount,
  // NEW-WEBGPU-HDR-PICK-FORMAT-CLOSURE — pick pipelines target the
  // context's byte-object-ID format authority (matches the pick FBO),
  // never the (possibly float/HDR) scene format.
  pickFormat = "rgba8unorm",
) {
  const code = `
${
  logDepthActive
    ? // NEW-CLASSIFIER-LOG-DEPTH (Batch 266) — canonical inline copies. The
      // non-clamped polyline tests less-equal against the shared scene depth
      // (write-disabled), which the globe now LOG-encodes; without writing log
      // z the polyline's hyperbolic z fails the test and it vanishes behind
      // the surface. Mirrors GroundPrimitive colorVS.
      "fn csm_vertexLogDepth(clipPosition: vec4<f32>, near: f32) -> f32 {\n" +
      "  return (clipPosition.w - near) + 1.0;\n" +
      "}\n" +
      "fn csm_writeLogDepth(depthFromNearPlusOne: f32, oneOverLog2FarDepthFromNearPlusOne: f32) -> f32 {\n" +
      "  return log2(depthFromNearPlusOne) * oneOverLog2FarDepthFromNearPlusOne;\n" +
      "}\n"
    : ""
}
struct U {
  modifiedView: mat4x4<f32>,
  projection: mat4x4<f32>,
  viewport: vec4<f32>,
  pixelRatio: f32,
  _pad0: f32,
  _pad1: f32,
  _pad2: f32,
  // AUDIT_2026_05_02 B.9 (Batch 153) — DP-H41 prev viewProjection at the
  // tail. NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — now
  // consumed by vsVelocity for camera-only motion vectors under TAA.
  prevViewProjection: mat4x4<f32>,
  // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — primitive
  // center in world coordinates. The vertex curr is RTC-relative to
  // this center (modifiedView already pre-multiplies the center into
  // its translation column for the color VS). The velocity VS needs
  // absolute world positions to project through prevViewProjection,
  // so it does worldPos = centerWC + curr. Single-precision is
  // sufficient because the velocity output is a screen-space delta;
  // any high-bits-low-bits split across centerH/centerL would only
  // matter if we needed to express positions at planet-scale precision
  // (we don't — the screen delta is bounded by viewport).
  centerWC: vec3<f32>,
  _padCenter: f32,
  // NEW-CLASSIFIER-LOG-DEPTH (Batch 266) — renderer-wide log-depth encode
  // frustum (near, far, oneOverLog2FarDepthFromNearPlusOne, reserved). Packed
  // unconditionally; only the //>>ifdef LOG_DEPTH VS branch reads it.
  logDepth: vec4<f32>,
};
@group(0) @binding(0) var<uniform> u: U;
@group(0) @binding(1) var<storage, read> batchColors: array<vec4<f32>>;
@group(0) @binding(2) var<storage, read> pickColors: array<vec4<f32>>;

struct VOut {
  @builtin(position) pos: vec4<f32>,
  @location(0) col: vec4<f32>,
  @location(1) pickCol: vec4<f32>,
};

// Miter-expanded screen-space offset, ported from
// PolylineCommon.glsl::getPolylineWindowCoordinatesEC. Near-plane clip is
// skipped for the first cut — see file header.
fn getOffset(
  pEC: vec4<f32>,
  prevEC: vec4<f32>,
  nextEC: vec4<f32>,
  expandDir: f32,
  width: f32,
  usePrev: bool,
  halfVP: vec2<f32>,
) -> vec2<f32> {
  let pClip = u.projection * pEC;
  let prevClip = u.projection * prevEC;
  let nextClip = u.projection * nextEC;

  let invPW = 1.0 / max(pClip.w, 1e-6);
  let invPrevW = 1.0 / max(prevClip.w, 1e-6);
  let invNextW = 1.0 / max(nextClip.w, 1e-6);

  let pPx = pClip.xy * invPW * halfVP;
  let prevPx = prevClip.xy * invPrevW * halfVP;
  let nextPx = nextClip.xy * invNextW * halfVP;

  let dirToPrev = normalize(prevPx - pPx);
  let dirToNext = normalize(nextPx - pPx);

  var thisSegmentForward: vec2<f32>;
  var otherSegmentForward: vec2<f32>;
  if (usePrev) {
    thisSegmentForward = -dirToPrev;
    otherSegmentForward = dirToNext;
  } else {
    thisSegmentForward = dirToNext;
    otherSegmentForward = -dirToPrev;
  }
  let thisSegmentLeft = vec2<f32>(-thisSegmentForward.y, thisSegmentForward.x);

  var leftWC = thisSegmentLeft;
  var expandWidth = width * 0.5;

  let prevDelta = prevEC.xyz - pEC.xyz;
  let nextDelta = nextEC.xyz - pEC.xyz;
  let prevColinear = dot(prevDelta, prevDelta) < 1e-2;
  let nextColinear = dot(nextDelta, nextDelta) < 1e-2;
  if (!prevColinear && !nextColinear) {
    let otherSegmentLeft = vec2<f32>(-otherSegmentForward.y, otherSegmentForward.x);
    let leftSum = thisSegmentLeft + otherSegmentLeft;
    let leftSumLength = length(leftSum);
    if (leftSumLength >= 1e-6) {
      leftWC = leftSum / leftSumLength;
    }
    let uVec = -thisSegmentForward;
    let sinAngle = abs(uVec.x * leftWC.y - uVec.y * leftWC.x);
    if (sinAngle > 1e-4) {
      expandWidth = clamp(expandWidth / sinAngle, 0.0, width * 2.0);
    }
  }

  return leftWC * expandDir * expandWidth * u.pixelRatio;
}

@vertex
fn vsMain(
  @location(0) prev: vec3<f32>,
  @location(1) curr: vec3<f32>,
  @location(2) next: vec3<f32>,
  @location(3) expandAndWidth: vec2<f32>,
  @location(4) batchId: f32,
) -> VOut {
  let expandDir = expandAndWidth.x;
  let width = abs(expandAndWidth.y) + 0.5;
  let usePrev = expandAndWidth.y < 0.0;

  let pEC = u.modifiedView * vec4<f32>(curr, 1.0);
  let prevEC = u.modifiedView * vec4<f32>(prev, 1.0);
  let nextEC = u.modifiedView * vec4<f32>(next, 1.0);

  let halfVP = u.viewport.zw * 0.5;
  let offsetPx = getOffset(pEC, prevEC, nextEC, expandDir, width, usePrev, halfVP);

  let pClip = u.projection * pEC;
  let offsetNDC = offsetPx / halfVP;
  var outClip = vec4<f32>(
    pClip.xy + offsetNDC * pClip.w,
    pClip.z,
    pClip.w,
  );
${
  logDepthActive
    ? // NEW-CLASSIFIER-LOG-DEPTH (Batch 266) — write log z so the polyline's
      // less-equal test (against the write-disabled LOG-depth scene depth)
      // passes. u.logDepth = (encodeNear, encodeFar, factor, _).
      "  let _ldNear = u.logDepth.x;\n" +
      "  let _ldFar = u.logDepth.y;\n" +
      "  let _ldFactor = 1.0 / log2((_ldFar - _ldNear) + 1.0);\n" +
      "  let _logZ = csm_writeLogDepth(csm_vertexLogDepth(outClip, _ldNear), _ldFactor);\n" +
      "  outClip.z = clamp(_logZ, 0.0, 1.0) * outClip.w;\n"
    : ""
}

  var output: VOut;
  output.pos = outClip;
  let bi = u32(batchId);
  output.col = batchColors[bi];
  output.pickCol = pickColors[bi];
  return output;
}

@fragment
fn fsMain(i: VOut) -> @location(0) vec4<f32> {
  // AUDIT_2026_05_02 B.1 — feature.show is folded into batchColors[bi].a
  // CPU-side. Discard hidden features here.
  if (i.col.a < 1.0e-3) {
    discard;
  }
  return i.col;
}

@fragment
fn pickFS(i: VOut) -> @location(0) vec4<f32> {
  // AUDIT_2026_05_02 B.1 — pick must respect feature.show too.
  if (i.col.a < 1.0e-3) {
    discard;
  }
  return i.pickCol;
}

// NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — velocity entry
// points for TAA. Vector3DTilePolylines have static per-feature
// geometry (the tileset content doesn't animate), so velocity is
// camera-only: project the SAME world-space position through both the
// current and previous VPs and emit (currNdc - prevNdc). The polyline
// extrusion math (getOffset) is intentionally NOT replicated in the
// velocity VS — the velocity texture only needs a per-pixel screen-
// delta, and rasterizing from the same extruded vertices via the same
// vsMain-style transformation produces matching coverage. We just
// need both clip positions for the same fragment.
//
// Approach: use the full extrusion math from vsMain for the current
// clip (so coverage matches the color pass exactly), then compute the
// previous clip for the SAME extruded vertex via prevViewProjection.
// Since the extrusion is a screen-space offset added to the projected
// position, the previous frame's extrusion would have been at a
// different screen-space offset (camera-distance-dependent). For
// camera-only motion this approximation is correct: the geometry's
// world-space position is identical, only the projection differs.
struct VelocityVOut {
  @builtin(position) pos: vec4<f32>,
  @location(0) currClip: vec4<f32>,
  @location(1) prevClip: vec4<f32>,
};

@vertex
fn vsVelocity(
  @location(0) prev: vec3<f32>,
  @location(1) curr: vec3<f32>,
  @location(2) next: vec3<f32>,
  @location(3) expandAndWidth: vec2<f32>,
  @location(4) batchId: f32,
) -> VelocityVOut {
  // Replicate the color VS extrusion exactly so the velocity-pass
  // rasterization covers the same fragments the color pass produced
  // — no spurious half-pixel velocity offsets at the polyline edges.
  let expandDir = expandAndWidth.x;
  let width = abs(expandAndWidth.y) + 0.5;
  let usePrev = expandAndWidth.y < 0.0;

  let pEC = u.modifiedView * vec4<f32>(curr, 1.0);
  let prevEC = u.modifiedView * vec4<f32>(prev, 1.0);
  let nextEC = u.modifiedView * vec4<f32>(next, 1.0);

  let halfVP = u.viewport.zw * 0.5;
  let offsetPx = getOffset(pEC, prevEC, nextEC, expandDir, width, usePrev, halfVP);

  let pClip = u.projection * pEC;
  let offsetNDC = offsetPx / halfVP;
  var curClip = vec4<f32>(
    pClip.xy + offsetNDC * pClip.w,
    pClip.z,
    pClip.w,
  );
${
  logDepthActive
    ? // NEW-CLASSIFIER-LOG-DEPTH (Batch 266) — the velocity pass shares the
      // scene depth read-only (less-equal), so its rasterized z must match the
      // log color pass or coverage diverges. Same log-z write as vsMain.
      "  let _ldNearV = u.logDepth.x;\n" +
      "  let _ldFarV = u.logDepth.y;\n" +
      "  let _ldFactorV = 1.0 / log2((_ldFarV - _ldNearV) + 1.0);\n" +
      "  let _logZV = csm_writeLogDepth(csm_vertexLogDepth(curClip, _ldNearV), _ldFactorV);\n" +
      "  curClip.z = clamp(_logZV, 0.0, 1.0) * curClip.w;\n"
    : ""
}

  // Previous-frame clip for the SAME extruded vertex's world position.
  // World position = primitive's centerWC + RTC-relative curr (the
  // extrusion offset is in screen-space, so it doesn't translate to
  // world-space — using the un-extruded world position here is the
  // closest physical approximation for camera-only motion). The
  // velocity-pass rasterization uses curClip for coverage, so the
  // emitted velocity is the per-fragment NDC delta between the
  // extruded current position and the un-extruded previous projection.
  // This is acceptable because the extrusion offset is small (line
  // width pixels) and TAA samples at sub-pixel resolution anyway.
  let worldPos = u.centerWC + curr;
  let prClip = u.prevViewProjection * vec4<f32>(worldPos, 1.0);

  var output: VelocityVOut;
  output.pos = curClip;
  output.currClip = curClip;
  output.prevClip = prClip;
  // batchId unused by velocity but kept in input layout to match the
  // shared vertex buffer format.
  let _bi = batchId;
  return output;
}

@fragment
fn fsVelocity(i: VelocityVOut) -> @location(0) vec2<f32> {
  let curW = i.currClip.w;
  let prevW = i.prevClip.w;
  if (curW <= 0.0 || prevW <= 0.0) {
    return vec2<f32>(0.0);
  }
  let curNdc = i.currClip.xy / curW;
  let prevNdc = i.prevClip.xy / prevW;
  return curNdc - prevNdc;
}
`;

  const mod = getPolylineShaderCache(device).getOrCreate(
    ShaderSourceId.VECTOR_3DTILE_POLYLINES,
    code,
    logDepthActive ? ShaderDefine.LOG_DEPTH : 0,
    `Vector3DTilePolylines${logDepthActive ? " [log]" : ""}`,
  );

  // NEW-WEBGPU-PIPELINE-KEY-LOG-DEPTH — `logDepthActive` picks a DIFFERENT
  // `mod` above, and all three descriptors below use it for both stages. The
  // central pipeline cache's `generateCacheKey` hashes only the descriptor NAME
  // plus structural fields — never `vertex.module`, `fragment.module`,
  // `entryPoint`, or the define mask. `_pipelineLogDepth` below rebuilds these
  // descriptors on a flip, so without this marker the rebuilt log descriptor
  // hits the hyperbolic pipeline already cached under the identical name.
  // Reachable via `scene.morphTo2D()` / `camera.switchToOrthographicFrustum()`,
  // which clear `frameState.useLogDepth`.
  const ldFlag = logDepthActive ? 1 : 0;

  const sharedBgl = makeBindGroupLayout(device, "Vector3DTilePolylines BGL", [
    uniformBuffer(0, Stage.VERTEX_FRAGMENT),
    storageBuffer(1, Stage.VERTEX, { readOnly: true }),
    storageBuffer(2, Stage.VERTEX, { readOnly: true }),
  ]);

  const layout = device.createPipelineLayout({
    label: "Vector3DTilePolylines PipelineLayout",
    bindGroupLayouts: [sharedBgl],
  });

  // Interleaved vertex layout — 60 bytes per vertex:
  //   loc 0: prev (vec3)            offset  0
  //   loc 1: curr (vec3)            offset 12
  //   loc 2: next (vec3)            offset 24
  //   loc 3: expandAndWidth (vec2)  offset 36
  //   loc 4: batchId (f32)          offset 44
  // (4-byte padding to round to 48-byte stride for alignment.)
  const vertexBuffers = [
    {
      arrayStride: 48,
      attributes: [
        { shaderLocation: 0, offset: 0, format: "float32x3" },
        { shaderLocation: 1, offset: 12, format: "float32x3" },
        { shaderLocation: 2, offset: 24, format: "float32x3" },
        { shaderLocation: 3, offset: 36, format: "float32x2" },
        { shaderLocation: 4, offset: 44, format: "float32" },
      ],
    },
  ];

  // ROADMAP s4.2 (B515) — the color pipeline runs inside the multisampled
  // scene pass, so its `multisample.count` MUST match `context._msaaSamples`
  // (4 at viewer defaults) or WebGPU rejects the draw with an
  // attachment-incompatible error and vector polylines render fully black.
  // Pick + velocity render into single-sample targets, so both stay count-1.
  const msState = sampleCount > 1 ? { count: sampleCount } : undefined;
  const colorDescriptor = {
    name: `Vector3DTilePolylines color [${format}/${depthFormat}/ms=${sampleCount ?? 1}/ld=${ldFlag}]`,
    layout,
    vertex: { module: mod, entryPoint: "vsMain", buffers: vertexBuffers },
    fragment: {
      module: mod,
      entryPoint: "fsMain",
      // Slice 5c-B Phase 1 (Batch 113) — scene-FB color target via
      // helper. Pick (L409, [{format}]) and velocity (L435, rg16float)
      // stay single-target.
      targets: makeSceneFBTargets(format, { translucent: true }),
    },
    primitive: { topology: "triangle-list", cullMode: "none" },
    depthStencil: {
      format: depthFormat,
      depthWriteEnabled: false,
      depthCompare: "less-equal",
      depthBias: -5,
      depthBiasSlopeScale: -5,
    },
    multisample: msState,
  };

  // Pick pipeline: same VS / same depth / same blend / different FS
  // entry point. The pick FBO consumer expects RGBA8 unorm output in
  // [0, 1]; the target is stamped with the context's pick-format
  // authority (NEW-WEBGPU-HDR-PICK-FORMAT-CLOSURE).
  const pickDescriptor = {
    name: `Vector3DTilePolylines pick [${pickFormat}/${depthFormat}/ld=${ldFlag}]`,
    layout,
    vertex: { module: mod, entryPoint: "vsMain", buffers: vertexBuffers },
    fragment: {
      module: mod,
      entryPoint: "pickFS",
      targets: [{ format: pickFormat }],
    },
    primitive: { topology: "triangle-list", cullMode: "none" },
    depthStencil: {
      format: depthFormat,
      depthWriteEnabled: false,
      depthCompare: "less-equal",
      depthBias: -5,
      depthBiasSlopeScale: -5,
    },
  };

  // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — velocity
  // pipeline descriptor. Same VS extrusion math as the color pipeline
  // (so the velocity-pass rasterization covers the SAME fragments the
  // color pass produced), single rg16float color target, no blend,
  // depth read-only. Same shared BGL — no extra storage needed; the
  // per-vertex prev clip is computed from `centerWC + curr` projected
  // through `prevViewProjection`.
  const velocityDescriptor = {
    name: `Vector3DTilePolylines velocity [${depthFormat}/ld=${ldFlag}]`,
    layout,
    vertex: { module: mod, entryPoint: "vsVelocity", buffers: vertexBuffers },
    fragment: {
      module: mod,
      entryPoint: "fsVelocity",
      targets: [{ format: "rg16float" }],
    },
    primitive: { topology: "triangle-list", cullMode: "none" },
    depthStencil: {
      format: depthFormat,
      depthWriteEnabled: false,
      depthCompare: "less-equal",
      // Match color pipeline's depth bias so velocity-pass coverage
      // tracks the color pass at oblique-angle line edges. Without
      // matching bias the velocity pass would clip slightly differently
      // than the color pass (off-by-one-pixel velocity contribution
      // along polyline edges, which TAA would propagate as edge ghost).
      depthBias: -5,
      depthBiasSlopeScale: -5,
    },
  };

  return { colorDescriptor, pickDescriptor, velocityDescriptor, sharedBgl };
}

function descriptorToGPU(d) {
  return {
    label: d.name,
    layout: d.layout ?? "auto",
    vertex: {
      module: d.vertex.module,
      entryPoint: d.vertex.entryPoint,
      buffers: d.vertex.buffers,
    },
    fragment: d.fragment
      ? {
          module: d.fragment.module,
          entryPoint: d.fragment.entryPoint,
          targets: d.fragment.targets,
        }
      : undefined,
    primitive: d.primitive,
    depthStencil: d.depthStencil,
    multisample: d.multisample,
  };
}

function tryResolvePipelines(device, pipelineCache, resources, cache) {
  if (cache.colorPipeline && cache.pickPipeline) {
    return true;
  }
  if (pipelineCache) {
    if (!cache.colorPipeline) {
      const sync = pipelineCache.getPipelineSync(resources.colorDescriptor);
      if (sync) {
        cache.colorPipeline = sync;
      } else if (!cache.colorRequestPending) {
        cache.colorRequestPending = true;
        pipelineCache
          .getPipeline(resources.colorDescriptor)
          .then((p) => {
            cache.colorPipeline = p;
            cache.colorRequestPending = false;
          })
          .catch(() => {
            cache.colorRequestPending = false;
          });
      }
    }
    if (!cache.pickPipeline) {
      const pickSync = pipelineCache.getPipelineSync(resources.pickDescriptor);
      if (pickSync) {
        cache.pickPipeline = pickSync;
      } else if (!cache.pickRequestPending) {
        cache.pickRequestPending = true;
        pipelineCache
          .getPipeline(resources.pickDescriptor)
          .then((p) => {
            cache.pickPipeline = p;
            cache.pickRequestPending = false;
          })
          .catch(() => {
            cache.pickRequestPending = false;
          });
      }
    }
    // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — velocity
    // pipeline. Cache miss is non-fatal: the color pass continues to
    // render correctly without it; only the velocity-pass dispatch
    // becomes a no-op until the variant lands. Same pattern as
    // Vector3DTilePrimitive (Batch 178).
    if (!cache.velocityPipeline) {
      const velSync = pipelineCache.getPipelineSync(
        resources.velocityDescriptor,
      );
      if (velSync) {
        cache.velocityPipeline = velSync;
      } else if (!cache.velocityRequestPending) {
        cache.velocityRequestPending = true;
        pipelineCache
          .getPipeline(resources.velocityDescriptor)
          .then((p) => {
            cache.velocityPipeline = p;
            cache.velocityRequestPending = false;
          })
          .catch(() => {
            cache.velocityRequestPending = false;
          });
      }
    }
    return !!cache.colorPipeline;
  }
  if (!cache.colorPipeline) {
    cache.colorPipeline = device.createRenderPipeline(
      descriptorToGPU(resources.colorDescriptor),
    );
  }
  if (!cache.pickPipeline) {
    cache.pickPipeline = device.createRenderPipeline(
      descriptorToGPU(resources.pickDescriptor),
    );
  }
  // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — fallback path.
  if (!cache.velocityPipeline) {
    cache.velocityPipeline = device.createRenderPipeline(
      descriptorToGPU(resources.velocityDescriptor),
    );
  }
  return true;
}

function packUniforms(data, frameState, primitive) {
  const uniformState = frameState.context.uniformState;
  // modifiedView = view with translation set to view*center, matching
  // WebGL `u_modifiedModelView`. This is the RTC-precision-aware view
  // matrix used by the WebGL VS, ported verbatim.
  Matrix4.clone(uniformState.view, scratchModifiedView);
  Matrix4.multiplyByPoint(
    scratchModifiedView,
    primitive._center ?? Cartesian3.ZERO,
    scratchRtcCenter,
  );
  Matrix4.setTranslation(
    scratchModifiedView,
    scratchRtcCenter,
    scratchModifiedView,
  );
  Matrix4.pack(scratchModifiedView, data, 0);
  Matrix4.pack(uniformState.projection, data, 16);

  // Viewport — source from context.drawingBufferWidth/Height directly.
  // See WebGPUGroundPolylineRenderer.js packUniforms for the full
  // explanation; same bug-pattern (uniformState.viewportCartesian4 is
  // zero-initialized at FR-update time and `??` doesn't fall through on 0).
  // Vector3DTilePolylines uses viewport for pixel-space line offset
  // (offsetNDC = offsetPx / halfVP) — halfVP=0 means offsetNDC=Inf and
  // every vertex extrudes to NaN clip-space.
  const ctx = frameState.context;
  data[32] = 0.0;
  data[33] = 0.0;
  data[34] = ctx?.drawingBufferWidth || 1;
  data[35] = ctx?.drawingBufferHeight || 1;

  data[36] = uniformState.pixelRatio ?? 1.0;

  // AUDIT_2026_05_02 B.9 (Batch 153) — DP-H41 prev viewProjection at floats
  // 40..55 (16-byte-aligned past the f32 + 3×_pad scalar block).
  const prevVP = uniformState.previousViewProjection;
  if (prevVP) {
    Matrix4.pack(prevVP, data, 40);
  } else {
    data[40] = 1;
    data[41] = 0;
    data[42] = 0;
    data[43] = 0;
    data[44] = 0;
    data[45] = 1;
    data[46] = 0;
    data[47] = 0;
    data[48] = 0;
    data[49] = 0;
    data[50] = 1;
    data[51] = 0;
    data[52] = 0;
    data[53] = 0;
    data[54] = 0;
    data[55] = 1;
  }

  // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — primitive
  // center in world coordinates at floats 56..58 (vec3 + 1 pad).
  // Consumed by `vsVelocity` to reconstruct world-space positions
  // (`worldPos = centerWC + curr`) for projection through
  // `prevViewProjection`.
  const center = primitive._center ?? Cartesian3.ZERO;
  data[56] = center.x;
  data[57] = center.y;
  data[58] = center.z;
  data[59] = 0.0;

  // NEW-CLASSIFIER-LOG-DEPTH (Batch 266) — log-depth encode frustum at floats
  // 60..63 (near, far, factor, reserved). Prefer the stashed FULL-frustum
  // encode the globe baked with over the live per-slice currentFrustum so the
  // polyline's per-vertex log z composes with the globe's scene depth (see the
  // same pattern in WebGPUBillboardRenderer.packUniforms). Packed
  // unconditionally; only the LOG_DEPTH VS variant reads it.
  const ldEncode = uniformState._logDepthEncodeNearFar;
  const ldFrustum = uniformState.currentFrustum;
  let ldNear = ldFrustum ? ldFrustum.x : 0.0;
  let ldFar = ldFrustum ? ldFrustum.y : 0.0;
  let ldFactor =
    typeof uniformState.oneOverLog2FarDepthFromNearPlusOne === "number"
      ? uniformState.oneOverLog2FarDepthFromNearPlusOne
      : 0.0;
  if (ldEncode && ldEncode[1] > ldEncode[0]) {
    ldNear = ldEncode[0];
    ldFar = ldEncode[1];
    const ldLog2Far = Math.log2(ldFar - ldNear + 1.0);
    ldFactor = ldLog2Far > 0.0 ? 1.0 / ldLog2Far : 0.0;
  } else if (!(ldFactor > 0.0) && ldFar > ldNear) {
    const ldLog2Far = Math.log2(ldFar - ldNear + 1.0);
    ldFactor = ldLog2Far > 0.0 ? 1.0 / ldLog2Far : 0.0;
  }
  data[60] = ldNear;
  data[61] = ldFar;
  data[62] = ldFactor;
  data[63] = 0.0; // reserved
}

function ensureVertexBuffer(cache, primitive, device) {
  if (defined(cache.vertexGPUBuffer)) {
    return;
  }

  const cur = primitive._currentPositions;
  const prev = primitive._previousPositions;
  const next = primitive._nextPositions;
  const expandAndWidth = primitive._expandAndWidth;
  const vertexBatchIds = primitive._vertexBatchIds;
  if (
    !defined(cur) ||
    !defined(prev) ||
    !defined(next) ||
    !defined(expandAndWidth) ||
    !defined(vertexBatchIds)
  ) {
    return;
  }

  const numVerts = cur.length / 3;
  if (numVerts === 0) {
    return;
  }

  // 48-byte stride: prev (12) + curr (12) + next (12) + expandAndWidth (8)
  // + batchId (4) + 0-pad. The 4-byte tail pad keeps GPU sample alignment
  // identical to the natural Float32Array stride and avoids rebuilding the
  // pipeline if a backend ever wants to add a 5th attribute slot.
  const interleaved = new Float32Array(numVerts * 12);
  for (let v = 0; v < numVerts; v++) {
    const dst = v * 12;
    const src3 = v * 3;
    const src2 = v * 2;
    interleaved[dst] = prev[src3];
    interleaved[dst + 1] = prev[src3 + 1];
    interleaved[dst + 2] = prev[src3 + 2];
    interleaved[dst + 3] = cur[src3];
    interleaved[dst + 4] = cur[src3 + 1];
    interleaved[dst + 5] = cur[src3 + 2];
    interleaved[dst + 6] = next[src3];
    interleaved[dst + 7] = next[src3 + 1];
    interleaved[dst + 8] = next[src3 + 2];
    interleaved[dst + 9] = expandAndWidth[src2];
    interleaved[dst + 10] = expandAndWidth[src2 + 1];
    interleaved[dst + 11] = vertexBatchIds[v];
    // dst + 12 padded by Float32Array zero init.
  }
  cache.vertexGPUBuffer = WebGPUBuffer.createVertexBuffer(
    device,
    interleaved,
    "Vector3DTilePolylines VB",
  );
  cache.vertexCount = numVerts;
}

function ensureIndexBuffer(cache, primitive, device) {
  if (defined(cache.indexGPUBuffer)) {
    return;
  }
  const indices = primitive._indices;
  if (!defined(indices)) {
    return;
  }

  const needsU32 = indices.BYTES_PER_ELEMENT === 4;
  const typed = needsU32 ? new Uint32Array(indices) : new Uint16Array(indices);
  cache.indexFormat = needsU32 ? "uint32" : "uint16";
  cache.indexGPUBuffer = device.createBuffer({
    label: "Vector3DTilePolylines IB",
    size: typed.byteLength,
    usage: GPUBufferUsage.INDEX | GPUBufferUsage.COPY_DST,
  });
  device.queue.writeBuffer(cache.indexGPUBuffer, 0, typed);
  cache.indexCount = indices.length;
}

function ensureBatchColorStorage(cache, primitive, device) {
  const featuresLength =
    primitive._batchTable?.featuresLength ??
    primitive._batchIds?.length ??
    INITIAL_BATCH_BUFFER_FEATURES;
  const requiredBytes = Math.max(
    featuresLength * BYTES_PER_BATCH_COLOR,
    INITIAL_BATCH_BUFFER_FEATURES * BYTES_PER_BATCH_COLOR,
  );

  if (
    defined(cache.batchColorBuffer) &&
    cache.batchColorBufferCapacity >= requiredBytes
  ) {
    return;
  }
  if (defined(cache.batchColorBuffer)) {
    cache.batchColorBuffer.destroy();
  }
  cache.batchColorBuffer = device.createBuffer({
    label: "Vector3DTilePolylines batch colors",
    size: requiredBytes,
    usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
  });
  cache.batchColorBufferCapacity = requiredBytes;
  cache.batchColorScratch = new Float32Array(requiredBytes / 4);
  cache._sharedBindGroupDirty = true;
}

function uploadBatchColors(cache, primitive, device) {
  const scratch = cache.batchColorScratch;
  if (!defined(scratch)) {
    return;
  }

  // Vector3DTilePolylines doesn't carry `_batchedIndices` (each polyline is
  // its own draw conceptually) — colors live on the batch table. Default
  // every feature to the primitive's `_highlightColor`; the batch table
  // overrides per feature when `applyStyle` evaluates.
  const highlight = primitive._highlightColor;
  const r = highlight?.red ?? 1.0;
  const g = highlight?.green ?? 1.0;
  const b = highlight?.blue ?? 1.0;
  const a = highlight?.alpha ?? 1.0;
  for (let i = 0; i < scratch.length; i += 4) {
    scratch[i] = r;
    scratch[i + 1] = g;
    scratch[i + 2] = b;
    scratch[i + 3] = a;
  }

  // AUDIT_2026_05_02 B.1 — fold per-feature `Cesium3DTileFeature.show`
  // into batch alpha so the FS discard branch hides set-show-false
  // features without needing a second storage buffer.
  const batchTable = primitive._batchTable;
  if (defined(batchTable) && typeof batchTable.getShow === "function") {
    const featuresLength = batchTable.featuresLength ?? 0;
    for (let id = 0; id < featuresLength; id++) {
      const slot = id * 4 + 3;
      if (slot >= scratch.length) {
        break;
      }
      if (!batchTable.getShow(id)) {
        scratch[slot] = 0.0;
      }
    }
  }

  device.queue.writeBuffer(
    cache.batchColorBuffer,
    0,
    scratch.buffer,
    scratch.byteOffset,
    cache.batchColorBufferCapacity,
  );
}

function ensurePickColorStorage(cache, primitive, device) {
  // Mirrors `ensureBatchColorStorage`. The pick-color storage buffer is
  // bound at @group(0) @binding(2) and is required by the BGL even when
  // the pick pipeline isn't running this frame — WebGPU forbids
  // partial bind groups. Always allocated, sized to match the batch
  // buffer.
  const featuresLength =
    primitive._batchTable?.featuresLength ??
    primitive._batchIds?.length ??
    INITIAL_BATCH_BUFFER_FEATURES;
  const requiredBytes = Math.max(
    featuresLength * BYTES_PER_BATCH_COLOR,
    INITIAL_BATCH_BUFFER_FEATURES * BYTES_PER_BATCH_COLOR,
  );

  if (
    defined(cache.pickColorBuffer) &&
    cache.pickColorBufferCapacity >= requiredBytes
  ) {
    return;
  }
  if (defined(cache.pickColorBuffer)) {
    cache.pickColorBuffer.destroy();
  }
  cache.pickColorBuffer = device.createBuffer({
    label: "Vector3DTilePolylines pick colors",
    size: requiredBytes,
    usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
  });
  cache.pickColorBufferCapacity = requiredBytes;
  cache.pickColorScratch = new Float32Array(requiredBytes / 4);
  cache._sharedBindGroupDirty = true;
  cache._pickColorsUploaded = false;
}

function uploadPickColors(cache, primitive, device) {
  const scratch = cache.pickColorScratch;
  if (!defined(scratch)) {
    return;
  }
  scratch.fill(0);

  const batchTable = primitive._batchTable;
  if (defined(batchTable) && typeof batchTable.getPickColor === "function") {
    const length = batchTable.featuresLength ?? 0;
    for (let i = 0; i < length; i++) {
      const pickId = batchTable.getPickColor(i);
      const color = pickId?.color;
      if (!defined(color)) {
        continue;
      }
      const slot = i * 4;
      if (slot + 3 < scratch.length) {
        scratch[slot] = color.red;
        scratch[slot + 1] = color.green;
        scratch[slot + 2] = color.blue;
        scratch[slot + 3] = color.alpha;
      }
    }
  }

  device.queue.writeBuffer(
    cache.pickColorBuffer,
    0,
    scratch.buffer,
    scratch.byteOffset,
    cache.pickColorBufferCapacity,
  );
}

function createWebGPUVector3DTilePolylineCommands(primitive, frameState) {
  const context = frameState.context;
  const device = context.device;

  // AUDIT_2026_05_02 A.4 (Batch 150) — non-SCENE3D scene mode gate.
  // 3D-positions-only VS; 2D / Columbus View positions are not part
  // of the Vector3DTilePolylines geometry stream (verified Batch 158
  // — only RTC-relative 3D positions exist, identical to upstream
  // WebGL).
  //
  // **Batch 207** — MORPHING is now allowed through. During morph,
  // the camera + view/projection matrices interpolate via
  // `frameState.morphTime` (1.0 = full 3D ↔ 0.0 = full 2D). Our
  // `packUniforms` reads `uniformState.view` + `uniformState.projection`
  // which already reflect that interpolation, so feeding the existing
  // ECEF/RTC positions through the morph-aware matrices renders the
  // polylines in their 3D world position during the transition —
  // they fade out of frame as the camera approaches 2D, matching
  // the animation users expect when 3D-only tile content morphs.
  // SCENE2D + COLUMBUS_VIEW remain gated because the 3D positions
  // would project to wandering points (no 2D attribute path).
  const sceneMode = frameState?.mode;
  if (sceneMode !== SceneMode.SCENE3D && sceneMode !== SceneMode.MORPHING) {
    //>>includeStart('debug', pragmas.debug);
    oneTimeWarning(
      "WebGPUVector3DTilePolylines.sceneMode",
      "Vector3DTilePolylines on WebGPU is currently only correct in " +
        "SceneMode.SCENE3D and SceneMode.MORPHING. SCENE2D / Columbus View " +
        "are silently skipped (no 2D position attribute path — matches " +
        "upstream WebGL behavior for this primitive type). Tracked as " +
        "A.4 / NEW-CLASSIFIER-2D-CV-MORPH in DEFERRED_WORK.md.",
    );
    //>>includeEnd('debug');
    return { colorCommands: [], pickCommands: [] };
  }

  if (!defined(primitive._webgpuCache)) {
    primitive._webgpuCache = {};
  }
  const cache = primitive._webgpuCache;

  const sceneGen = context._scenePipelineFormatGeneration ?? 0;
  // NEW-CLASSIFIER-LOG-DEPTH (Batch 266) — rebuild on LOG_DEPTH master-switch
  // flip (or a frame toggling frameState.useLogDepth). Mirrors the
  // GroundPrimitive `_pipelineLogDepth` flip guard.
  const logDepthActive = isWebGPULogDepthActive(context, frameState);
  if (
    defined(cache._pipelineResources) &&
    (cache._pipelineFormatGeneration !== sceneGen ||
      cache._pipelineLogDepth !== logDepthActive)
  ) {
    cache._pipelineResources = undefined;
    cache.colorPipeline = undefined;
    cache.pickPipeline = undefined;
    // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — clear the
    // velocity pipeline alongside color/pick on format change so the
    // resolver re-runs against the new presentation format. Mirrors
    // the Batch 176 audit fix that surfaced the same gap on splats.
    cache.velocityPipeline = undefined;
    cache.sharedBindGroup = undefined;
  }
  if (!defined(cache._pipelineResources)) {
    const format = context.scenePipelineFormat || "bgra8unorm";
    const depthFmt = context.depthFormat || "depth24plus-stencil8";
    const sampleCount = context._msaaSamples ?? 1;
    cache._pipelineResources = buildPolylinePipelineResources(
      device,
      format,
      depthFmt,
      logDepthActive,
      sampleCount,
      // NEW-WEBGPU-HDR-PICK-FORMAT-CLOSURE — pick target format authority.
      context.pickPipelineFormat || "rgba8unorm",
    );
    cache._pipelineFormatGeneration = sceneGen;
    cache._pipelineLogDepth = logDepthActive;
    cache.colorRequestPending = false;
    cache.pickRequestPending = false;
    // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — pending-
    // flag init parity with the existing flags (caught as an audit
    // observation on Batch 178; applying preemptively here).
    cache.velocityRequestPending = false;
  }
  if (
    !tryResolvePipelines(
      device,
      context.webgpuPipelineCache ?? null,
      cache._pipelineResources,
      cache,
    )
  ) {
    return { colorCommands: [], pickCommands: [] };
  }

  if (!defined(cache.uniformBuffer)) {
    cache.uniformBuffer = WebGPUBuffer.createUniformBuffer(
      device,
      UNIFORM_BUFFER_SIZE,
      "Vector3DTilePolylines uniforms",
    );
    cache.uniformData = new Float32Array(UNIFORM_BUFFER_SIZE / 4);
  }
  ensureBatchColorStorage(cache, primitive, device);
  ensurePickColorStorage(cache, primitive, device);
  if (cache._sharedBindGroupDirty || !defined(cache.sharedBindGroup)) {
    cache.sharedBindGroup = device.createBindGroup({
      label: "Vector3DTilePolylines BG",
      layout: cache._pipelineResources.sharedBgl,
      entries: [
        { binding: 0, resource: { buffer: cache.uniformBuffer.buffer } },
        { binding: 1, resource: { buffer: cache.batchColorBuffer } },
        { binding: 2, resource: { buffer: cache.pickColorBuffer } },
      ],
    });
    cache._sharedBindGroupDirty = false;
  }

  ensureVertexBuffer(cache, primitive, device);
  ensureIndexBuffer(cache, primitive, device);
  if (!defined(cache.vertexGPUBuffer) || !defined(cache.indexGPUBuffer)) {
    return { colorCommands: [], pickCommands: [] };
  }

  packUniforms(cache.uniformData, frameState, primitive);
  device.queue.writeBuffer(
    cache.uniformBuffer.buffer,
    0,
    cache.uniformData.buffer,
    0,
    UNIFORM_BUFFER_SIZE,
  );

  // AUDIT_2026_05_02 B.1 — re-upload when batch table reports dirty
  // values (e.g., per-feature `show` toggle). Without this trigger, the
  // initial upload runs once on first frame and `feature.show = false`
  // never reaches the storage buffer.
  // (Audit-rereview correction: _batchValuesDirty lives on the
  // batchTable's _batchTexture, not on _batchTable directly.)
  const batchValuesDirty =
    primitive._batchTable?._batchTexture?._batchValuesDirty === true;
  if (!cache._batchColorsUploaded || batchValuesDirty) {
    uploadBatchColors(cache, primitive, device);
    cache._batchColorsUploaded = true;
  }
  if (!cache._pickColorsUploaded) {
    uploadPickColors(cache, primitive, device);
    cache._pickColorsUploaded = true;
  }

  // Pass.TRANSLUCENT — matches the WebGL Scene/Vector3DTilePolylines pass
  // assignment. The polyline depthBias in the pipeline pulls polylines
  // toward the camera so they lie on top of overlapping geometry.
  const colorCmd = new WebGPUDrawCommand({
    pipeline: cache.colorPipeline,
    bindGroups: [cache.sharedBindGroup],
    vertexBuffers: [cache.vertexGPUBuffer],
    indexBuffer: cache.indexGPUBuffer,
    indexFormat: cache.indexFormat,
    indexCount: cache.indexCount || 0,
    vertexCount: 0,
    pass: Pass.TRANSLUCENT,
    owner: primitive,
  });

  // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — derive
  // velocity command alongside the color command when TAA is on.
  // Same pattern as Vector3DTilePrimitive (Batch 178) and Voxel
  // (Batch 173): the velocity pass walks the command list for
  // `cmd.velocityCommand` and dispatches into the rg16float render
  // pass sharing scene depth read-only. Skipped when TAA is off —
  // static scenes pay nothing.
  if (frameState?.taaEnabled === true && defined(cache.velocityPipeline)) {
    colorCmd.velocityCommand = new WebGPUDrawCommand({
      pipeline: cache.velocityPipeline,
      bindGroups: [cache.sharedBindGroup],
      vertexBuffers: [cache.vertexGPUBuffer],
      indexBuffer: cache.indexGPUBuffer,
      indexFormat: cache.indexFormat,
      indexCount: cache.indexCount || 0,
      vertexCount: 0,
      pass: Pass.TRANSLUCENT,
      owner: primitive,
    });
  }

  const pickCommands = [];
  if (defined(cache.pickPipeline)) {
    pickCommands.push(
      new WebGPUDrawCommand({
        pipeline: cache.pickPipeline,
        bindGroups: [cache.sharedBindGroup],
        vertexBuffers: [cache.vertexGPUBuffer],
        indexBuffer: cache.indexGPUBuffer,
        indexFormat: cache.indexFormat,
        indexCount: cache.indexCount || 0,
        vertexCount: 0,
        pass: Pass.TRANSLUCENT,
        owner: primitive,
        pickOnly: true,
      }),
    );
  }

  return { colorCommands: [colorCmd], pickCommands };
}

function destroyWebGPUVector3DTilePolylineResources(primitive) {
  const cache = primitive._webgpuCache;
  if (!defined(cache)) {
    return;
  }
  if (defined(cache.uniformBuffer)) {
    cache.uniformBuffer.destroy();
  }
  if (defined(cache.batchColorBuffer)) {
    cache.batchColorBuffer.destroy();
  }
  if (defined(cache.pickColorBuffer)) {
    cache.pickColorBuffer.destroy();
  }
  if (defined(cache.vertexGPUBuffer)) {
    cache.vertexGPUBuffer.destroy();
  }
  if (defined(cache.indexGPUBuffer)) {
    cache.indexGPUBuffer.destroy();
  }
  primitive._webgpuCache = undefined;
}

export {
  createWebGPUVector3DTilePolylineCommands,
  destroyWebGPUVector3DTilePolylineResources,
};
export default {
  createWebGPUVector3DTilePolylineCommands,
  destroyWebGPUVector3DTilePolylineResources,
};
