/**
 * Froxel-grid participating media renderer (`CELESTIAL_ATMOSPHERE_DESIGN.md`
 * §4.8). Allocates the 3D texture pair (density + scattered light + integrated
 * volume), creates compute pipelines for the three Frostbite-style passes
 * (density injection, light scattering, ray-march integration), and
 * runs a final full-screen composite pass that samples the integrated
 * volume in screen UV + linearized depth and modulates the scene color.
 *
 * **Phase status (current — see VolumetricFog.wgsl for ground truth):**
 *   - **Phase 5b SHIPPED** — real height-fog density (`density × exp(-h × falloff)`),
 *     Henyey-Greenstein sun + moon in-scattering, front-to-back integration with
 *     Beer-Lambert + alpha-over composite. Composite reads the integrated volume.
 *   - **Phase 5c SHIPPED** — sun shadow-map sampling for in-scattering occlusion
 *     (god-ray formation). Falls back to fully-lit when `u.occlusion.x == 0` or
 *     no shadow map is bound.
 *   - **Phase 5d SHIPPED** — varying-density modulation via 3-octave value-noise
 *     FBM. Gated by `u.noise.x` (`enableVaryingDensity`).
 *   - **C-P7-RTE (Batch 26)** — altitude reconstruction via 2nd-order Taylor
 *     expansion around the camera; eliminates the `length(worldPos) - innerRadius`
 *     f32 cancellation that produced fog-density banding at orbital altitudes.
 *
 * The kernels are NOT placeholders. Don't be misled by the prior version of
 * this docstring (which described a Phase 5a no-op contract that no longer
 * matches the WGSL).
 *
 * Architecture:
 *   1. `update(context, frameState, scene)` — runs the three compute
 *      passes once per frame when `enableVolumetricFog` is true.
 *      Allocates GPU resources lazily on first call.
 *   2. `composite(context, frameState, colorView, depthView, outputView)` —
 *      runs the full-screen composite pass that samples the integrated
 *      volume and writes the modulated scene color to the output view.
 *      Wired into `WebGPUSceneRenderer._executeEnvironmentalEffects()`
 *      after procedural clouds / SSR / weather particles, before
 *      post-processing (matches B22 placement).
 *
 * Resource budget (medium quality, 160×90×128 = 1.8M froxels):
 *   - 2 × rgba16float 3D textures @ 1.8M voxels × 8 bytes = ~28 MB each
 *   - 1 × rgba16float 3D integrated volume = ~28 MB
 *   - Total: ~84 MB
 *
 * Quality bands:
 *   low    →  80 ×  45 ×  64  ≈  230K froxels  ≈  11 MB
 *   medium → 160 ×  90 × 128  ≈  1.8M froxels  ≈  84 MB
 *   high   → 240 × 135 × 192  ≈  6.2M froxels  ≈  300 MB
 *
 * The `auto` setting picks one of the above based on the
 * VisualPerformanceTargetService's init benchmark (B7/B17 lock).
 * @module WebGPUVolumetricFogRenderer
 */

/// <reference types="@webgpu/types" />

import Matrix4 from "../../Core/Matrix4.js";

// Scratch matrices for the per-frame inverse view-projection
// composition. The kernels need invVP for screen UV → world ray
// reconstruction; we compose `view × projection` then invert when the
// camera doesn't already cache the result.
const _scratchVP = new Matrix4();
const _scratchInvVP = new Matrix4();

// WGSL sources — auto-generated by `gulp build` via wgslToJavaScript.
import VolumetricFogComputeSource from "../../Shaders/WebGPU/Compute/VolumetricFog.js";
import VolumetricFogCompositeSource from "../../Shaders/WebGPU/PostProcess/VolumetricFogComposite.js";
import {
  makeBindGroupLayout,
  sampler,
  texture,
  uniformBuffer,
  Stage,
} from "./WebGPUBindGroupLayoutHelpers.js";
import { ShaderSourceId } from "./WebGPUShaderDefines.js";
import { WebGPUShaderModuleCache } from "./WebGPUShaderModuleCache.js";
import type {
  WebGPURenderPipelineCache,
  WebGPURenderPipelineDescriptor,
} from "./WebGPURenderPipelineCache.js";
import type { WebGPUComputePipelineCache } from "./WebGPUComputePipelineCache.js";
import { buildVolumetricFogResources } from "./WebGPUVolumetricFogResources.js";

// Per-device shader module cache so two contexts with volumetric fog
// enabled share one compiled `GPUShaderModule` per source.
// (C-R7-SHADER-MODULE-DEDUP, Batch 74.)
const _volumetricFogShaderModuleCaches = new WeakMap<
  GPUDevice,
  WebGPUShaderModuleCache
>();

export function getVolumetricFogShaderModuleCache(
  device: GPUDevice,
): WebGPUShaderModuleCache {
  let cache = _volumetricFogShaderModuleCaches.get(device);
  if (!cache) {
    cache = new WebGPUShaderModuleCache(device);
    _volumetricFogShaderModuleCaches.set(device, cache);
  }
  return cache;
}

/** Quality preset → 3D texture resolution mapping (W × H × D). */
export const QUALITY_RESOLUTIONS = {
  low: { width: 80, height: 45, depth: 64 },
  medium: { width: 160, height: 90, depth: 128 },
  high: { width: 240, height: 135, depth: 192 },
} as const;

export type QualityKey = keyof typeof QUALITY_RESOLUTIONS;

/** Number of floats in the VolumetricFogParams uniform buffer.
 *  Phase 5d layout (64 floats, 256 bytes):
 *    0..3   resolution (uint xyzw)
 *    4..7   scattering (near, maxDist, density, falloff)
 *    8..11  albedo + anisotropy
 *    12..27 invViewProj (mat4)
 *    28..43 sunShadowMatrix (mat4)
 *    44..47 cameraXYZ + innerRadius
 *    48..51 sunDirXYZ + sunIntensity
 *    52..55 moonDirXYZ + moonPhase × moonIntensity
 *    56..59 occlusion (enableScatteringOcclusion, ambientStrength,
 *                      shadowMapValid, shadowDarkness)
 *    60..63 noise (enableVaryingDensity, noiseScale, noiseStrength, _pad)
 */
// 72 floats (288 bytes) after Batch 26 — added 8 floats at offsets 64–71
// for the C-P7-RTE altitude reconstruction (cameraAltitudeRTE +
// altitudeCurvature). See the WGSL `VolumetricFogParams` struct for
// field layout.
//
// 84 floats (336 bytes) after Session 65 Batch 44 — appended 12 floats
// at offsets 72–83 for the Phase 6c cloud-shadow uniforms:
//   72..75  cloudShadow      (enable, layerBottom, layerTop, coverage)
//   76..79  cloudWindAndTime (windDir.xy, windSpeed, time)
//   80..83  cloudDensityShape (densityMultiplier, absorption,
//                              noiseScale, _pad)
//
// 88 floats (352 bytes) after Batch 420 — appended 4 floats at offsets
// 84–87 for the Phase C ground-fog uniforms:
//   84..87  groundFog        (enabled, intensity, bandHeight, peakDensity)
//
// 92 floats (368 bytes) after Batch 431 (FOG-IBL-AMBIENT) — appended 4
// floats at offsets 88–91 for the sky-LUT / IBL fog-ambient uniforms:
//   88..91  iblAmbient       (enable, atmosphereThickness, scale, _pad)
// When `enable` (offset 88) < 0.5 the scattering kernel takes the
// existing `ambientTerm = u.occlusion.y` branch byte-for-byte, so the
// OFF default consumes NONE of these floats — flag-off output is
// byte-identical to pre-Batch-431.
//
// 96 floats (384 bytes) after Batch 435 (FOG-TEMPORAL) — appended 4 floats
// at offsets 92–95 for the integrate-pass blue-noise jitter:
//   92..95  temporal (enableJitter, frameIndex, _pad, _pad)
// When `enableJitter` (offset 92) < 0.5 the integrate pass adds NO jitter
// to the slice depth, so the OFF default integrate output is byte-identical
// to pre-Batch-435 (the jitter is the ONLY thing offsets 92–95 drive, and
// it is gated to zero on the parity path).
//
// 116 floats (464 bytes) after Batch 437 (CLOUD-SHADOWS) — appended 20 floats
// at offsets 96–115 for the HI-FI cloud shadow (sample the beer shadow map
// instead of the local-fbm approximation):
//   96..99   cloudShadowHiFi      (enable, absorption, strength, _pad)
//   100..115 cloudShadowSunViewVP (mat4 — world ECEF → sun ortho clip)
// When `enable` (offset 96) < 0.5 the scattering kernel's `sampleCloudShadow`
// takes the existing local-fbm branch byte-for-byte, so the OFF default
// consumes NONE of these floats → byte-identical to pre-Batch-437.
//
// 124 floats (496 bytes) after Batch 440 (FOG-MS) — appended 8 floats at
// offsets 116–123 for the opt-in MULTIPLE-SCATTERING octaves:
//   116..119 multiScatter      (enable, octaves, decayA, decayB)
//   120..123 multiScatterPhase (decayC, _pad, _pad, _pad)
// When `enable` (offset 116) < 0.5 OR `octaves` (offset 117) <= 1, the
// scattering kernel takes the existing single HG-phase term byte-for-byte
// (octave 1 == single-scatter), so the OFF default consumes NONE of these
// floats → byte-identical to pre-Batch-440.
export const VOLUMETRIC_FOG_PARAMS_FLOATS = 124;
export const VOLUMETRIC_FOG_PARAMS_BYTES = VOLUMETRIC_FOG_PARAMS_FLOATS * 4;

/** CompositeUniforms float count: mat4 (16) + 2 × vec4 (8) = 24 floats. */
export const COMPOSITE_UNIFORMS_FLOATS = 24;
export const COMPOSITE_UNIFORMS_BYTES = COMPOSITE_UNIFORMS_FLOATS * 4;

/**
 * Batch 435 (FOG-TEMPORAL) — TemporalUniforms float count for the resolve
 * pass. MUST equal the WGSL `TemporalUniforms` struct length:
 *   previousViewProjection (mat4, 16) + invViewProj current (mat4, 16) +
 *   cameraAndInner (4) + resolution+near+far (vec4 ×… see below):
 *     0..15   previousViewProjection
 *     16..31  invViewProj (current frame — reconstruct froxel world pos)
 *     32..35  cameraAndInner   (camera.xyz, innerRadius)
 *     36..39  gridParams       (width, height, depth, _pad)  [as f32]
 *     40..43  depthParams      (near, far/maxDist, alpha, firstFrame)
 *   = 44 floats.
 */
export const FOG_TEMPORAL_UNIFORMS_FLOATS = 44;
export const FOG_TEMPORAL_UNIFORMS_BYTES = FOG_TEMPORAL_UNIFORMS_FLOATS * 4;

/**
 * Batch 435 (FOG-TEMPORAL) — per-frame exponential-accumulation blend alpha
 * (the fraction of the NEW jittered march folded in each frame; history keeps
 * 1−alpha). ~0.05 → ~20-frame effective history, enough to fully resolve the
 * jittered march while the neighborhood clamp keeps motion crisp.
 */
export const FOG_TEMPORAL_BLEND_ALPHA = 0.05;

/**
 * GPU resources owned by one VolumetricFog renderer instance. Allocated
 * lazily on first `update()` call and rebuilt when the resolution band
 * changes (quality preset switch or VPT auto-tune).
 */
export interface VolumetricFogResources {
  // Resolution band currently allocated. Used to detect quality changes.
  resolutionKey: QualityKey;
  width: number;
  height: number;
  depth: number;

  // 3D textures.
  densityTexture: GPUTexture;
  densityView: GPUTextureView;
  scatteringTexture: GPUTexture;
  scatteringView: GPUTextureView;
  integratedTexture: GPUTexture;
  integratedView: GPUTextureView;
  // Sampling view (filterable) for the composite pass — same texture
  // as `integratedView` but created with default usage so the composite
  // shader can sample it.
  integratedSampleView: GPUTextureView;

  // Compute pipelines — one per pass. Phase 5b uses three distinct
  // bind group layouts (and matching pipeline layouts) because the
  // density / scattering / integrate passes have different read-vs-write
  // texture access patterns and WGSL doesn't permit aliasing the same
  // `@binding` slot across access modes.
  computeShaderModule: GPUShaderModule;
  densityBindGroupLayout: GPUBindGroupLayout;
  densityPipeline: GPUComputePipeline;
  densityBindGroup: GPUBindGroup;
  scatteringBindGroupLayout: GPUBindGroupLayout;
  scatteringPipeline: GPUComputePipeline;
  // Phase 5c: scattering bind group is rebuilt when the bound sun
  // shadow map view changes (initially the placeholder, then the real
  // map once a shadow-casting sun is active).
  scatteringBindGroup: GPUBindGroup;
  scatteringBoundShadowView: GPUTextureView | null;
  integrateBindGroupLayout: GPUBindGroupLayout;
  integratePipeline: GPUComputePipeline;
  integrateBindGroup: GPUBindGroup;

  // Batch 435 (FOG-TEMPORAL) — DOUBLE-BUFFERED (ping-pong) 3D froxel HISTORY
  // pair + the reproject/clamp/blend resolve pipeline. ALL of this is the
  // OPT-IN path: on the default (temporal OFF) the history textures are a
  // shared 1×1×1 PLACEHOLDER (so the resolve BGL never forks and the
  // integrate pass output is byte-identical), the resolve pass is NEVER
  // dispatched, and the composite samples `integratedSampleView` exactly as
  // before. When temporal is ON the full-resolution history pair is
  // allocated lazily on first use, the integrate pass writes the raw current
  // march to `integratedTexture`, the resolve pass reprojects the previous
  // history + blends + writes the new history, and the composite samples the
  // freshly-written history instead.
  //
  // The history matches the froxel volume format/dims (rgba16float, W×H×D)
  // because it accumulates the integrated 3D scattering volume directly.
  // `temporalHistoryAllocated` is false until the real pair is built.
  temporalHistoryAllocated: boolean;
  temporalHistoryTexture: [GPUTexture | null, GPUTexture | null];
  temporalHistoryStorageView: [GPUTextureView | null, GPUTextureView | null];
  temporalHistorySampleView: [GPUTextureView | null, GPUTextureView | null];
  temporalRead: number; // ping-pong index (0/1) of the history to READ this frame
  temporalFirstFrame: boolean;
  // 1×1×1 placeholder history (storage + sample views) bound on the OFF path
  // so the resolve BGL stays constant and nothing forks.
  temporalPlaceholderTexture: GPUTexture;
  temporalPlaceholderStorageView: GPUTextureView;
  temporalPlaceholderSampleView: GPUTextureView;
  temporalResolveBindGroupLayout: GPUBindGroupLayout;
  temporalResolvePipeline: GPUComputePipeline;
  temporalUniformBuffer: GPUBuffer;
  temporalUniformData: Float32Array;
  temporalSampler: GPUSampler;
  // The resolve bind group is rebuilt only when the read/write history view
  // identities change (ping-pong flip / (re)allocation), so steady-state
  // cost is zero.
  temporalResolveBindGroup: GPUBindGroup | null;
  temporalBoundCurrentView: GPUTextureView | null;
  temporalBoundReadView: GPUTextureView | null;
  temporalBoundWriteView: GPUTextureView | null;

  // Phase 5c — sun shadow map placeholder + comparison sampler.
  // The placeholder is a 1×1 depth32float texture cleared to 1.0
  // (max depth = "fully lit"). When a real shadow map is bound the
  // scattering bind group is rebuilt to point at it; the placeholder
  // stays around for the fallback path.
  shadowPlaceholderTexture: GPUTexture;
  shadowPlaceholderView: GPUTextureView;
  shadowComparisonSampler: GPUSampler;

  // Batch 431 (FOG-IBL-AMBIENT) — sky-LUT / IBL ambient resources for the
  // scattering pass. Bound UNCONDITIONALLY (placeholders until the real
  // atmosphere TRANSMITTANCE LUT + atmosphere-derived SH buffer arrive)
  // so the scattering BGL never forks; the WGSL only samples them when the
  // `u.iblAmbient.x` flag is set (default 0 → byte-identical flat-constant
  // ambient).
  //   - 1×1 white rgba16float transmittance placeholder + a linear
  //     sampler for the (cosZenith, altitude) LUT lookup.
  //   - 160-byte zero-filled SH placeholder buffer (9 vec4 coeffs +
  //     control vec4 with control.w = 0 → SH contributes nothing). The
  //     real buffer is the scene env-manager's `_webgpuSHBuffer`.
  // The scattering bind group is rebuilt (alongside the shadow-view
  // rebuild) whenever the bound transmittance view or SH buffer changes.
  iblTransmittancePlaceholderTexture: GPUTexture;
  iblTransmittancePlaceholderView: GPUTextureView;
  iblLutSampler: GPUSampler;
  iblShPlaceholderBuffer: GPUBuffer;
  // The transmittance view + SH buffer currently bound in the scattering
  // bind group. Tracked so the rebuild only fires on an actual change.
  scatteringBoundTransmittanceView: GPUTextureView | null;
  scatteringBoundShBuffer: GPUBuffer | null;
  // Batch 437 (CLOUD-SHADOWS) — beer shadow map (binding 11) + sampler (12).
  // The placeholder (1×1 zero r16float → transmittance 1) is bound when the hi-fi
  // flag is off; the real cloud beer shadow map is bound when on. `scatteringBound
  // BeerShadowView` tracks the currently-bound view so the rebuild only fires on a
  // change.
  beerShadowPlaceholderTexture: GPUTexture;
  beerShadowPlaceholderView: GPUTextureView;
  beerShadowSampler: GPUSampler;
  scatteringBoundBeerShadowView: GPUTextureView | null;

  // Params uniform for the compute passes.
  paramsBuffer: GPUBuffer;
  paramsData: Float32Array;
  paramsU32: Uint32Array;

  // Composite pass resources.
  compositeShaderModule: GPUShaderModule;
  compositeBindGroupLayout: GPUBindGroupLayout;
  // C-R7-RENDERER-MIGRATION (Batch 74). The render pipeline is now
  // materialized through `webgpuPipelineCache.getPipeline()`. On the
  // first frame after enabling fog the pipeline kicks off async; until
  // it lands, `composite()` early-exits (one-frame visual gap, recovers
  // next frame). The `compositePipelineEntry` slot tracks the descriptor
  // + in-flight state for re-resolution.
  compositePipeline: GPURenderPipeline | null;
  compositePipelineEntry: {
    descriptor: WebGPURenderPipelineDescriptor;
    pipeline: GPURenderPipeline | null;
    pending: boolean;
  };
  compositeUniformBuffer: GPUBuffer;
  compositeUniformData: Float32Array;
  compositeSampler: GPUSampler;
  // Composite bind group — recreated when the input scene color/depth
  // texture views change (e.g., on resize). Cached on the bind group
  // build site to avoid every-frame allocation.
  compositeBindGroup: GPUBindGroup | null;
  compositeBoundColorView: GPUTextureView | null;
  compositeBoundDepthView: GPUTextureView | null;
  compositeBoundOutputFormat: GPUTextureFormat | null;
  // Batch 435 (FOG-TEMPORAL) — the 3D fog volume view currently bound at
  // composite binding 4 (raw integrated volume on the parity path, or the
  // resolved history view on the temporal path). Part of the bind-group cache
  // key so the bind group rebuilds when the ping-pong flips / temporal toggles.
  compositeBoundFogSourceView: GPUTextureView | null;
}

/**
 * Per-context state for the volumetric fog renderer. The feature
 * renderer creates one of these on first invocation and reuses it for
 * the lifetime of the GraphicsContext.
 */
class WebGPUVolumetricFogRenderer {
  private _device: GPUDevice;
  private _resources: VolumetricFogResources | null = null;
  private _isDestroyed = false;
  // C-R7-COMPUTE-PIPELINE-CACHE (Batch 76) — captured lazily on the
  // first `update()` call so `_ensureResources` can route the three
  // compute pipeline creations through the central cache.
  private _computePipelineCache: WebGPUComputePipelineCache | null = null;
  // Phase 6 audit fix — snapshot mode coordination state. The freezable
  // is registered on the scene's SnapshotModeService once on first
  // sight; it just toggles `_frozen`, which the per-frame `update()`
  // checks to skip the compute passes entirely. The service reference
  // is stashed so `destroy()` can unregister cleanly.
  private _frozen = false;
  private _snapshotRegistered = false;
  private _snapshotService: {
    registerFreezable(
      name: string,
      freezable: { freeze(): void; thaw(): void },
    ): void;
    unregisterFreezable(name: string): void;
  } | null = null;
  // Phase 6 debug surface — frame counters split between "compute
  // dispatched" and "skipped because frozen". Cheap to maintain and
  // tells the operator at a glance whether snapshot mode is biting.
  private _updatesDispatched = 0;
  private _updatesSkippedFrozen = 0;
  private _composites = 0;
  private _lastEnabled = false;
  // Batch 435 (FOG-TEMPORAL) — monotonic frame counter feeding the
  // integrate-pass blue-noise jitter seed, and the per-frame "was the resolve
  // pass run this frame" flag the composite reads to decide which 3D view to
  // sample (resolved history vs raw integrated volume).
  private _temporalFrameIndex = 0;
  private _temporalResolvedThisFrame = false;

  constructor(device: GPUDevice) {
    this._device = device;
  }

  /**
   * Returns a SnapshotFreezable-shaped object suitable for passing to
   * `SnapshotModeService.registerFreezable()`. Mirrors the pattern used
   * by `WebGPURenderBundleManager.asFreezable()` so the registration
   * site is symmetric and the spec layer can drive the contract
   * without faking out a GPU device.
   */
  asFreezable(): {
    name: string;
    freeze: () => void;
    thaw: () => void;
    isFrozen: () => boolean;
  } {
    return {
      name: "webgpu-volumetric-fog",
      freeze: () => {
        this._frozen = true;
      },
      thaw: () => {
        this._frozen = false;
      },
      isFrozen: () => this._frozen,
    };
  }

  /**
   * Diagnostic snapshot for the central debug surface
   * (`Scene.getDebugSnapshot()`). Pure read; safe to call any time.
   */
  getStatistics(): {
    enabled: boolean;
    frozen: boolean;
    snapshotRegistered: boolean;
    destroyed: boolean;
    resolutionKey: string | null;
    dimensions: { width: number; height: number; depth: number } | null;
    updatesDispatched: number;
    updatesSkippedFrozen: number;
    composites: number;
  } {
    const r = this._resources;
    return {
      enabled: this._lastEnabled,
      frozen: this._frozen,
      snapshotRegistered: this._snapshotRegistered,
      destroyed: this._isDestroyed,
      resolutionKey: r ? r.resolutionKey : null,
      dimensions: r
        ? { width: r.width, height: r.height, depth: r.depth }
        : null,
      updatesDispatched: this._updatesDispatched,
      updatesSkippedFrozen: this._updatesSkippedFrozen,
      composites: this._composites,
    };
  }

  /**
   * Resolve the active quality band from `atmosphericConditions.volumetricFog.quality`.
   *
   * An explicit `"low" | "medium" | "high"` is returned verbatim. For
   * `"auto"` (or unknown):
   *   - When the scene's VisualPerformanceTargetService is ENABLED
   *     (`scene.visualPerformanceTarget.enabled === true`, opt-in), resolve to
   *     the device-appropriate INIT tier via
   *     {@link VisualPerformanceTargetService#resolveInitialQualityTier}
   *     (4.13 FOG-AUTO-VPT, Batch 445). This is the one-shot capability
   *     classification — NOT the continuous frame-budget auto-tuner, which
   *     stays deferred.
   *   - Otherwise (VPT disabled — the default) → `"low"`, byte-identical to the
   *     pre-445 behavior.
   */
  private _resolveQuality(
    quality: string | undefined,
    scene: CesiumScene | undefined,
  ): QualityKey {
    if (quality === "high" || quality === "medium" || quality === "low") {
      return quality;
    }
    // "auto" or unknown. Only consult the VPT init benchmark when VPT is
    // explicitly enabled (opt-in); the default (VPT disabled) stays "low".
    const vpt = (
      scene as unknown as {
        visualPerformanceTarget?: {
          enabled?: boolean;
          resolveInitialQualityTier?: (
            device: GPUDevice,
          ) => "low" | "medium" | "high";
        };
      }
    )?.visualPerformanceTarget;
    if (
      vpt?.enabled === true &&
      typeof vpt.resolveInitialQualityTier === "function"
    ) {
      return vpt.resolveInitialQualityTier(this._device);
    }
    // VPT disabled (default) → conservative low, verbatim pre-445 behavior.
    return "low";
  }

  /**
   * Lazy-create or rebuild the GPU resources. Called from `update()` on
   * the first frame and whenever the quality band changes. Idempotent.
   */
  private _ensureResources(quality: QualityKey): VolumetricFogResources {
    if (this._resources && this._resources.resolutionKey === quality) {
      return this._resources;
    }
    if (this._resources) {
      this._destroyResources();
    }
    this._resources = buildVolumetricFogResources(
      this._device,
      quality,
      this._computePipelineCache,
    );
    return this._resources;
  }

  private _destroyResources(): void {
    if (!this._resources) return;
    const r = this._resources;
    r.densityTexture.destroy();
    r.scatteringTexture.destroy();
    r.integratedTexture.destroy();
    r.shadowPlaceholderTexture.destroy();
    // Batch 431 (FOG-IBL-AMBIENT) — release the sky-LUT / IBL placeholders.
    r.iblTransmittancePlaceholderTexture.destroy();
    r.iblShPlaceholderBuffer.destroy();
    // Batch 437 (CLOUD-SHADOWS) — release the beer-shadow-map placeholder.
    r.beerShadowPlaceholderTexture.destroy();
    // Batch 435 (FOG-TEMPORAL) — release the temporal ping-pong history pair +
    // placeholder + uniform buffer.
    r.temporalHistoryTexture[0]?.destroy();
    r.temporalHistoryTexture[1]?.destroy();
    r.temporalPlaceholderTexture.destroy();
    r.temporalUniformBuffer.destroy();
    r.paramsBuffer.destroy();
    r.compositeUniformBuffer.destroy();
    this._resources = null;
  }

  /**
   * Batch 435 (FOG-TEMPORAL) — lazily (re)allocate the DOUBLE-BUFFERED
   * (ping-pong) 3D froxel HISTORY pair, sized to the current froxel volume
   * (W×H×D, rgba16float — it accumulates the integrated volume). Re-created
   * when the dimensions change (quality switch rebuilds the whole resource set
   * so this only re-fires on the FIRST temporal frame after a rebuild). On
   * (re)allocation the first-frame flag is reset so the next resolve seeds an
   * identity history (no startup flash). Returns false (caller falls back to
   * the non-temporal path → raw integrate result) if anything can't build.
   */
  private _ensureTemporalHistory(r: VolumetricFogResources): boolean {
    if (
      r.temporalHistoryAllocated &&
      r.temporalHistoryTexture[0] &&
      r.temporalHistoryTexture[1]
    ) {
      return true;
    }
    try {
      const usage =
        GPUTextureUsage.STORAGE_BINDING | GPUTextureUsage.TEXTURE_BINDING;
      for (let i = 0; i < 2; i++) {
        const tex = this._device.createTexture({
          label: `VolumetricFog_TemporalHistory_${i}`,
          size: {
            width: r.width,
            height: r.height,
            depthOrArrayLayers: r.depth,
          },
          format: "rgba16float",
          dimension: "3d",
          usage,
        });
        r.temporalHistoryTexture[i] = tex;
        r.temporalHistoryStorageView[i] = tex.createView({
          label: `VolumetricFog_TemporalHistory_${i}_StorageView`,
          dimension: "3d",
        });
        r.temporalHistorySampleView[i] = tex.createView({
          label: `VolumetricFog_TemporalHistory_${i}_SampleView`,
          dimension: "3d",
        });
      }
      r.temporalRead = 0;
      r.temporalFirstFrame = true;
      r.temporalResolveBindGroup = null;
      r.temporalHistoryAllocated = true;
      return true;
    } catch (e) {
      // Permanent sentinel (CLAUDE.md null-target guard): the flag asked for
      // temporal but the history pair couldn't allocate — fall back to the
      // raw integrate result so the fog still renders. Real failure → no
      // pragma.
      console.error(
        `[CesiumJS:webgpu:ctx-?] VolumetricFog temporal history allocation failed (${r.width}x${r.height}x${r.depth}); falling back to non-temporal.`,
        e,
      );
      r.temporalHistoryTexture[0]?.destroy();
      r.temporalHistoryTexture[1]?.destroy();
      r.temporalHistoryTexture = [null, null];
      r.temporalHistoryStorageView = [null, null];
      r.temporalHistorySampleView = [null, null];
      r.temporalHistoryAllocated = false;
      return false;
    }
  }

  /**
   * Run the three compute passes for one frame. No-op when
   * `enableVolumetricFog` is off — caller is responsible for the
   * top-level toggle check, but we double-check here as defense in
   * depth.
   *
   * Phase 5a: dispatches the placeholder kernels that clear their
   * outputs. Phase 5b/5c populate density / scattering / integration
   * with real math.
   */
  update(
    context: CesiumGraphicsContext,
    frameState: CesiumFrameState,
    scene: CesiumScene,
  ): void {
    if (this._isDestroyed) return;
    const _scene = scene;
    const ac = frameState.atmosphericConditions;
    const vf = ac && ac.volumetricFog ? ac.volumetricFog : undefined;
    // Batch 420 — GROUND FOG owns its OWN activation path. Ground fog
    // implies fog, so the froxel passes run (and the mist renders) even
    // when the general `volumetricFog.enabled` master is off. We reuse
    // ALL the froxel infra (grid, scatter, integrate, composite); only
    // the density profile differs (the near-surface boost added in the
    // WGSL `densityInjection` pass). When ground fog is the sole driver,
    // the base height-fog density still comes from the volumetricFog
    // config defaults (or its leaf values if the user set them without
    // flipping `enabled`).
    const groundFog =
      ac && ac.effects && ac.effects.groundFog
        ? ac.effects.groundFog
        : undefined;
    const groundFogActive = groundFog?.enabled === true;
    const fogMasterOn = vf?.enabled === true;
    if (!fogMasterOn && !groundFogActive) {
      this._lastEnabled = false;
      return;
    }
    this._lastEnabled = true;

    const device: GPUDevice = context.device;
    if (!device) return;

    // C-R7-COMPUTE-PIPELINE-CACHE (Batch 76) — capture the central cache
    // before `_ensureResources` runs so the lazy compute-pipeline build
    // routes through it. The compute pipeline cache is a context-level
    // resource, so we read it on every update (cheap getter access)
    // rather than caching the reference indefinitely — this also picks
    // up the new cache instance after a device-loss invalidation.
    this._computePipelineCache = context.webgpuComputePipelineCache ?? null;

    // Batch 420 — `vf` is normally always defined (the AtmosphericConditions
    // facade always builds `volumetricFog`), but the ground-fog-only
    // activation path can technically reach here with `vf` falsy. Use
    // optional chaining + the `?? default` fallbacks already present below
    // so the base height-fog parameters resolve to their sensible defaults
    // when only ground fog is driving the render.
    const quality = this._resolveQuality(vf?.quality, scene);
    const r = this._ensureResources(quality);

    // Phase 6 audit fix — snapshot mode integration. When the snapshot
    // service has frozen the scene, the integrated 3D volume from the
    // previous frame is still visually correct (the camera is locked,
    // sun direction is locked, density field is unchanged). Skipping
    // the three compute dispatches saves ~2.7ms/frame at medium
    // resolution and is the entire reason snapshot mode exists.
    //
    // Late-registration pattern: each context's fog instance registers
    // its freezable on first sight. The freezable just toggles the
    // local `_frozen` flag — there's no separate cache to invalidate
    // because the integrated texture IS the cache.
    if (!this._snapshotRegistered && scene && scene.snapshotMode) {
      // Use asFreezable() so the registered closure matches the
      // direct-API path the spec layer drives.
      scene.snapshotMode.registerFreezable(
        "webgpu-volumetric-fog",
        this.asFreezable(),
      );
      this._snapshotRegistered = true;
      this._snapshotService = scene.snapshotMode;
    }
    if (this._frozen) {
      // Skip all three compute passes — last frame's integrated
      // volume is still bound and the composite pass will sample it.
      this._updatesSkippedFrozen++;
      return;
    }
    this._updatesDispatched++;

    // ── Pack params UBO ──
    // Resolution.
    r.paramsU32[0] = r.width;
    r.paramsU32[1] = r.height;
    r.paramsU32[2] = r.depth;
    r.paramsU32[3] = 0;
    // Scattering params.
    r.paramsData[4] = frameState.camera?.frustum?.near ?? 1.0;
    // Batch 421 — froxel march distance. The energy-conserving single-scatter
    // integration is BOUNDED (no whiteout overflow) but its dynamic range
    // over a 50 km march is compressed: a low grazing/horizon ray stays in
    // the ground band for tens of km, so even a thin band accumulates enough
    // optical depth to drive transmittance → 0 (opaque) on those rays — the
    // foreground terrain we want to see *through* the mist gets buried in
    // horizon haze. Capping the march to a few km for the ground-fog mist
    // keeps the near terrain see-through (short path = modest optical depth)
    // while still hazing the mid-distance, giving the graded look. The base
    // height-fog (master-on) path keeps the full configured distance so
    // distance haze still reaches the horizon.
    const froxelMaxDistance = vf?.maxDistance ?? 50000;
    r.paramsData[5] = froxelMaxDistance;
    // Batch 420 — base height-fog density. When the volumetricFog master is
    // OFF and ground fog is the SOLE driver (own-activation path), the base
    // height fog must contribute NOTHING — otherwise the default
    // `density = 1.0` floods the whole froxel grid (a full whiteout) and
    // the ground mist is lost in it. Zero the base density on the
    // ground-fog-only path so ONLY the near-surface boost (added in the
    // WGSL density pass) shapes the volume. With the master on, the base
    // fog keeps its configured density and the ground mist layers on top.
    r.paramsData[6] = fogMasterOn ? (vf?.density ?? 1.0) : 0.0;
    r.paramsData[7] = vf?.falloff ?? 0.0001;
    // Albedo + anisotropy.
    const albedo = vf?.fogAlbedo ?? { r: 0.9, g: 0.92, b: 0.95 };
    r.paramsData[8] = albedo.r;
    r.paramsData[9] = albedo.g;
    r.paramsData[10] = albedo.b;
    r.paramsData[11] = vf?.fogAnisotropy ?? 0.3;

    // Inverse view-projection matrix (offsets 12..27). The kernels
    // unproject screen UV + slice depth → world position via this.
    // Camera should provide it pre-computed; if not, compose it from
    // view × projection on the fly.
    const camera = frameState.camera;
    let invVP: ArrayLike<number> | undefined = camera?.inverseViewProjection;
    if (!invVP && camera) {
      // Compose view × projection then invert.
      Matrix4.multiply(
        camera.frustum.projectionMatrix,
        camera.viewMatrix,
        _scratchVP,
      );
      Matrix4.inverse(_scratchVP, _scratchInvVP);
      invVP = _scratchInvVP;
    }
    if (invVP) {
      for (let i = 0; i < 16; i++) {
        r.paramsData[12 + i] = invVP[i];
      }
    } else {
      // Identity fallback — produces a valid no-op composite when the
      // camera isn't ready yet (first frame edge case).
      for (let i = 0; i < 16; i++) {
        r.paramsData[12 + i] = i % 5 === 0 ? 1.0 : 0.0;
      }
    }

    // Phase 5c — sun shadow matrix (offsets 28..43). Fetched from the
    // first active shadow map on frameState. The kernel uses this to
    // project each froxel's world position into shadow clip space and
    // sample the depth comparison; god ray formation depends on this.
    // When no shadow map is active, fill identity (the kernel skips
    // sampling via `occlusion.z = 0` instead of relying on the matrix).
    const shadowMaps = frameState.shadowMaps;
    let activeShadowMap: CesiumShadowMap | null = null;
    if (Array.isArray(shadowMaps) && shadowMaps.length > 0) {
      activeShadowMap = shadowMaps[0] as CesiumShadowMap;
    }
    let sunShadowMatrix: ArrayLike<number> | null = null;
    let realShadowView: GPUTextureView | null = null;
    if (activeShadowMap?._shadowMapMatrix) {
      sunShadowMatrix = activeShadowMap._shadowMapMatrix;
      const shadowCache = activeShadowMap._webgpuCache;
      if (shadowCache?.depthTextureView) {
        realShadowView = shadowCache.depthTextureView;
      }
    }
    if (sunShadowMatrix) {
      for (let i = 0; i < 16; i++) {
        r.paramsData[28 + i] = sunShadowMatrix[i];
      }
    } else {
      // Identity placeholder. Kernel skips the sample so the contents
      // here don't matter functionally, but we keep them clean.
      for (let i = 0; i < 16; i++) {
        r.paramsData[28 + i] = i % 5 === 0 ? 1.0 : 0.0;
      }
    }

    // C-P7 (Batch 2): pick `min(radii)` as the inner radius so a
    // camera directly over a pole doesn't compute a negative altitude
    // (WGS84 polar radius is ~21 km smaller than equatorial). The ~21 km
    // equator undershoot is well inside the atmosphere's ~100 km
    // thickness.
    //
    // C-P7-RTE (Batch 26): in-shader altitude reconstruction used to
    // compute `length(worldPos) - innerRadius` in f32 — both terms are
    // ~6.4e6 m at Earth radius, so the f32 difference had ~1 m ulp and
    // produced visible fog-density banding at orbital altitudes. We now
    // precompute `cameraAltitude = length(camPos) - innerRadius` in f64
    // on the CPU, upload it alongside the unit-length `cameraUp`
    // direction, and compute per-froxel altitude as a 2nd-order Taylor
    // expansion around the camera. See `cameraAltitudeRTE` in
    // VolumetricFog.wgsl for the math.
    const camPos = camera?.positionWC;
    const cx = camPos?.x ?? 0;
    const cy = camPos?.y ?? 0;
    const cz = camPos?.z ?? 0;
    r.paramsData[44] = cx;
    r.paramsData[45] = cy;
    r.paramsData[46] = cz;
    const globeEllipsoid = _scene?.globe?._ellipsoid as
      { radii: CesiumCartesian3 } | undefined;
    const innerRadius = globeEllipsoid
      ? Math.min(
          globeEllipsoid.radii.x,
          globeEllipsoid.radii.y,
          globeEllipsoid.radii.z,
        )
      : 6356752; // WGS84 polar radius
    r.paramsData[47] = innerRadius;

    // C-P7-RTE — compute altitude terms in f64 on the CPU so the
    // shader can reconstruct altitude without f32 cancellation. At
    // Earth scale, JS's native f64 (Math.sqrt, arithmetic) keeps the
    // result precise to sub-millimeter; splitting the work between
    // CPU-f64 and GPU-f32 is the standard RTE pattern.
    const cMag = Math.sqrt(cx * cx + cy * cy + cz * cz);
    const cameraAltitude = cMag - innerRadius;
    const invMag = cMag > 0 ? 1.0 / cMag : 0.0;
    // Unit vector from Earth center through the camera (well-conditioned
    // even at orbital altitudes because cMag >> 0).
    const upX = cx * invMag;
    const upY = cy * invMag;
    const upZ = cz * invMag;
    // Slots 64–67: cameraAltitudeRTE (cameraUp.xyz + cameraAltitude)
    r.paramsData[64] = upX;
    r.paramsData[65] = upY;
    r.paramsData[66] = upZ;
    r.paramsData[67] = cameraAltitude;
    // Slots 68–71: altitudeCurvature (oneOverDenom + pad).
    // The denominator (2 * (innerRadius + cameraAltitude)) = 2 * cMag.
    // Guard against cMag=0 (not physical, but keeps the shader's
    // multiply well-behaved during teardown).
    r.paramsData[68] = cMag > 0 ? 1.0 / (2.0 * cMag) : 0.0;
    r.paramsData[69] = 0.0;
    r.paramsData[70] = 0.0;
    r.paramsData[71] = 0.0;

    // Sun direction + intensity (offsets 48..51).
    const sunDir = frameState.sunDirectionWC;
    r.paramsData[48] = sunDir?.x ?? 0;
    r.paramsData[49] = sunDir?.y ?? 0;
    r.paramsData[50] = sunDir?.z ?? 1;
    // Sun intensity — currently a constant; Phase 1.4 humidity / airQuality
    // already modulate the LUT, so the sun-as-light intensity through
    // fog is the same as the LUT input. Hard-code 1.0 for the kernel
    // and let the albedo + density carry the rest.
    r.paramsData[51] = 1.0;

    // Moon direction + (phase × intensity) (offsets 52..55).
    const moonDir = frameState.moonDirectionWC;
    r.paramsData[52] = moonDir?.x ?? 0;
    r.paramsData[53] = moonDir?.y ?? 0;
    r.paramsData[54] = moonDir?.z ?? 1;
    const moonPhase = frameState.moonPhaseFraction ?? 1.0;
    const moonIntensity = ac?.lighting?.moonIntensity ?? 0.05;
    r.paramsData[55] = moonPhase * moonIntensity;

    // Phase 5c — occlusion controls (offsets 56..59).
    //   x = enableScatteringOcclusion (B20: default FALSE)
    //   y = ambientStrength (constant for now; Phase 5e can wire LUT)
    //   z = shadowMapValid (kernel skips sample when 0)
    //   w = shadowDarkness (matches the WebGPU shadow renderer's `darkness`)
    const occlusionEnabled = vf?.enableScatteringOcclusion === true;
    r.paramsData[56] = occlusionEnabled ? 1.0 : 0.0;
    // Batch 421 — ground mist is dominated by sky/ambient in-scatter (it is
    // lit by the whole sky dome far more than by direct forward sun-scatter),
    // so a higher ambient floor makes the energy-conserving mist read as a
    // believable milky fill rather than a dim grey. The base height-fog path
    // keeps the dimmer 0.05 default. This only runs when fog/ground fog is
    // active, so the OFF default is unchanged.
    // Batch 421 — ground mist is dominated by sky/ambient in-scatter: it is
    // lit by the whole sky dome far more than by direct forward sun-scatter.
    // A bright ambient floor makes the energy-conserving mist read as a
    // believable MILKY fill that roughly replaces the scene luminance the
    // transmittance removes (so a thin mist hazes rather than darkens). The
    // base height-fog (master-on) path keeps the dimmer configured value.
    // This branch only runs when fog/ground fog is active, so the OFF default
    // is unchanged.
    const ambientStrengthValue = groundFogActive
      ? Math.max(vf?.ambientStrength ?? 0, 0.7)
      : (vf?.ambientStrength ?? 0.05);
    r.paramsData[57] = ambientStrengthValue;
    r.paramsData[58] = realShadowView ? 1.0 : 0.0;
    r.paramsData[59] = activeShadowMap?.darkness ?? 0.3;

    // Phase 5d — varying atmosphere density (offsets 60..63).
    // Sourced from `atmosphericConditions.varyingAtmosphereDensity` —
    // a sibling leaf to volumetricFog. Per B21, this is silently a
    // no-op when volumetricFog is off (we only run the kernels at all
    // when vf.enabled is true), so reading it here is fine.
    const varyingRaw = ac?.varyingAtmosphereDensity;
    const varying = typeof varyingRaw === "object" ? varyingRaw : undefined;
    const varyingEnabled = varying?.enabled === true;
    r.paramsData[60] = varyingEnabled ? 1.0 : 0.0;
    r.paramsData[61] = varying?.noiseScale ?? 5000;
    r.paramsData[62] = varying?.noiseStrength ?? 0.3;
    r.paramsData[63] = 0.0;

    // Phase 6c — Cloud-shadow uniforms (offsets 72..83). Sourced from the managed
    // default cloud collection's `.volumetric` config (matching what
    // `WebGPUProceduralCloudRenderer` reads). The feature is gated to "fog is on
    // AND clouds are on AND coverage > 0" — when any of those are false, the WGSL
    // `sampleCloudShadow` short-circuits to 1.0 (no attenuation) so the fog
    // scattering is unchanged from pre-Batch-44 behaviour.
    // Cloud-unification epic slice 4B — the cloud-shadow config re-homes off the
    // removed `globe.cloud*` / `globe.showProceduralClouds` fields onto the managed
    // default cloud collection (`globe.defaultCloudCollection`). Clouds are active
    // when its exclusive `renderMode` is VOLUMETRIC (=== 1) AND `volumetric.enabled`
    // — identical to the `atmosphericConditions.clouds.enableVolumetric` facade.
    const volColl = (
      scene as unknown as {
        globe?: {
          defaultCloudCollection?: {
            renderMode?: number;
            volumetric?: {
              enabled?: boolean;
              cloudCoverage?: number;
              cloudDensity?: number;
              cloudLayerBottom?: number;
              cloudLayerTop?: number;
            };
          };
        };
      }
    ).globe?.defaultCloudCollection;
    const vol = volColl?.volumetric;
    const cloudsEnabled =
      volColl?.renderMode === 1 &&
      vol?.enabled === true &&
      (vol?.cloudCoverage ?? 0) > 0;
    const cloudShadowEnable = cloudsEnabled ? 1.0 : 0.0;
    r.paramsData[72] = cloudShadowEnable;
    r.paramsData[73] = vol?.cloudLayerBottom ?? 1500;
    r.paramsData[74] = vol?.cloudLayerTop ?? 4000;
    r.paramsData[75] = vol?.cloudCoverage ?? 0.5;

    // Wind state + time for cloud animation matching ProceduralClouds'
    // wind-drift offset. Read from `atmosphericConditions.weather` when
    // present (Phase 4 wiring); otherwise default to calm.
    const weather = ac?.weather as
      | {
          windDirection?: { x: number; y: number; z: number };
          windSpeed?: number;
        }
      | undefined;
    // Map a 3D wind direction onto the horizontal XZ plane the cloud
    // renderer uses. If wind is purely vertical, project to (0, 0) so
    // the noise stays static — matches ProceduralClouds' XZ-only wind.
    const wd = weather?.windDirection;
    const wdx = wd?.x ?? 0;
    const wdz = wd?.z ?? 0;
    r.paramsData[76] = wdx;
    r.paramsData[77] = wdz;
    r.paramsData[78] = weather?.windSpeed ?? 0;
    // Time in seconds since scene start — used together with windSpeed
    // to produce a drifting cloud-noise offset. The cloud renderer reads
    // its own `time` uniform from a similar source so the cast shadows
    // animate in sync with the visible clouds.
    const julianTime = (
      frameState.time as unknown as
        | {
            getValue?: () => { dayNumber?: number; secondsOfDay?: number };
          }
        | undefined
    )?.getValue?.();
    r.paramsData[79] =
      (julianTime?.dayNumber ?? 0) * 86400 + (julianTime?.secondsOfDay ?? 0);

    // Density shape uniforms. `densityMultiplier` mirrors the cloud
    // render's `cloud.densityMultiplier` default (0.3 in
    // ProceduralCloudRenderer). `absorptionCoeff` mirrors that
    // renderer's default (0.04). `noiseScale` is 0.0003 to match the
    // cloud render's `samplePos = worldPos * 0.0003` mapping so cast
    // shadows track the same feature scale as the visible clouds.
    r.paramsData[80] = vol?.cloudDensity ?? 0.3;
    r.paramsData[81] = 0.04;
    r.paramsData[82] = 0.0003;
    r.paramsData[83] = 0.0;

    // Batch 420 — GROUND FOG uniforms (offsets 84..87). Sourced from
    // `atmosphericConditions.effects.groundFog` (computed above). When the
    // master `effects.auto` is on, the AtmosphericEffects mapper derives
    // `enabled`/`intensity` from the temperature−dewpoint spread in humid
    // air; otherwise the app sets them directly. The WGSL `densityInjection`
    // pass adds `intensity × peakDensity × exp(-altitude / bandHeight)` to
    // the base height-fog density only when `enabled` (offset 84) ≥ 0.5,
    // so the OFF default leaves the density field byte-identical.
    //
    //   84 = enabled (0/1)
    //   85 = intensity (0..1)
    //   86 = bandHeight (m) — exponential mist falloff scale. 120 m gives
    //        the classic morning-mist band hugging the lowest couple hundred
    //        metres; above ~3× this the boost is negligible.
    //   87 = peakDensity — the per-metre extinction a fully-saturated
    //        (intensity=1) ground froxel reaches at altitude 0.
    //
    //        Batch 421 — ENERGY-CONSERVING re-tune (graded mist, no whiteout).
    //        The froxel scatter integration is now energy-conserving
    //        single-scatter (per slice `inscatter = sourceRadiance ×
    //        (1 - exp(-σ·Δz))`, accumulated transmittance-weighted), so
    //        density maps to OPACITY via a smooth Beer-Lambert rolloff
    //        (`transmittance = exp(-Σσ·Δz)`). The actual whiteout ROOT CAUSE
    //        was the Henyey-Greenstein forward-scatter peak overflowing f16
    //        (the per-froxel `sourceRadiance` hit 65504), now fixed by a
    //        clamped HG in VolumetricFog.wgsl. With sourceRadiance bounded
    //        (~0.2 phase + 0.7 ambient floor for the milky fill) peakDensity
    //        is a real per-metre extinction: over the slant path through the
    //        ground band a fully-saturated froxel accumulates optical depth
    //        ~1 → transmittance ~0.1–0.5, a near-opaque-but-still-see-through
    //        mist at the surface that fades with altitude. The old ~1e-6
    //        binary cliff is gone; intensity now sweeps a usable 0..1
    //        mist-thickness range (probe-verified 0.3 / 0.6 / 1.0). See
    //        NEW-WEBGPU-FROXEL-FOG-SCATTER-DYNAMIC-RANGE.
    const groundFogIntensity =
      typeof groundFog?.intensity === "number" ? groundFog.intensity : 0.0;
    r.paramsData[84] = groundFogActive ? 1.0 : 0.0;
    r.paramsData[85] = groundFogIntensity;
    r.paramsData[86] = 120.0;
    r.paramsData[87] = 1.2e-4;

    // Batch 431 (FOG-IBL-AMBIENT) — sky-LUT / IBL fog-ambient uniforms
    // (offsets 88..91). When `iblAmbient` is on, the scattering kernel
    // replaces the flat-constant `ambientTerm = u.occlusion.y` with an
    // altitude- + time-of-day-correct ambient: a sample of the Bruneton
    // TRANSMITTANCE LUT at `(froxel altitude, view-up)` tinted by the
    // atmosphere-derived SH-L2 irradiance probe. Gated by offset 88; when
    // < 0.5 the WGSL takes the existing constant branch byte-for-byte, so
    // the OFF default is byte-identical to pre-Batch-431 (no float here
    // affects the flag-off output path).
    //
    //   88 = enable (0/1) — also implicitly 0 when no real transmittance
    //        LUT is bound yet (the placeholder is white = passthrough, so
    //        a stray sample can't darken; but we gate on the flag anyway).
    //   89 = atmosphereThickness (m) — MUST match the value the
    //        TRANSMITTANCE LUT was baked with (SkyAtmosphere's
    //        ATMOSPHERE_THICKNESS = 111e3) so the LUT `v = altitude /
    //        thickness` lookup lands on the right row.
    //   90 = ambient scale — reuses `ambientStrength` so the IBL ambient
    //        respects the same brightness knob as the constant path.
    //   91 = reserved (pad).
    const iblAmbientEnabled = vf?.iblAmbient === true;
    // Resolve the real transmittance LUT view + atmosphere-derived SH
    // buffer. Both are optional: the LUT exists once SkyAtmosphere has
    // baked it (compute-capable contexts), the SH buffer exists once a
    // model/tileset env-manager has run its SH projection. When either is
    // missing the placeholder stays bound and that term degrades to a
    // passthrough (white transmittance / zero SH) — the feature simply
    // produces a paler ambient, never an error.
    let realTransmittanceView: GPUTextureView | null = null;
    if (iblAmbientEnabled) {
      const perfMgr = (
        context as unknown as {
          performanceManager?: {
            ensureAtmosphereLUTResources?: (d: GPUDevice) => {
              transmittanceView?: GPUTextureView;
            } | null;
          };
        }
      ).performanceManager;
      if (perfMgr?.ensureAtmosphereLUTResources) {
        const res = perfMgr.ensureAtmosphereLUTResources(device);
        if (res?.transmittanceView) {
          realTransmittanceView = res.transmittanceView;
        }
      }
    }
    // Atmosphere-derived SH-L2 irradiance buffer from the scene's
    // environment-map manager (the same `_webgpuSHBuffer` the model PBR
    // path samples for diffuse IBL — Principle 9: it's baked but nothing
    // on the fog path read it until now). Optional; placeholder otherwise.
    let realShBuffer: GPUBuffer | null = null;
    if (iblAmbientEnabled) {
      const envManager = (
        scene as unknown as {
          environmentMapManager?: { _webgpuSHBuffer?: GPUBuffer | null };
        }
      ).environmentMapManager;
      if (envManager?._webgpuSHBuffer) {
        realShBuffer = envManager._webgpuSHBuffer;
      }
    }
    r.paramsData[88] = iblAmbientEnabled ? 1.0 : 0.0;
    r.paramsData[89] = 111000.0; // ATMOSPHERE_THICKNESS (matches the LUT bake)
    r.paramsData[90] = ambientStrengthValue;
    r.paramsData[91] = 0.0;

    // Batch 435 (FOG-TEMPORAL) — integrate-pass blue-noise jitter uniforms
    // (offsets 92..95). The flag is gated to "fog active AND vf.temporal".
    // When off, offset 92 is 0.0 → the integrate march adds NO jitter and is
    // byte-identical to pre-Batch-435 (the jitter is the ONLY consumer of
    // these floats). `frameIndex` is a monotonic counter feeding the
    // interleaved-gradient blue-noise seed (golden-ratio frame rotation in
    // WGSL). This branch only runs when fog is active, so the OFF default is
    // unchanged.
    const temporalEnabled = vf?.temporal === true;
    r.paramsData[92] = temporalEnabled ? 1.0 : 0.0;
    r.paramsData[93] = this._temporalFrameIndex % 64;
    r.paramsData[94] = 0.0;
    r.paramsData[95] = 0.0;

    // Batch 437 (CLOUD-SHADOWS) — HI-FI cloud shadow uniforms (offsets 96..115).
    // Gated to "vf.cloudShadowHiFi AND the cloud renderer rendered a real beer
    // shadow map this frame (globe.cloudCastShadows on)". When off, offset 96 is
    // 0.0 → the scattering kernel's `sampleCloudShadow` takes the legacy local-fbm
    // branch byte-for-byte (parity default). The cloud renderer runs in the same
    // frame's environmental-effects chain BEFORE the fog, so the map + matrix are
    // current.
    const cloudCacheForFog = (
      frameState.context as unknown as {
        _cloudCache?: {
          shadowActive?: boolean;
          shadowView?: GPUTextureView | null;
          shadowSunViewVP?: Float32Array;
          shadowAbsorption?: number;
        };
      }
    )?._cloudCache;
    const cloudShadowHiFiOn =
      vf?.cloudShadowHiFi === true &&
      cloudCacheForFog?.shadowActive === true &&
      !!cloudCacheForFog.shadowView;
    r.paramsData[96] = cloudShadowHiFiOn ? 1.0 : 0.0;
    r.paramsData[97] = cloudCacheForFog?.shadowAbsorption ?? 0.04;
    r.paramsData[98] = 1.0; // strength
    r.paramsData[99] = 0.0;
    if (cloudShadowHiFiOn && cloudCacheForFog?.shadowSunViewVP) {
      const vp = cloudCacheForFog.shadowSunViewVP;
      for (let i = 0; i < 16; i++) r.paramsData[100 + i] = vp[i];
    } else {
      // Identity (never used when the gate is off).
      for (let i = 0; i < 16; i++)
        r.paramsData[100 + i] = i % 5 === 0 ? 1.0 : 0.0;
    }
    const desiredBeerShadowView = cloudShadowHiFiOn
      ? cloudCacheForFog!.shadowView!
      : r.beerShadowPlaceholderView;

    // Batch 440 (FOG-MS) — MULTIPLE-SCATTERING octave uniforms (offsets
    // 116..123). Gated to "vf.multiScatter AND msOctaves > 1". When off, offset
    // 116 is 0.0 AND/OR offset 117 is 1.0 → the scattering kernel takes the
    // single HG-phase term byte-for-byte (octave 1 == single-scatter), so the
    // OFF default is byte-identical to pre-Batch-440. The a/b/c geometric-decay
    // factors mirror the cloud renderer's defaults (msDecayA/B 0.5); decayC is
    // 0.5 here (a bit stronger isotropy relaxation than the cloud's 0.85) so the
    // deeper fog octaves fill the dense core softly. The MS term returns a gain
    // multiplier (>= 1) on the single-scatter forward term, capped by the slot-121
    // clamp so the dense-core lift can't blow out. This branch only runs when fog
    // is active, so the OFF default path is unchanged.
    const multiScatterEnabled = vf?.multiScatter === true;
    // Clamp octaves to [1, 8]: 1 == single-scatter (parity); beyond ~4 the
    // geometric decay makes octaves negligible, and 8 caps the loop cost.
    const rawOctaves =
      typeof vf?.msOctaves === "number" ? Math.round(vf.msOctaves) : 1;
    const msOctaves = Math.max(1, Math.min(8, rawOctaves));
    r.paramsData[116] = multiScatterEnabled ? 1.0 : 0.0;
    r.paramsData[117] = msOctaves;
    r.paramsData[118] = 0.5; // decayA — contribution per octave
    r.paramsData[119] = 0.5; // decayB — Beer extinction per octave
    r.paramsData[120] = 0.5; // decayC — HG phase eccentricity per octave
    // decayD slot reused as the MS lift CLAMP. The MS term only ADDS light
    // (gain >= 1); this caps how bright the dense-core lift gets so it stays
    // energy-conserving (a tasteful lit volume, not a blowout). 2.0 = at most
    // double the single-scatter forward term in the densest core.
    r.paramsData[121] = 2.0;
    // opticalDepthScale (offset 122) — maps the per-froxel density value the
    // `densityInjection` pass writes into a well-conditioned MS optical depth.
    // The energy-conserving fog spreads opacity over many individually-thin
    // froxels, so per-froxel density is small even in an opaque column; we tune
    // the scale so the DENSEST froxel (the near-surface, full-strength fog) lands
    // at optical depth ~3 (octave-0 Beer dark, deeper octaves lift it). The
    // densest froxel ≈ the base height-fog `density` (master path) or the ground-
    // fog `peakDensity × intensity` (ground-fog-only path — a much smaller
    // per-metre scale). Reference whichever drives the densest froxel so the
    // optical depth is well-conditioned in both modes; thinner (higher-altitude)
    // froxels scale down → gain ~1 (no MS there), so the lift bites only the core.
    const msGroundPeak = groundFogActive ? 1.2e-4 * groundFogIntensity : 0.0;
    const msBaseDensity = Math.max(
      fogMasterOn ? (vf?.density ?? 1.0) : 0.0,
      msGroundPeak,
      1e-4,
    );
    r.paramsData[122] = 3.0 / msBaseDensity;
    r.paramsData[123] = 0.0;

    // Rebuild the scattering bind group when the shadow view changes OR
    // (Batch 431) when the IBL transmittance LUT view / SH buffer changes.
    // The placeholder views are the initial state; once a real shadow map
    // / atmosphere LUT / atmosphere SH buffer arrives we swap to it. The
    // bind group rebuild is rare (only when a bound resource's identity
    // changes — typically once per viewer session) so the cost is
    // amortized to zero. When `iblAmbient` is off, the placeholder views
    // stay bound and the WGSL never samples them (flag-gated → parity).
    const desiredShadowView = realShadowView ?? r.shadowPlaceholderView;
    const desiredTransmittanceView =
      realTransmittanceView ?? r.iblTransmittancePlaceholderView;
    const desiredShBuffer = realShBuffer ?? r.iblShPlaceholderBuffer;
    if (
      r.scatteringBoundShadowView !== desiredShadowView ||
      r.scatteringBoundTransmittanceView !== desiredTransmittanceView ||
      r.scatteringBoundShBuffer !== desiredShBuffer ||
      r.scatteringBoundBeerShadowView !== desiredBeerShadowView
    ) {
      r.scatteringBindGroup = device.createBindGroup({
        label: "VolumetricFog_ScatteringBindGroup",
        layout: r.scatteringBindGroupLayout,
        entries: [
          { binding: 0, resource: { buffer: r.paramsBuffer } },
          { binding: 2, resource: r.densityView },
          { binding: 3, resource: r.scatteringView },
          { binding: 6, resource: desiredShadowView },
          { binding: 7, resource: r.shadowComparisonSampler },
          // Batch 431 (FOG-IBL-AMBIENT) — sky-LUT / IBL ambient.
          { binding: 8, resource: desiredTransmittanceView },
          { binding: 9, resource: r.iblLutSampler },
          { binding: 10, resource: { buffer: desiredShBuffer } },
          // Batch 437 (CLOUD-SHADOWS) — beer shadow map + sampler.
          { binding: 11, resource: desiredBeerShadowView },
          { binding: 12, resource: r.beerShadowSampler },
        ],
      });
      r.scatteringBoundShadowView = desiredShadowView;
      r.scatteringBoundTransmittanceView = desiredTransmittanceView;
      r.scatteringBoundShBuffer = desiredShBuffer;
      r.scatteringBoundBeerShadowView = desiredBeerShadowView;
    }

    device.queue.writeBuffer(
      r.paramsBuffer,
      0,
      r.paramsData.buffer,
      r.paramsData.byteOffset,
      r.paramsData.byteLength,
    );

    // ── Dispatch the three compute passes ──
    // Density and scattering: full 3D dispatch (W × H × D froxels).
    // Integrate: 2D dispatch (W × H), each thread serial-walks Z.
    //
    // Batch 420 — PRESENT-PATH FIX. Record the compute passes into the
    // MAIN frame command encoder when one is active, instead of creating a
    // private encoder and submitting it mid-frame. The mid-frame
    // `device.queue.submit()` of a private encoder splits the frame's GPU
    // work across two command buffers; the canvas write that the
    // `composite()` pass records into the main encoder afterward was being
    // lost (the magenta present-path probe showed 0% reaching the canvas,
    // while ProceduralClouds — which records entirely into the main encoder
    // and never submits mid-frame — reached the canvas at ~87%). Recording
    // the compute into the main encoder keeps the whole fog pipeline
    // (compute → composite → present) in a single ordered command buffer,
    // matching the proven ProceduralClouds path. Falls back to a private
    // encoder + immediate submit only when no main encoder exists (test
    // harnesses that bypass `beginFrame`).
    const mainComputeEncoder = (
      context as unknown as { _currentCommandEncoder?: GPUCommandEncoder }
    )._currentCommandEncoder;
    const useMainCompute = !!mainComputeEncoder;
    const encoder =
      mainComputeEncoder ??
      device.createCommandEncoder({
        label: "VolumetricFog_ComputeEncoder",
      });

    const wgX = Math.ceil(r.width / 8);
    const wgY = Math.ceil(r.height / 8);
    const wgZ = r.depth;

    {
      const pass = encoder.beginComputePass({
        label: "VolumetricFog_DensityPass",
      });
      pass.setPipeline(r.densityPipeline);
      pass.setBindGroup(0, r.densityBindGroup);
      pass.dispatchWorkgroups(wgX, wgY, wgZ);
      pass.end();
    }
    {
      const pass = encoder.beginComputePass({
        label: "VolumetricFog_ScatteringPass",
      });
      pass.setPipeline(r.scatteringPipeline);
      pass.setBindGroup(0, r.scatteringBindGroup);
      pass.dispatchWorkgroups(wgX, wgY, wgZ);
      pass.end();
    }
    {
      const pass = encoder.beginComputePass({
        label: "VolumetricFog_IntegratePass",
      });
      pass.setPipeline(r.integratePipeline);
      pass.setBindGroup(0, r.integrateBindGroup);
      // Phase 5b: each thread walks the depth axis serially, so Z=1.
      pass.dispatchWorkgroups(wgX, wgY, 1);
      pass.end();
    }

    // ── Batch 435 (FOG-TEMPORAL) — temporal reprojection + accumulation ──
    // Dispatched ONLY when `vf.temporal` is on. Reprojects the previous
    // accumulated history via `previousViewProjection`, neighborhood-clamps it
    // (ghost rejection), and exponentially blends with the freshly-marched
    // (blue-noise-jittered) integrate result → writes the new history, which
    // the composite then samples. When off this whole block is skipped, the
    // composite samples the raw integrated volume, and the integrate output
    // (no jitter) is byte-identical to pre-Batch-435.
    this._temporalResolvedThisFrame = false;
    if (temporalEnabled && this._ensureTemporalHistory(r)) {
      const readIdx = r.temporalRead & 1;
      const writeIdx = readIdx ^ 1;
      const readSampleView = r.temporalHistorySampleView[readIdx];
      const writeStorageView = r.temporalHistoryStorageView[writeIdx];
      if (readSampleView && writeStorageView) {
        // Pack TemporalUniforms (44 floats — byte-locked to the WGSL struct).
        const td = r.temporalUniformData;
        // previousViewProjection (mat4, 16) — column-major, from UniformState.
        const us = (
          context as unknown as {
            uniformState?: { previousViewProjection?: ArrayLike<number> };
          }
        ).uniformState;
        const prevVP = us?.previousViewProjection;
        if (prevVP) {
          for (let i = 0; i < 16; i++) td[i] = prevVP[i];
        } else {
          // Identity fallback (first frame before UniformState has a prior VP).
          for (let i = 0; i < 16; i++) td[i] = i % 5 === 0 ? 1.0 : 0.0;
        }
        // invViewProj current (mat4, 16) — reuse the same matrix the integrate
        // march used so the resolve reconstructs identical froxel world pos.
        if (invVP) {
          for (let i = 0; i < 16; i++) td[16 + i] = invVP[i];
        } else {
          for (let i = 0; i < 16; i++) td[16 + i] = i % 5 === 0 ? 1.0 : 0.0;
        }
        // cameraAndInner (camera.xyz, innerRadius).
        td[32] = cx;
        td[33] = cy;
        td[34] = cz;
        td[35] = innerRadius;
        // gridParams (W, H, D as f32, pad).
        td[36] = r.width;
        td[37] = r.height;
        td[38] = r.depth;
        td[39] = 0.0;
        // depthParams (near, far/maxDist, alpha, firstFrame).
        td[40] = frameState.camera?.frustum?.near ?? 1.0;
        td[41] = froxelMaxDistance;
        td[42] = FOG_TEMPORAL_BLEND_ALPHA;
        td[43] = r.temporalFirstFrame ? 1.0 : 0.0;
        device.queue.writeBuffer(
          r.temporalUniformBuffer,
          0,
          td.buffer,
          td.byteOffset,
          td.byteLength,
        );

        // Rebuild the resolve bind group when the read/write history view
        // identities change (ping-pong flip / (re)allocation). Steady state
        // alternates between two cached configurations.
        if (
          r.temporalResolveBindGroup === null ||
          r.temporalBoundCurrentView !== r.integratedSampleView ||
          r.temporalBoundReadView !== readSampleView ||
          r.temporalBoundWriteView !== writeStorageView
        ) {
          r.temporalResolveBindGroup = device.createBindGroup({
            label: "VolumetricFog_TemporalResolveBindGroup",
            layout: r.temporalResolveBindGroupLayout,
            entries: [
              { binding: 0, resource: { buffer: r.temporalUniformBuffer } },
              { binding: 1, resource: r.integratedSampleView },
              { binding: 2, resource: readSampleView },
              { binding: 3, resource: r.temporalSampler },
              { binding: 4, resource: writeStorageView },
            ],
          });
          r.temporalBoundCurrentView = r.integratedSampleView;
          r.temporalBoundReadView = readSampleView;
          r.temporalBoundWriteView = writeStorageView;
        }

        const tPass = encoder.beginComputePass({
          label: "VolumetricFog_TemporalResolvePass",
        });
        tPass.setPipeline(r.temporalResolvePipeline);
        tPass.setBindGroup(0, r.temporalResolveBindGroup);
        // Full 3D dispatch over the froxel volume.
        tPass.dispatchWorkgroups(wgX, wgY, wgZ);
        tPass.end();

        // Ping-pong: next frame reads what we just wrote. Mark resolved so the
        // composite samples the freshly-written history view.
        r.temporalRead = writeIdx;
        r.temporalFirstFrame = false;
        this._temporalResolvedThisFrame = true;
      }
    } else if (!temporalEnabled && r.temporalHistoryAllocated) {
      // Flag was turned OFF after being on — free the history pair so the OFF
      // path goes back to zero extra memory (and re-seeds identity if it's
      // turned back on later).
      r.temporalHistoryTexture[0]?.destroy();
      r.temporalHistoryTexture[1]?.destroy();
      r.temporalHistoryTexture = [null, null];
      r.temporalHistoryStorageView = [null, null];
      r.temporalHistorySampleView = [null, null];
      r.temporalHistoryAllocated = false;
      r.temporalResolveBindGroup = null;
      r.temporalBoundReadView = null;
      r.temporalBoundWriteView = null;
    }

    this._temporalFrameIndex++;

    // Batch 420 — only submit when we created a PRIVATE encoder. When the
    // compute recorded into the main frame encoder, `endFrame()` submits it
    // together with the composite + present (single ordered command
    // buffer). Submitting the main encoder here would finish it prematurely
    // and break the rest of the frame.
    if (!useMainCompute) {
      device.queue.submit([encoder.finish()]);
    }
  }

  /**
   * Run the composite pass: full-screen triangle that samples the
   * integrated 3D volume in screen UV + linearized depth and writes
   * `out = sceneColor * transmittance + scatteredLight` to `outputView`.
   *
   * Phase 5a: with cleared volume contents, this is visually a no-op.
   * Caller is still responsible for checking `enableVolumetricFog` —
   * we early-out here as defense in depth.
   */
  composite(
    context: CesiumGraphicsContext,
    frameState: CesiumFrameState,
    colorView: GPUTextureView,
    depthView: GPUTextureView,
    outputView: GPUTextureView,
    outputFormat: GPUTextureFormat,
  ): void {
    if (this._isDestroyed || !this._resources) return;
    const ac = frameState.atmosphericConditions;
    const vf = ac && ac.volumetricFog ? ac.volumetricFog : undefined;
    // Batch 420 — mirror the own-activation gate from `update()`: the
    // composite must run (to show the mist) whenever EITHER the fog master
    // is on OR ground fog is active. Otherwise the integrated volume the
    // ground-fog density pass just wrote would never reach the screen.
    const groundFogActive = ac?.effects?.groundFog?.enabled === true;
    if (vf?.enabled !== true && !groundFogActive) return;

    const device: GPUDevice = context.device;
    if (!device) return;

    this._composites++;
    const r = this._resources;

    // AUDIT_2026_05_02 B.17 — VolumetricFog composite was built once
    // with `targets: [{ format: "bgra8unorm" }]` placeholder; when HDR
    // is enabled the actual outputView is `rgba16float`, the format
    // mismatch makes the renderpass produce a black frame plus a
    // validation warning. Rebuild the pipeline + cached entry whenever
    // the outputFormat changes so HDR + volumetric fog co-enabled
    // renders correctly.
    if (
      r.compositePipelineEntry.descriptor.fragment?.targets?.[0]?.format !==
      outputFormat
    ) {
      // Patch the descriptor in place; null the resolved pipeline so the
      // cache lookup below materializes a fresh one keyed on the new
      // descriptor hash.
      const target0 = r.compositePipelineEntry.descriptor.fragment
        ?.targets?.[0] as { format: GPUTextureFormat } | undefined;
      if (target0) target0.format = outputFormat;
      r.compositePipelineEntry.pipeline = null;
      r.compositePipelineEntry.pending = false;
      r.compositePipeline = null;
    }

    // C-R7-RENDERER-MIGRATION (Batch 74) — resolve the composite render
    // pipeline through the central cache. Skip the composite this frame
    // if the pipeline is still materializing — the integrated volume is
    // cleared (Phase 5a no-op) so a missed frame is invisible. By next
    // frame the pipeline is cached.
    if (!r.compositePipeline) {
      const pipelineCache =
        (
          context as unknown as {
            webgpuPipelineCache?: WebGPURenderPipelineCache | null;
          }
        ).webgpuPipelineCache ?? null;
      const entry = r.compositePipelineEntry;
      if (entry.pipeline) {
        r.compositePipeline = entry.pipeline;
      } else if (pipelineCache) {
        const sync = pipelineCache.getPipelineSync(entry.descriptor);
        if (sync) {
          entry.pipeline = sync;
          entry.pending = false;
          r.compositePipeline = sync;
        } else {
          if (!entry.pending) {
            entry.pending = true;
            pipelineCache
              .getPipeline(entry.descriptor)
              .then((p) => {
                entry.pipeline = p;
                entry.pending = false;
              })
              .catch(() => {
                entry.pending = false;
              });
          }
          return;
        }
      } else {
        // Fallback: no central cache.
        const desc = entry.descriptor;
        entry.pipeline = device.createRenderPipeline({
          label: desc.name,
          layout: desc.layout ?? "auto",
          vertex: {
            module: desc.vertex.module,
            entryPoint: desc.vertex.entryPoint,
            buffers: desc.vertex.buffers,
          },
          fragment: desc.fragment
            ? {
                module: desc.fragment.module,
                entryPoint: desc.fragment.entryPoint,
                targets: desc.fragment.targets,
              }
            : undefined,
          primitive: desc.primitive,
          depthStencil: desc.depthStencil,
          multisample: desc.multisample,
        });
        r.compositePipeline = entry.pipeline;
      }
    }

    // Pack the composite uniform buffer.
    const camera = frameState.camera;
    const inverseViewProjection = camera?.inverseViewProjection;
    if (inverseViewProjection) {
      for (let i = 0; i < 16; i++) {
        r.compositeUniformData[i] = inverseViewProjection[i];
      }
    } else {
      // Fallback to identity if the inverse VP isn't available — the
      // composite still produces the correct visual no-op because the
      // integrated volume is cleared, so depth-direction precision
      // doesn't matter.
      for (let i = 0; i < 16; i++) {
        r.compositeUniformData[i] = i % 5 === 0 ? 1.0 : 0.0;
      }
    }
    r.compositeUniformData[16] = camera?.frustum?.near ?? 1.0;
    r.compositeUniformData[17] = camera?.frustum?.far ?? 1.0e9;
    // Batch 421 — MUST match the compute pass's `froxelMaxDistance` so the
    // composite samples the integrated volume at the same depth slicing the
    // integrate pass wrote. The ground-fog-only path shortens the march to
    // keep near terrain see-through (see the `froxelMaxDistance` comment in
    // `update()`); mirror that here.
    r.compositeUniformData[18] = vf?.maxDistance ?? 50000;
    r.compositeUniformData[19] = 0;
    r.compositeUniformData[20] = context.drawingBufferWidth ?? 1;
    r.compositeUniformData[21] = context.drawingBufferHeight ?? 1;
    r.compositeUniformData[22] = 0;
    r.compositeUniformData[23] = 0;

    device.queue.writeBuffer(
      r.compositeUniformBuffer,
      0,
      r.compositeUniformData.buffer,
      r.compositeUniformData.byteOffset,
      r.compositeUniformData.byteLength,
    );

    // Batch 435 (FOG-TEMPORAL) — the composite samples the 3D fog volume at
    // binding 4. When temporal resolved this frame, that source is the
    // freshly-written history (the accumulated, reprojected, clamped result);
    // otherwise it's the raw integrated volume (parity-default path). The
    // resolve writes history index `temporalRead` (it flipped at the end of
    // `update()`, so `temporalRead` now points at the JUST-WRITTEN buffer).
    let fogSourceView: GPUTextureView = r.integratedSampleView;
    if (this._temporalResolvedThisFrame) {
      const writtenIdx = r.temporalRead & 1;
      const hv = r.temporalHistorySampleView[writtenIdx];
      if (hv) {
        fogSourceView = hv;
      }
    }

    // (Re)build the composite bind group when the input views change. The fog
    // source view is part of the cache key so the bind group rebuilds when the
    // temporal ping-pong flips (or temporal toggles on/off). The output format
    // check is informational only — the composite pipeline was created with
    // bgra8unorm; if the actual output format differs the renderpass would
    // fail (rebuilt in `composite()` above).
    if (
      r.compositeBindGroup === null ||
      r.compositeBoundColorView !== colorView ||
      r.compositeBoundDepthView !== depthView ||
      r.compositeBoundOutputFormat !== outputFormat ||
      r.compositeBoundFogSourceView !== fogSourceView
    ) {
      r.compositeBindGroup = device.createBindGroup({
        label: "VolumetricFog_CompositeBindGroup",
        layout: r.compositeBindGroupLayout,
        entries: [
          { binding: 0, resource: { buffer: r.compositeUniformBuffer } },
          { binding: 1, resource: r.compositeSampler },
          { binding: 2, resource: colorView },
          { binding: 3, resource: depthView },
          { binding: 4, resource: fogSourceView },
        ],
      });
      r.compositeBoundColorView = colorView;
      r.compositeBoundDepthView = depthView;
      r.compositeBoundOutputFormat = outputFormat;
      r.compositeBoundFogSourceView = fogSourceView;
    }

    // Slice 5c-B Batch 130 — record into the main frame encoder so the
    // composite ordering survives. Same fix pattern as Batch 127 for
    // NPR / SSR / ProceduralClouds. Falls back to ephemeral encoder
    // + immediate submit when no main encoder exists (test harnesses
    // that bypass `beginFrame`).
    const mainEncoder = (
      context as unknown as { _currentCommandEncoder?: GPUCommandEncoder }
    )._currentCommandEncoder;
    const useMain = !!mainEncoder;
    const encoder =
      mainEncoder ??
      device.createCommandEncoder({
        label: "VolumetricFog_CompositeEncoder (orphan)",
      });
    const pass = encoder.beginRenderPass({
      label: "VolumetricFog_CompositePass",
      colorAttachments: [
        {
          view: outputView,
          loadOp: "load",
          storeOp: "store",
        },
      ],
    });
    pass.setPipeline(r.compositePipeline);
    pass.setBindGroup(0, r.compositeBindGroup);
    pass.draw(3);
    pass.end();
    if (!useMain) {
      device.queue.submit([encoder.finish()]);
    }
  }

  destroy(): void {
    if (this._isDestroyed) return;
    // Phase 6 audit fix — unregister the snapshot freezable so the
    // service's Map doesn't hold a closure reference to a destroyed
    // renderer. Idempotent on the service side.
    if (this._snapshotRegistered && this._snapshotService) {
      try {
        this._snapshotService.unregisterFreezable("webgpu-volumetric-fog");
      } catch (e) {
        //>>includeStart('debug', pragmas.debug);
        console.warn("[WebGPU:VolumetricFog] unregisterFreezable failed:", e);
        //>>includeEnd('debug');
      }
      this._snapshotRegistered = false;
      this._snapshotService = null;
    }
    this._destroyResources();
    this._isDestroyed = true;
  }
}

// ─── Feature renderer factory + entry points ───────────────────────

const _instances = new WeakMap<
  CesiumGraphicsContext,
  WebGPUVolumetricFogRenderer
>();

function getOrCreate(
  context: CesiumGraphicsContext,
): WebGPUVolumetricFogRenderer {
  let inst = _instances.get(context);
  if (!inst) {
    inst = new WebGPUVolumetricFogRenderer(context.device);
    _instances.set(context, inst);
  }
  return inst;
}

/**
 * Feature renderer entry point: dispatch the three compute passes.
 * Called from `WebGPUSceneRenderer._executeEnvironmentalEffects()` once
 * per frame when `atmosphericConditions.volumetricFog.enabled` is true.
 */
export function updateWebGPUVolumetricFog(
  context: CesiumGraphicsContext,
  frameState: CesiumFrameState,
  scene: CesiumScene,
): void {
  if (!context || !context.device) return;
  const inst = getOrCreate(context);
  inst.update(context, frameState, scene);
}

/**
 * Feature renderer entry point: composite the integrated volume into
 * the scene color. Called from `WebGPUSceneRenderer._executeEnvironmentalEffects()`
 * after `updateWebGPUVolumetricFog()` and the other environmental
 * effects (procedural clouds, SSR, weather particles), before
 * post-processing.
 */
export function compositeWebGPUVolumetricFog(
  context: CesiumGraphicsContext,
  frameState: CesiumFrameState,
  colorView: GPUTextureView,
  depthView: GPUTextureView,
  outputView: GPUTextureView,
  outputFormat: GPUTextureFormat,
): void {
  if (!context || !context.device) return;
  const inst = _instances.get(context);
  if (!inst) return;
  inst.composite(
    context,
    frameState,
    colorView,
    depthView,
    outputView,
    outputFormat,
  );
}

/**
 * Feature renderer destroy entry point. Releases all GPU resources for
 * the given context's volumetric fog instance.
 */
export function destroyWebGPUVolumetricFog(
  context: CesiumGraphicsContext,
): void {
  const inst = _instances.get(context);
  if (inst) {
    inst.destroy();
    _instances.delete(context);
  }
}

/**
 * Phase 6 debug surface entry point — return the per-context volumetric
 * fog statistics, or `null` if the renderer has not been touched yet
 * for this context. Called by `WebGPUContext.getRendererStatistics()`.
 */
export function getWebGPUVolumetricFogStatistics(
  context: CesiumGraphicsContext,
): ReturnType<WebGPUVolumetricFogRenderer["getStatistics"]> | null {
  const inst = _instances.get(context);
  return inst ? inst.getStatistics() : null;
}

export { WebGPUVolumetricFogRenderer };
