/**
 * Shader loader for WebGPU collection rendering (PointPrimitive, Billboard, Polyline).
 * All WGSL shader source code is imported from pre-built JS modules under:
 *   Source/Shaders/WebGPU/Collections/
 *
 * Each .wgsl file has a companion .js file (auto-generated by the build) that
 * exports the shader source as a string. This avoids runtime fetch() calls.
 *
 * @private
 * @module WebGPUCollectionShaders
 */
import defined from "../../Core/defined.js";

// =========================================================================
// Static shader imports — bundled by esbuild, no runtime fetch needed
// =========================================================================
import PointPrimitiveColor from "../../Shaders/WebGPU/Collections/PointPrimitiveColor.js";
import PointPrimitivePick from "../../Shaders/WebGPU/Collections/PointPrimitivePick.js";
import BillboardCollection from "../../Shaders/WebGPU/Collections/BillboardCollection.js";
import BillboardCollectionPick from "../../Shaders/WebGPU/Collections/BillboardCollectionPick.js";
import PolylineCollection from "../../Shaders/WebGPU/Collections/PolylineCollection.js";
import PolylineCollectionPick from "../../Shaders/WebGPU/Collections/PolylineCollectionPick.js";
import PolylineArrow from "../../Shaders/WebGPU/Collections/PolylineArrow.js";
import PolylineDash from "../../Shaders/WebGPU/Collections/PolylineDash.js";
import PolylineGlow from "../../Shaders/WebGPU/Collections/PolylineGlow.js";
import PolylineOutline from "../../Shaders/WebGPU/Collections/PolylineOutline.js";
import BillboardCollectionSDF from "../../Shaders/WebGPU/Collections/BillboardCollectionSDF.js";

// =========================================================================
// Shader Cache — populated synchronously from static imports
// =========================================================================

const _shaderCache = {
  // Point primitive shaders
  pointColor: PointPrimitiveColor,
  pointPick: PointPrimitivePick,
  // Billboard shaders
  billboardColor: BillboardCollection,
  billboardPick: BillboardCollectionPick,
  billboardSDF: BillboardCollectionSDF,
  // Polyline shaders
  polylineColor: PolylineCollection,
  polylinePick: PolylineCollectionPick,
  // Polyline material shaders
  polylineArrow: PolylineArrow,
  polylineDash: PolylineDash,
  polylineGlow: PolylineGlow,
  polylineOutline: PolylineOutline,
};

// Shaders are always available — no async loading needed
const _shadersLoaded = true;

// =========================================================================
// Shader Loading (kept for API compatibility, now a no-op)
// =========================================================================

/**
 * Initializes the collection shader cache.
 * With static imports, this is a no-op — shaders are available immediately.
 * Kept for API compatibility with callers that expect an async init step.
 *
 * @returns {Promise<void>} Resolves immediately.
 * @private
 */
async function initCollectionShaders() {
  // No-op: shaders are statically imported and always available
  return;
}

/**
 * Returns the cached WGSL source for a collection shader key.
 * @param {string} key - Shader key (e.g., 'pointColor', 'pointPick')
 * @returns {string} WGSL shader source code
 * @private
 */
function getCollectionShaderSource(key) {
  const source = _shaderCache[key];
  if (!defined(source)) {
    throw new Error(
      `[WebGPUCollectionShaders] Unknown shader key: "${key}". Available: ${Object.keys(_shaderCache).join(", ")}`,
    );
  }
  return source;
}

/**
 * Returns true if the collection shader cache has been populated.
 * @returns {boolean}
 * @private
 */
function areCollectionShadersLoaded() {
  return _shadersLoaded;
}

// =========================================================================
// Exports
// =========================================================================

export {
  initCollectionShaders,
  getCollectionShaderSource,
  areCollectionShadersLoaded,
};

export default {
  initCollectionShaders,
  getCollectionShaderSource,
  areCollectionShadersLoaded,
};
