/**
 * @module WebGPUVector3DTilePolylinesRenderer
 *
 * (Per-feature pick added in Batch 115.)
 *
 * WebGPU equivalent of `Vector3DTilePolylines` (3D Tiles polylines NOT
 * clamped to terrain). Pairs with `WebGPUVector3DTileClampedPolylinesRenderer`
 * for the terrain-clamped variant.
 *
 * The CPU side (worker-decoded `_currentPositions`, `_previousPositions`,
 * `_nextPositions`, `_expandAndWidth`, `_vertexBatchIds`, `_indices`) is
 * generated by the existing `createVectorTilePolylines` task processor.
 * On the WebGPU path, `Vector3DTilePolylines.update()` keeps those arrays
 * alive (the WebGL `finishVertexArray` is skipped) so this renderer can
 * upload them straight into GPU buffers.
 *
 * **Shipped (Batch 113):**
 *   - WGSL VS port of `Vector3DTilePolylinesVS.glsl` + the screen-space
 *     miter expansion from `PolylineCommon.glsl::getPolylineWindowCoordinatesEC`.
 *   - Per-vertex `previousPosition`, `currentPosition`, `nextPosition`
 *     (vec3, RTC-relative to `_center`), `expandAndWidth` (vec2),
 *     `batchId` (f32) — interleaved into a single 60-byte / vertex stream
 *     so the GroundPrimitive vertex-cache cost amortizes.
 *   - Per-batch color via storage buffer indexed by `batchId`.
 *   - Single DrawCommand emission (the index buffer concatenates all
 *     polylines into one draw).
 *   - `Pass.TRANSLUCENT` matching the WebGL `_command.pass` choice — these
 *     polylines write color but not depth.
 *
 * **Deferred:**
 *   - Near-plane clipping (`clipLineSegmentToNearPlane`). Polylines that
 *     cross the near plane will render with garbage segments. Fix: port
 *     the WebGL clip routine — ~40 LOC of WGSL.
 *   - `POLYLINE_DASH` material variant.
 *
 * **Per-feature pick (Batch 115):**
 *   - A second storage buffer `pickColors[batchId]` is bound at @group(0)
 *     @binding(2) and uploaded from `batchTable.getPickColor(i)`.
 *   - A second pipeline (`pickPipeline`) shares the same VS but uses a
 *     `pickFS` entry point that returns `pickColors[batchId]`.
 *   - `createCommands` returns `{ colorCommands, pickCommands }`. The
 *     Scene-side `Vector3DTilePolylines.update()` pushes `pickCommands`
 *     when `frameState.passes.pick === true`.
 *
 * @private
 */
import defined from "../../Core/defined.js";
import Cartesian3 from "../../Core/Cartesian3.js";
import Matrix4 from "../../Core/Matrix4.js";
import WebGPUBuffer from "./WebGPUBuffer.js";
import WebGPUDrawCommand from "./WebGPUDrawCommand.js";
import {
  makeBindGroupLayout,
  uniformBuffer,
  storageBuffer,
  Stage,
} from "./WebGPUBindGroupLayoutHelpers.js";
import { ShaderSourceId } from "./WebGPUShaderDefines.js";
import { WebGPUShaderModuleCache } from "./WebGPUShaderModuleCache.js";

// C-R7-SHADER-MODULE-DEDUP (Batch 163) — per-device module cache.
const _polylineShaderCaches = new WeakMap();

function getPolylineShaderCache(device) {
  let cache = _polylineShaderCaches.get(device);
  if (!cache) {
    cache = new WebGPUShaderModuleCache(device);
    _polylineShaderCaches.set(device, cache);
  }
  return cache;
}

const UNIFORM_BUFFER_SIZE = 256;
const BYTES_PER_BATCH_COLOR = 16;
const INITIAL_BATCH_BUFFER_FEATURES = 64;

const scratchModifiedView = new Matrix4();
const scratchRtcCenter = new Cartesian3();

function buildPolylinePipelineResources(device, format, depthFormat) {
  const code = `
struct U {
  modifiedView: mat4x4<f32>,
  projection: mat4x4<f32>,
  viewport: vec4<f32>,
  pixelRatio: f32,
  _pad0: f32,
  _pad1: f32,
  _pad2: f32,
};
@group(0) @binding(0) var<uniform> u: U;
@group(0) @binding(1) var<storage, read> batchColors: array<vec4<f32>>;
@group(0) @binding(2) var<storage, read> pickColors: array<vec4<f32>>;

struct VOut {
  @builtin(position) pos: vec4<f32>,
  @location(0) col: vec4<f32>,
  @location(1) pickCol: vec4<f32>,
};

// Miter-expanded screen-space offset, ported from
// PolylineCommon.glsl::getPolylineWindowCoordinatesEC. Near-plane clip is
// skipped for the first cut — see file header.
fn getOffset(
  pEC: vec4<f32>,
  prevEC: vec4<f32>,
  nextEC: vec4<f32>,
  expandDir: f32,
  width: f32,
  usePrev: bool,
  halfVP: vec2<f32>,
) -> vec2<f32> {
  let pClip = u.projection * pEC;
  let prevClip = u.projection * prevEC;
  let nextClip = u.projection * nextEC;

  let invPW = 1.0 / max(pClip.w, 1e-6);
  let invPrevW = 1.0 / max(prevClip.w, 1e-6);
  let invNextW = 1.0 / max(nextClip.w, 1e-6);

  let pPx = pClip.xy * invPW * halfVP;
  let prevPx = prevClip.xy * invPrevW * halfVP;
  let nextPx = nextClip.xy * invNextW * halfVP;

  let dirToPrev = normalize(prevPx - pPx);
  let dirToNext = normalize(nextPx - pPx);

  var thisSegmentForward: vec2<f32>;
  var otherSegmentForward: vec2<f32>;
  if (usePrev) {
    thisSegmentForward = -dirToPrev;
    otherSegmentForward = dirToNext;
  } else {
    thisSegmentForward = dirToNext;
    otherSegmentForward = -dirToPrev;
  }
  let thisSegmentLeft = vec2<f32>(-thisSegmentForward.y, thisSegmentForward.x);

  var leftWC = thisSegmentLeft;
  var expandWidth = width * 0.5;

  let prevDelta = prevEC.xyz - pEC.xyz;
  let nextDelta = nextEC.xyz - pEC.xyz;
  let prevColinear = dot(prevDelta, prevDelta) < 1e-2;
  let nextColinear = dot(nextDelta, nextDelta) < 1e-2;
  if (!prevColinear && !nextColinear) {
    let otherSegmentLeft = vec2<f32>(-otherSegmentForward.y, otherSegmentForward.x);
    let leftSum = thisSegmentLeft + otherSegmentLeft;
    let leftSumLength = length(leftSum);
    if (leftSumLength >= 1e-6) {
      leftWC = leftSum / leftSumLength;
    }
    let uVec = -thisSegmentForward;
    let sinAngle = abs(uVec.x * leftWC.y - uVec.y * leftWC.x);
    if (sinAngle > 1e-4) {
      expandWidth = clamp(expandWidth / sinAngle, 0.0, width * 2.0);
    }
  }

  return leftWC * expandDir * expandWidth * u.pixelRatio;
}

@vertex
fn vsMain(
  @location(0) prev: vec3<f32>,
  @location(1) curr: vec3<f32>,
  @location(2) next: vec3<f32>,
  @location(3) expandAndWidth: vec2<f32>,
  @location(4) batchId: f32,
) -> VOut {
  let expandDir = expandAndWidth.x;
  let width = abs(expandAndWidth.y) + 0.5;
  let usePrev = expandAndWidth.y < 0.0;

  let pEC = u.modifiedView * vec4<f32>(curr, 1.0);
  let prevEC = u.modifiedView * vec4<f32>(prev, 1.0);
  let nextEC = u.modifiedView * vec4<f32>(next, 1.0);

  let halfVP = u.viewport.zw * 0.5;
  let offsetPx = getOffset(pEC, prevEC, nextEC, expandDir, width, usePrev, halfVP);

  let pClip = u.projection * pEC;
  let offsetNDC = offsetPx / halfVP;
  let outClip = vec4<f32>(
    pClip.xy + offsetNDC * pClip.w,
    pClip.z,
    pClip.w,
  );

  var output: VOut;
  output.pos = outClip;
  let bi = u32(batchId);
  output.col = batchColors[bi];
  output.pickCol = pickColors[bi];
  return output;
}

@fragment
fn fsMain(i: VOut) -> @location(0) vec4<f32> {
  // AUDIT_2026_05_02 B.1 — feature.show is folded into batchColors[bi].a
  // CPU-side. Discard hidden features here.
  if (i.col.a < 1.0e-3) {
    discard;
  }
  return i.col;
}

@fragment
fn pickFS(i: VOut) -> @location(0) vec4<f32> {
  // AUDIT_2026_05_02 B.1 — pick must respect feature.show too.
  if (i.col.a < 1.0e-3) {
    discard;
  }
  return i.pickCol;
}
`;

  const mod = getPolylineShaderCache(device).getOrCreate(
    ShaderSourceId.VECTOR_3DTILE_POLYLINES,
    code,
    0,
    "Vector3DTilePolylines",
  );

  const sharedBgl = makeBindGroupLayout(device, "Vector3DTilePolylines BGL", [
    uniformBuffer(0, Stage.VERTEX_FRAGMENT),
    storageBuffer(1, Stage.VERTEX, { readOnly: true }),
    storageBuffer(2, Stage.VERTEX, { readOnly: true }),
  ]);

  const layout = device.createPipelineLayout({
    label: "Vector3DTilePolylines PipelineLayout",
    bindGroupLayouts: [sharedBgl],
  });

  // Interleaved vertex layout — 60 bytes per vertex:
  //   loc 0: prev (vec3)            offset  0
  //   loc 1: curr (vec3)            offset 12
  //   loc 2: next (vec3)            offset 24
  //   loc 3: expandAndWidth (vec2)  offset 36
  //   loc 4: batchId (f32)          offset 44
  // (4-byte padding to round to 48-byte stride for alignment.)
  const vertexBuffers = [
    {
      arrayStride: 48,
      attributes: [
        { shaderLocation: 0, offset: 0, format: "float32x3" },
        { shaderLocation: 1, offset: 12, format: "float32x3" },
        { shaderLocation: 2, offset: 24, format: "float32x3" },
        { shaderLocation: 3, offset: 36, format: "float32x2" },
        { shaderLocation: 4, offset: 44, format: "float32" },
      ],
    },
  ];

  const colorDescriptor = {
    name: `Vector3DTilePolylines color [${format}/${depthFormat}]`,
    layout,
    vertex: { module: mod, entryPoint: "vsMain", buffers: vertexBuffers },
    fragment: {
      module: mod,
      entryPoint: "fsMain",
      targets: [
        {
          format,
          blend: {
            color: {
              srcFactor: "src-alpha",
              dstFactor: "one-minus-src-alpha",
              operation: "add",
            },
            alpha: {
              srcFactor: "one",
              dstFactor: "one-minus-src-alpha",
              operation: "add",
            },
          },
        },
      ],
    },
    primitive: { topology: "triangle-list", cullMode: "none" },
    depthStencil: {
      format: depthFormat,
      depthWriteEnabled: false,
      depthCompare: "less-equal",
      depthBias: -5,
      depthBiasSlopeScale: -5,
    },
  };

  // Pick pipeline: same VS / same depth / same blend / different FS
  // entry point. The pick FBO consumer expects RGBA8 unorm output in
  // [0, 1]; the FR's source format already is RGBA8 in pick passes.
  const pickDescriptor = {
    name: `Vector3DTilePolylines pick [${format}/${depthFormat}]`,
    layout,
    vertex: { module: mod, entryPoint: "vsMain", buffers: vertexBuffers },
    fragment: {
      module: mod,
      entryPoint: "pickFS",
      targets: [{ format }],
    },
    primitive: { topology: "triangle-list", cullMode: "none" },
    depthStencil: {
      format: depthFormat,
      depthWriteEnabled: false,
      depthCompare: "less-equal",
      depthBias: -5,
      depthBiasSlopeScale: -5,
    },
  };

  return { colorDescriptor, pickDescriptor, sharedBgl };
}

function descriptorToGPU(d) {
  return {
    label: d.name,
    layout: d.layout ?? "auto",
    vertex: {
      module: d.vertex.module,
      entryPoint: d.vertex.entryPoint,
      buffers: d.vertex.buffers,
    },
    fragment: d.fragment
      ? {
          module: d.fragment.module,
          entryPoint: d.fragment.entryPoint,
          targets: d.fragment.targets,
        }
      : undefined,
    primitive: d.primitive,
    depthStencil: d.depthStencil,
    multisample: d.multisample,
  };
}

function tryResolvePipelines(device, pipelineCache, resources, cache) {
  if (cache.colorPipeline && cache.pickPipeline) {
    return true;
  }
  if (pipelineCache) {
    if (!cache.colorPipeline) {
      const sync = pipelineCache.getPipelineSync(resources.colorDescriptor);
      if (sync) {
        cache.colorPipeline = sync;
      } else if (!cache.colorRequestPending) {
        cache.colorRequestPending = true;
        pipelineCache
          .getPipeline(resources.colorDescriptor)
          .then((p) => {
            cache.colorPipeline = p;
            cache.colorRequestPending = false;
          })
          .catch(() => {
            cache.colorRequestPending = false;
          });
      }
    }
    if (!cache.pickPipeline) {
      const pickSync = pipelineCache.getPipelineSync(resources.pickDescriptor);
      if (pickSync) {
        cache.pickPipeline = pickSync;
      } else if (!cache.pickRequestPending) {
        cache.pickRequestPending = true;
        pipelineCache
          .getPipeline(resources.pickDescriptor)
          .then((p) => {
            cache.pickPipeline = p;
            cache.pickRequestPending = false;
          })
          .catch(() => {
            cache.pickRequestPending = false;
          });
      }
    }
    return !!cache.colorPipeline;
  }
  if (!cache.colorPipeline) {
    cache.colorPipeline = device.createRenderPipeline(
      descriptorToGPU(resources.colorDescriptor),
    );
  }
  if (!cache.pickPipeline) {
    cache.pickPipeline = device.createRenderPipeline(
      descriptorToGPU(resources.pickDescriptor),
    );
  }
  return true;
}

function packUniforms(data, frameState, primitive) {
  const uniformState = frameState.context.uniformState;
  // modifiedView = view with translation set to view*center, matching
  // WebGL `u_modifiedModelView`. This is the RTC-precision-aware view
  // matrix used by the WebGL VS, ported verbatim.
  Matrix4.clone(uniformState.view, scratchModifiedView);
  Matrix4.multiplyByPoint(
    scratchModifiedView,
    primitive._center ?? Cartesian3.ZERO,
    scratchRtcCenter,
  );
  Matrix4.setTranslation(
    scratchModifiedView,
    scratchRtcCenter,
    scratchModifiedView,
  );
  Matrix4.pack(scratchModifiedView, data, 0);
  Matrix4.pack(uniformState.projection, data, 16);

  // Viewport — source from context.drawingBufferWidth/Height directly.
  // See WebGPUGroundPolylineRenderer.js packUniforms for the full
  // explanation; same bug-pattern (uniformState.viewportCartesian4 is
  // zero-initialized at FR-update time and `??` doesn't fall through on 0).
  // Vector3DTilePolylines uses viewport for pixel-space line offset
  // (offsetNDC = offsetPx / halfVP) — halfVP=0 means offsetNDC=Inf and
  // every vertex extrudes to NaN clip-space.
  const ctx = frameState.context;
  data[32] = 0.0;
  data[33] = 0.0;
  data[34] = ctx?.drawingBufferWidth || 1;
  data[35] = ctx?.drawingBufferHeight || 1;

  data[36] = uniformState.pixelRatio ?? 1.0;
}

function ensureVertexBuffer(cache, primitive, device) {
  if (defined(cache.vertexGPUBuffer)) {
    return;
  }

  const cur = primitive._currentPositions;
  const prev = primitive._previousPositions;
  const next = primitive._nextPositions;
  const expandAndWidth = primitive._expandAndWidth;
  const vertexBatchIds = primitive._vertexBatchIds;
  if (
    !defined(cur) ||
    !defined(prev) ||
    !defined(next) ||
    !defined(expandAndWidth) ||
    !defined(vertexBatchIds)
  ) {
    return;
  }

  const numVerts = cur.length / 3;
  if (numVerts === 0) {
    return;
  }

  // 48-byte stride: prev (12) + curr (12) + next (12) + expandAndWidth (8)
  // + batchId (4) + 0-pad. The 4-byte tail pad keeps GPU sample alignment
  // identical to the natural Float32Array stride and avoids rebuilding the
  // pipeline if a backend ever wants to add a 5th attribute slot.
  const interleaved = new Float32Array(numVerts * 12);
  for (let v = 0; v < numVerts; v++) {
    const dst = v * 12;
    const src3 = v * 3;
    const src2 = v * 2;
    interleaved[dst] = prev[src3];
    interleaved[dst + 1] = prev[src3 + 1];
    interleaved[dst + 2] = prev[src3 + 2];
    interleaved[dst + 3] = cur[src3];
    interleaved[dst + 4] = cur[src3 + 1];
    interleaved[dst + 5] = cur[src3 + 2];
    interleaved[dst + 6] = next[src3];
    interleaved[dst + 7] = next[src3 + 1];
    interleaved[dst + 8] = next[src3 + 2];
    interleaved[dst + 9] = expandAndWidth[src2];
    interleaved[dst + 10] = expandAndWidth[src2 + 1];
    interleaved[dst + 11] = vertexBatchIds[v];
    // dst + 12 padded by Float32Array zero init.
  }
  cache.vertexGPUBuffer = WebGPUBuffer.createVertexBuffer(
    device,
    interleaved,
    "Vector3DTilePolylines VB",
  );
  cache.vertexCount = numVerts;
}

function ensureIndexBuffer(cache, primitive, device) {
  if (defined(cache.indexGPUBuffer)) {
    return;
  }
  const indices = primitive._indices;
  if (!defined(indices)) {
    return;
  }

  const needsU32 = indices.BYTES_PER_ELEMENT === 4;
  const typed = needsU32 ? new Uint32Array(indices) : new Uint16Array(indices);
  cache.indexFormat = needsU32 ? "uint32" : "uint16";
  cache.indexGPUBuffer = device.createBuffer({
    label: "Vector3DTilePolylines IB",
    size: typed.byteLength,
    usage: GPUBufferUsage.INDEX | GPUBufferUsage.COPY_DST,
  });
  device.queue.writeBuffer(cache.indexGPUBuffer, 0, typed);
  cache.indexCount = indices.length;
}

function ensureBatchColorStorage(cache, primitive, device) {
  const featuresLength =
    primitive._batchTable?.featuresLength ??
    primitive._batchIds?.length ??
    INITIAL_BATCH_BUFFER_FEATURES;
  const requiredBytes = Math.max(
    featuresLength * BYTES_PER_BATCH_COLOR,
    INITIAL_BATCH_BUFFER_FEATURES * BYTES_PER_BATCH_COLOR,
  );

  if (
    defined(cache.batchColorBuffer) &&
    cache.batchColorBufferCapacity >= requiredBytes
  ) {
    return;
  }
  if (defined(cache.batchColorBuffer)) {
    cache.batchColorBuffer.destroy();
  }
  cache.batchColorBuffer = device.createBuffer({
    label: "Vector3DTilePolylines batch colors",
    size: requiredBytes,
    usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
  });
  cache.batchColorBufferCapacity = requiredBytes;
  cache.batchColorScratch = new Float32Array(requiredBytes / 4);
  cache._sharedBindGroupDirty = true;
}

function uploadBatchColors(cache, primitive, device) {
  const scratch = cache.batchColorScratch;
  if (!defined(scratch)) {
    return;
  }

  // Vector3DTilePolylines doesn't carry `_batchedIndices` (each polyline is
  // its own draw conceptually) — colors live on the batch table. Default
  // every feature to the primitive's `_highlightColor`; the batch table
  // overrides per feature when `applyStyle` evaluates.
  const highlight = primitive._highlightColor;
  const r = highlight?.red ?? 1.0;
  const g = highlight?.green ?? 1.0;
  const b = highlight?.blue ?? 1.0;
  const a = highlight?.alpha ?? 1.0;
  for (let i = 0; i < scratch.length; i += 4) {
    scratch[i] = r;
    scratch[i + 1] = g;
    scratch[i + 2] = b;
    scratch[i + 3] = a;
  }

  // AUDIT_2026_05_02 B.1 — fold per-feature `Cesium3DTileFeature.show`
  // into batch alpha so the FS discard branch hides set-show-false
  // features without needing a second storage buffer.
  const batchTable = primitive._batchTable;
  if (defined(batchTable) && typeof batchTable.getShow === "function") {
    const featuresLength = batchTable.featuresLength ?? 0;
    for (let id = 0; id < featuresLength; id++) {
      const slot = id * 4 + 3;
      if (slot >= scratch.length) {
        break;
      }
      if (!batchTable.getShow(id)) {
        scratch[slot] = 0.0;
      }
    }
  }

  device.queue.writeBuffer(
    cache.batchColorBuffer,
    0,
    scratch.buffer,
    scratch.byteOffset,
    cache.batchColorBufferCapacity,
  );
}

function ensurePickColorStorage(cache, primitive, device) {
  // Mirrors `ensureBatchColorStorage`. The pick-color storage buffer is
  // bound at @group(0) @binding(2) and is required by the BGL even when
  // the pick pipeline isn't running this frame — WebGPU forbids
  // partial bind groups. Always allocated, sized to match the batch
  // buffer.
  const featuresLength =
    primitive._batchTable?.featuresLength ??
    primitive._batchIds?.length ??
    INITIAL_BATCH_BUFFER_FEATURES;
  const requiredBytes = Math.max(
    featuresLength * BYTES_PER_BATCH_COLOR,
    INITIAL_BATCH_BUFFER_FEATURES * BYTES_PER_BATCH_COLOR,
  );

  if (
    defined(cache.pickColorBuffer) &&
    cache.pickColorBufferCapacity >= requiredBytes
  ) {
    return;
  }
  if (defined(cache.pickColorBuffer)) {
    cache.pickColorBuffer.destroy();
  }
  cache.pickColorBuffer = device.createBuffer({
    label: "Vector3DTilePolylines pick colors",
    size: requiredBytes,
    usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
  });
  cache.pickColorBufferCapacity = requiredBytes;
  cache.pickColorScratch = new Float32Array(requiredBytes / 4);
  cache._sharedBindGroupDirty = true;
  cache._pickColorsUploaded = false;
}

function uploadPickColors(cache, primitive, device) {
  const scratch = cache.pickColorScratch;
  if (!defined(scratch)) {
    return;
  }
  scratch.fill(0);

  const batchTable = primitive._batchTable;
  if (defined(batchTable) && typeof batchTable.getPickColor === "function") {
    const length = batchTable.featuresLength ?? 0;
    for (let i = 0; i < length; i++) {
      const pickId = batchTable.getPickColor(i);
      const color = pickId?.color;
      if (!defined(color)) {
        continue;
      }
      const slot = i * 4;
      if (slot + 3 < scratch.length) {
        scratch[slot] = color.red;
        scratch[slot + 1] = color.green;
        scratch[slot + 2] = color.blue;
        scratch[slot + 3] = color.alpha;
      }
    }
  }

  device.queue.writeBuffer(
    cache.pickColorBuffer,
    0,
    scratch.buffer,
    scratch.byteOffset,
    cache.pickColorBufferCapacity,
  );
}

function createWebGPUVector3DTilePolylineCommands(primitive, frameState) {
  const context = frameState.context;
  const device = context.device;

  if (!defined(primitive._webgpuCache)) {
    primitive._webgpuCache = {};
  }
  const cache = primitive._webgpuCache;

  const sceneGen = context._scenePipelineFormatGeneration ?? 0;
  if (
    defined(cache._pipelineResources) &&
    cache._pipelineFormatGeneration !== sceneGen
  ) {
    cache._pipelineResources = undefined;
    cache.colorPipeline = undefined;
    cache.pickPipeline = undefined;
    cache.sharedBindGroup = undefined;
  }
  if (!defined(cache._pipelineResources)) {
    const format = context.scenePipelineFormat || "bgra8unorm";
    const depthFmt = context.depthFormat || "depth24plus-stencil8";
    cache._pipelineResources = buildPolylinePipelineResources(
      device,
      format,
      depthFmt,
    );
    cache._pipelineFormatGeneration = sceneGen;
    cache.colorRequestPending = false;
    cache.pickRequestPending = false;
  }
  if (
    !tryResolvePipelines(
      device,
      context.webgpuPipelineCache ?? null,
      cache._pipelineResources,
      cache,
    )
  ) {
    return { colorCommands: [], pickCommands: [] };
  }

  if (!defined(cache.uniformBuffer)) {
    cache.uniformBuffer = WebGPUBuffer.createUniformBuffer(
      device,
      UNIFORM_BUFFER_SIZE,
      "Vector3DTilePolylines uniforms",
    );
    cache.uniformData = new Float32Array(UNIFORM_BUFFER_SIZE / 4);
  }
  ensureBatchColorStorage(cache, primitive, device);
  ensurePickColorStorage(cache, primitive, device);
  if (cache._sharedBindGroupDirty || !defined(cache.sharedBindGroup)) {
    cache.sharedBindGroup = device.createBindGroup({
      label: "Vector3DTilePolylines BG",
      layout: cache._pipelineResources.sharedBgl,
      entries: [
        { binding: 0, resource: { buffer: cache.uniformBuffer.buffer } },
        { binding: 1, resource: { buffer: cache.batchColorBuffer } },
        { binding: 2, resource: { buffer: cache.pickColorBuffer } },
      ],
    });
    cache._sharedBindGroupDirty = false;
  }

  ensureVertexBuffer(cache, primitive, device);
  ensureIndexBuffer(cache, primitive, device);
  if (!defined(cache.vertexGPUBuffer) || !defined(cache.indexGPUBuffer)) {
    return { colorCommands: [], pickCommands: [] };
  }

  packUniforms(cache.uniformData, frameState, primitive);
  device.queue.writeBuffer(
    cache.uniformBuffer.buffer,
    0,
    cache.uniformData.buffer,
    0,
    UNIFORM_BUFFER_SIZE,
  );

  // AUDIT_2026_05_02 B.1 — re-upload when batch table reports dirty
  // values (e.g., per-feature `show` toggle). Without this trigger, the
  // initial upload runs once on first frame and `feature.show = false`
  // never reaches the storage buffer.
  const batchValuesDirty = primitive._batchTable?._batchValuesDirty === true;
  if (!cache._batchColorsUploaded || batchValuesDirty) {
    uploadBatchColors(cache, primitive, device);
    cache._batchColorsUploaded = true;
  }
  if (!cache._pickColorsUploaded) {
    uploadPickColors(cache, primitive, device);
    cache._pickColorsUploaded = true;
  }

  // Pass.TRANSLUCENT — matches the WebGL Scene/Vector3DTilePolylines pass
  // assignment. The polyline depthBias in the pipeline pulls polylines
  // toward the camera so they lie on top of overlapping geometry.
  const colorCmd = new WebGPUDrawCommand({
    pipeline: cache.colorPipeline,
    bindGroups: [cache.sharedBindGroup],
    vertexBuffers: [cache.vertexGPUBuffer],
    indexBuffer: cache.indexGPUBuffer,
    indexFormat: cache.indexFormat,
    indexCount: cache.indexCount || 0,
    vertexCount: 0,
    pass: 9 /* Pass.TRANSLUCENT */,
    owner: primitive,
  });

  const pickCommands = [];
  if (defined(cache.pickPipeline)) {
    pickCommands.push(
      new WebGPUDrawCommand({
        pipeline: cache.pickPipeline,
        bindGroups: [cache.sharedBindGroup],
        vertexBuffers: [cache.vertexGPUBuffer],
        indexBuffer: cache.indexGPUBuffer,
        indexFormat: cache.indexFormat,
        indexCount: cache.indexCount || 0,
        vertexCount: 0,
        pass: 9 /* Pass.TRANSLUCENT */,
        owner: primitive,
        pickOnly: true,
      }),
    );
  }

  return { colorCommands: [colorCmd], pickCommands };
}

function destroyWebGPUVector3DTilePolylineResources(primitive) {
  const cache = primitive._webgpuCache;
  if (!defined(cache)) {
    return;
  }
  if (defined(cache.uniformBuffer)) {
    cache.uniformBuffer.destroy();
  }
  if (defined(cache.batchColorBuffer)) {
    cache.batchColorBuffer.destroy();
  }
  if (defined(cache.pickColorBuffer)) {
    cache.pickColorBuffer.destroy();
  }
  if (defined(cache.vertexGPUBuffer)) {
    cache.vertexGPUBuffer.destroy();
  }
  if (defined(cache.indexGPUBuffer)) {
    cache.indexGPUBuffer.destroy();
  }
  primitive._webgpuCache = undefined;
}

export {
  createWebGPUVector3DTilePolylineCommands,
  destroyWebGPUVector3DTilePolylineResources,
};
export default {
  createWebGPUVector3DTilePolylineCommands,
  destroyWebGPUVector3DTilePolylineResources,
};
