/**
 * @module WebGPUVector3DTileClampedPolylinesRenderer
 *
 * WebGPU equivalent of `Vector3DTileClampedPolylines` (3D Tiles polylines
 * clamped to terrain). Pairs with `WebGPUVector3DTilePolylinesRenderer`
 * for the un-clamped variant and with `WebGPUVector3DTilePrimitiveRenderer`
 * for the polygon classifier.
 *
 * Architecture mirrors `WebGPUGroundPolylineRenderer`'s depth-sample
 * classifier (ADR-2026-04-28). The volume's rasterization handles lateral
 * coverage; the FS samples the globe depth texture, reconstructs the eye-
 * space surface position, and tests it against three EC planes (start,
 * end, right) plus the per-fragment width threshold computed from
 * `czm_metersPerPixel`. Fragments outside the swept volume are discarded.
 *
 * The CPU side (worker-decoded `_startEllipsoidNormals`,
 * `_endEllipsoidNormals`, `_startPositionAndHeights`,
 * `_endPositionAndHeights`, `_startFaceNormalAndVertexCornerIds`,
 * `_endFaceNormalAndHalfWidths`, `_vertexBatchIds`, `_indices`) is
 * generated by the existing `createVectorTileClampedPolylines` task
 * processor. On the WebGPU path, `Vector3DTileClampedPolylines.update()`
 * keeps those arrays alive (the WebGL `finishVertexArray` is skipped) so
 * this renderer can upload them straight into GPU buffers.
 *
 * **Shipped (Batch 114):**
 *   - WGSL VS port of `Vector3DTileClampedPolylinesVS.glsl` — per-vertex
 *     shadow-volume extrusion (height + width miter), eye-space plane
 *     reconstruction, manual depth clamp.
 *   - WGSL FS port of `Vector3DTileClampedPolylinesFS.glsl` — depth-
 *     sampled classifier with 5-plane test (right ± halfMaxWidth, start/
 *     end half-spaces, sky discard).
 *   - 7-attribute interleaved vertex layout in a single 96-byte stream.
 *   - Per-batch color via storage buffer indexed by `batchId`.
 *   - Single shared depth-sample bind group reused across both ground
 *     passes (TERRAIN + 3D-TILE classification — see "Pass routing" below).
 *
 * **Deferred:**
 *   - Per-feature pick. Same trade-off as the polygon FR: the storage-
 *     buffer indirection means adding `pickColors[batchId]` is one extra
 *     `vec4[]` slot when a future batch enables it.
 *   - `DEBUG_SHOW_VOLUME` mode (visualizes the swept volume in red/blue).
 *   - Distinct depth source per pass: WebGL stencils against
 *     `czm_globeDepthTexture` for TERRAIN and against `czm_pickDepthTexture`
 *     for 3D-Tile classification. The current depth-sample resolver
 *     follows the same simplification as `WebGPUVector3DTilePrimitiveRenderer`
 *     — pick `_packedTranslucentDepthView` if present, else `_globeDepthView`.
 *
 * **Pass routing:**
 *
 *   `classificationType` is one of TERRAIN (0) / CESIUM_3D_TILE (1) /
 *   BOTH (2). The WebGPU command list dispatches a single command per
 *   pass it should appear in:
 *     - TERRAIN: `Pass.TERRAIN_CLASSIFICATION` (3)
 *     - CESIUM_3D_TILE: `Pass.CESIUM_3D_TILE_CLASSIFICATION` (6)
 *     - BOTH: emit one of each.
 *   Both commands share the same pipeline / bind groups / vertex+index
 *   buffer; only the pass enum differs.
 *
 * @private
 */
import defined from "../../Core/defined.js";
import Matrix4 from "../../Core/Matrix4.js";
import oneTimeWarning from "../../Core/oneTimeWarning.js";
import SceneMode from "../../Scene/SceneMode.js";
import csm_depthClamp from "../../Shaders/WebGPU/chunks/functions/csm_depthClamp.js";
import WebGPUBuffer from "./WebGPUBuffer.js";
import WebGPUDrawCommand from "./WebGPUDrawCommand.js";
import {
  makeBindGroupLayout,
  uniformBuffer,
  storageBuffer,
  sampler as samplerEntry,
  texture as textureEntry,
  Stage,
} from "./WebGPUBindGroupLayoutHelpers.js";
import { ShaderSourceId } from "./WebGPUShaderDefines.js";
import { WebGPUShaderModuleCache } from "./WebGPUShaderModuleCache.js";

// C-R7-SHADER-MODULE-DEDUP (Batch 163) — per-device module cache.
const _clampedPolylineShaderCaches = new WeakMap();

function getClampedPolylineShaderCache(device) {
  let cache = _clampedPolylineShaderCaches.get(device);
  if (!cache) {
    cache = new WebGPUShaderModuleCache(device);
    _clampedPolylineShaderCaches.set(device, cache);
  }
  return cache;
}

// AUDIT_2026_05_02 B.9 (Batch 153) — bumped from 320 → 384 to fit the
// trailing `prevViewProjection: mat4x4<f32>` (64 bytes) added per the
// DP-H41 invariant. Layout: 272 bytes used + 64 bytes prevVP + 48 bytes
// trailing reserved = 384.
const UNIFORM_BUFFER_SIZE = 384;
const BYTES_PER_BATCH_COLOR = 16;
const INITIAL_BATCH_BUFFER_FEATURES = 64;

const VERTEX_STRIDE_FLOATS = 24;
const VERTEX_STRIDE_BYTES = VERTEX_STRIDE_FLOATS * 4;

const PASS_TERRAIN_CLASSIFICATION = 3;
const PASS_CESIUM_3D_TILE_CLASSIFICATION = 6;
const CLASSIFICATION_TYPE_TERRAIN = 0;
const CLASSIFICATION_TYPE_3DTILE = 1;
const CLASSIFICATION_TYPE_BOTH = 2;

function buildClampedPolylinePipelineResources(device, format, depthFormat) {
  const code = `
${csm_depthClamp}
struct U {
  modifiedView: mat4x4<f32>,
  projection: mat4x4<f32>,
  invProjection: mat4x4<f32>,
  normalCol0: vec4<f32>,
  normalCol1: vec4<f32>,
  normalCol2: vec4<f32>,
  viewport: vec4<f32>,
  minMaxHeights: vec2<f32>,
  pixelRatio: f32,
  _pad: f32,
  // AUDIT_2026_05_02 B.9 (Batch 153) — DP-H41 prev viewProjection at the
  // tail. NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — now
  // consumed by vsVelocity for camera-only motion vectors under TAA.
  prevViewProjection: mat4x4<f32>,
  // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — primitive
  // center in world coordinates. Vertex startPosH.xyz / endPosH.xyz
  // are RTC-relative to this center; the velocity VS reconstructs
  // world-space positions (worldPos = centerWC + posObj) for
  // projection through prevViewProjection. See Vector3DTilePolylines
  // Batch 179 for the analogous wiring.
  centerWC: vec3<f32>,
  _padCenter: f32,
};
@group(0) @binding(0) var<uniform> u: U;
@group(0) @binding(1) var<storage, read> batchColors: array<vec4<f32>>;
@group(0) @binding(2) var<storage, read> pickColors: array<vec4<f32>>;

@group(1) @binding(0) var globeDepthTex: texture_2d<f32>;
@group(1) @binding(1) var depthSampler: sampler;

struct VOut {
  @builtin(position) pos: vec4<f32>,
  @location(0) startPlaneEC: vec4<f32>,
  @location(1) endPlaneEC: vec4<f32>,
  @location(2) rightPlaneEC: vec4<f32>,
  @location(3) volumeUpEC_halfWidth: vec4<f32>,
  @location(4) col: vec4<f32>,
  @location(5) pickCol: vec4<f32>,
};

fn applyNormal(v: vec3<f32>) -> vec3<f32> {
  let m = mat3x3<f32>(u.normalCol0.xyz, u.normalCol1.xyz, u.normalCol2.xyz);
  return m * v;
}

// czm_metersPerPixel(positionEC) approximation. Pulled from the GroundPolyline
// FR: proj[0][0] / proj[1][1] are 1/(aspect*tan(fov/2)) and 1/tan(fov/2);
// 2/W and 2/H over those give the NDC-pixel size.
fn metersPerPixel(positionEC: vec3<f32>) -> f32 {
  let pixelW = 2.0 / (u.viewport.z * u.projection[0][0]);
  let pixelH = 2.0 / (u.viewport.w * u.projection[1][1]);
  let pixelSize = max(abs(pixelW), abs(pixelH));
  return pixelSize * abs(positionEC.z);
}

@vertex
fn vsMain(
  @location(0) startEN: vec3<f32>,
  @location(6) batchId: f32,
  @location(1) endEN: vec3<f32>,
  @location(2) startPosH: vec4<f32>,
  @location(3) endPosH: vec4<f32>,
  @location(4) startFaceNVC: vec4<f32>,
  @location(5) endFaceNHW: vec4<f32>,
) -> VOut {
  // vertex corner IDs follow the WebGL VS exactly:
  //   isEnd = floor(corner * 0.251)         -> 0 for start, 1 for end face
  //   isTop = floor(corner * mix(0.51, 0.19, isEnd))
  //                                          -> 0 for bottom, 1 for top
  let cornerId = startFaceNVC.w;
  let isEnd = floor(cornerId * 0.251);
  let isTop = floor(cornerId * mix(0.51, 0.19, isEnd));

  let forward = endPosH.xyz - startPosH.xyz;
  var right = normalize(cross(forward, startEN));

  var posObj = vec4<f32>(startPosH.xyz + forward * isEnd, 1.0);

  let volumeUpEC = applyNormal(normalize(cross(right, forward)));

  // Vertical extrusion to bracket the global terrain min/max height.
  let normalForExtrude = mix(startEN, endEN, isEnd);
  var heightOffset = mix(startPosH.w, endPosH.w, isEnd);
  heightOffset = mix(u.minMaxHeights.y, u.minMaxHeights.x, isTop) - heightOffset;
  posObj = vec4<f32>(posObj.xyz + heightOffset * normalForExtrude, 1.0);

  // RTC -> EC.
  var posEC = u.modifiedView * posObj;
  let rightEC = applyNormal(right);

  // Width miter push. Mirrors VectorClampedPolylineVS:
  //   N = (vertexCorner < 4 ? -startFaceNormal : endFaceNormal) ⊗ ellipsoidNormal
  //   miterPushNormal = czm_normal * normalize(N)
  //   distance = widthEC / dot(miterPushNormal, right)
  //   sign     = sign(0.5 - mod(corner, 2.0))
  var scratchNormal = mix(-startFaceNVC.xyz, endFaceNHW.xyz, isEnd);
  scratchNormal = cross(scratchNormal, mix(startEN, endEN, isEnd));
  let miterPushNormal = applyNormal(normalize(scratchNormal));

  let widthEC = 2.0 * endFaceNHW.w * max(0.0, metersPerPixel(posEC.xyz));
  let widthOffset = widthEC / dot(miterPushNormal, rightEC);
  let cornerMod2 = cornerId - 2.0 * floor(cornerId * 0.5);
  let signMod = sign(0.5 - cornerMod2);
  posEC = vec4<f32>(posEC.xyz + miterPushNormal * (widthOffset * signMod), 1.0);

  // czm_depthClamp — WebGPU has no native depthClamp extension. Without
  // this, fragments past the far plane (very common for shadow volumes
  // that bracket terrain min/max) are clipped and the volume coverage
  // thins out near the horizon. The chunk lives at
  // packages/engine/Source/Shaders/WebGPU/chunks/functions/csm_depthClamp.wgsl.
  let clip = csm_depthClamp(u.projection * posEC);

  // Side-plane reconstruction in eye-space, per the WebGL VS.
  let startEC = u.modifiedView * vec4<f32>(startPosH.xyz, 1.0);
  let endEC = u.modifiedView * vec4<f32>(endPosH.xyz, 1.0);
  let startNormalEC = applyNormal(startFaceNVC.xyz);
  let endNormalEC = applyNormal(endFaceNHW.xyz);

  var output: VOut;
  output.pos = clip;
  output.startPlaneEC = vec4<f32>(startNormalEC, -dot(startNormalEC, startEC.xyz));
  output.endPlaneEC = vec4<f32>(endNormalEC, -dot(endNormalEC, endEC.xyz));
  output.rightPlaneEC = vec4<f32>(rightEC, -dot(rightEC, startEC.xyz));
  output.volumeUpEC_halfWidth = vec4<f32>(volumeUpEC, endFaceNHW.w);
  let bi = u32(batchId);
  output.col = batchColors[bi];
  output.pickCol = pickColors[bi];
  return output;
}

fn unpackDepth(packed: vec4<f32>) -> f32 {
  return dot(packed, vec4<f32>(1.0, 1.0 / 255.0, 1.0 / 65025.0, 1.0 / 16581375.0));
}

fn windowToEyeCoordinates(fragXY: vec2<f32>, depth: f32) -> vec3<f32> {
  // WebGPU NDC z is already in [0, 1] (no remap needed). Y flip
  // accounts for fragCoord (top-left origin) vs NDC (bottom-up).
  var ndc = (fragXY / u.viewport.zw) * 2.0 - 1.0;
  ndc.y = -ndc.y;
  let clip = vec4<f32>(ndc, depth, 1.0);
  let eye = u.invProjection * clip;
  return eye.xyz / eye.w;
}

fn planeDistance(plane: vec4<f32>, p: vec3<f32>) -> f32 {
  return dot(plane.xyz, p) + plane.w;
}

// Returns true if the fragment lies inside the swept volume (and thus
// should be drawn); returns false if it should be discarded. Centralized
// so the color FS and pick FS share identical coverage rules.
fn classifyFragment(in: VOut) -> bool {
  let screenUV = in.pos.xy / u.viewport.zw;
  let packed = textureSampleLevel(globeDepthTex, depthSampler, screenUV, 0.0);
  let surfaceDepth = unpackDepth(packed);
  if (surfaceDepth == 0.0) {
    return false;
  }

  let eyeCoord = windowToEyeCoordinates(in.pos.xy, surfaceDepth);

  let halfWidth = in.volumeUpEC_halfWidth.w;
  let volumeUpEC = in.volumeUpEC_halfWidth.xyz;
  var halfMaxWidth = halfWidth * metersPerPixel(eyeCoord);
  let viewDir = -normalize(eyeCoord);
  halfMaxWidth = halfMaxWidth + halfMaxWidth * (1.0 - dot(viewDir, volumeUpEC));

  let widthwiseDistance = planeDistance(in.rightPlaneEC, eyeCoord);
  let distFromStart = planeDistance(in.startPlaneEC, eyeCoord);
  let distFromEnd = planeDistance(in.endPlaneEC, eyeCoord);

  if (abs(widthwiseDistance) > halfMaxWidth || distFromStart < 0.0 || distFromEnd < 0.0) {
    return false;
  }
  return true;
}

@fragment
fn fsMain(in: VOut) -> @location(0) vec4<f32> {
  // AUDIT_2026_05_02 B.1 — feature.show folded into batchColors[bi].a
  // CPU-side. Discard hidden features.
  if (in.col.a < 1.0e-3) {
    discard;
  }
  if (!classifyFragment(in)) {
    discard;
  }
  return in.col;
}

@fragment
fn pickFS(in: VOut) -> @location(0) vec4<f32> {
  // AUDIT_2026_05_02 B.1 — pick must respect feature.show too.
  if (in.col.a < 1.0e-3) {
    discard;
  }
  if (!classifyFragment(in)) {
    discard;
  }
  return in.pickCol;
}

// AUDIT_2026_05_02 A.2 (Batch 141, NEW-INVERT-CLASS-STENCIL-CLASSIFIER) —
// IGNORE_SHOW variant. Same volume rasterization + plane-test as fsMain;
// deliberately does NOT respect feature.show. Color writes disabled at the
// pipeline (writeMask=0), the only side-effect is stencil=0xff via
// stencil-write state.
@fragment
fn stencilFS(in: VOut) -> @location(0) vec4<f32> {
  if (!classifyFragment(in)) {
    discard;
  }
  return vec4<f32>(0.0);
}

// NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — velocity
// entry points for clamped-polyline classifier. Replicates the volume
// extrusion exactly so velocity-pass coverage matches the color pass
// fragment-for-fragment. The previous-frame clip uses the un-extruded
// world-space position (centerWC + posObj before width/height push)
// projected through prevViewProjection — same approximation as
// Vector3DTilePolylines: thin lines and small camera deltas mean the
// extrusion offset's contribution to velocity is negligible vs the
// camera-induced delta TAA actually cares about.
struct VelocityVOut {
  @builtin(position) pos: vec4<f32>,
  @location(0) currClip: vec4<f32>,
  @location(1) prevClip: vec4<f32>,
};

@vertex
fn vsVelocity(
  @location(0) startEN: vec3<f32>,
  @location(6) batchId: f32,
  @location(1) endEN: vec3<f32>,
  @location(2) startPosH: vec4<f32>,
  @location(3) endPosH: vec4<f32>,
  @location(4) startFaceNVC: vec4<f32>,
  @location(5) endFaceNHW: vec4<f32>,
) -> VelocityVOut {
  // Replicate the color VS extrusion math byte-for-byte so the
  // velocity-pass rasterization covers the same fragments. Differs
  // only in what's emitted (currClip + prevClip instead of plane
  // varyings).
  let cornerId = startFaceNVC.w;
  let isEnd = floor(cornerId * 0.251);
  let isTop = floor(cornerId * mix(0.51, 0.19, isEnd));

  let forward = endPosH.xyz - startPosH.xyz;
  var right = normalize(cross(forward, startEN));

  var posObj = vec4<f32>(startPosH.xyz + forward * isEnd, 1.0);

  let normalForExtrude = mix(startEN, endEN, isEnd);
  var heightOffset = mix(startPosH.w, endPosH.w, isEnd);
  heightOffset = mix(u.minMaxHeights.y, u.minMaxHeights.x, isTop) - heightOffset;
  posObj = vec4<f32>(posObj.xyz + heightOffset * normalForExtrude, 1.0);

  // Capture the un-extruded world position BEFORE the screen-space
  // width-miter push for use in the prev-frame projection. The
  // width-miter offset is in eye-space pixels; it's not a world-space
  // displacement we'd want to carry into the prev-VP transform.
  let worldPosUnextruded = u.centerWC + posObj.xyz;

  var posEC = u.modifiedView * posObj;
  let rightEC = applyNormal(right);
  var scratchNormal = mix(-startFaceNVC.xyz, endFaceNHW.xyz, isEnd);
  scratchNormal = cross(scratchNormal, mix(startEN, endEN, isEnd));
  let miterPushNormal = applyNormal(normalize(scratchNormal));
  let widthEC = 2.0 * endFaceNHW.w * max(0.0, metersPerPixel(posEC.xyz));
  let widthOffset = widthEC / dot(miterPushNormal, rightEC);
  let cornerMod2 = cornerId - 2.0 * floor(cornerId * 0.5);
  let signMod = sign(0.5 - cornerMod2);
  posEC = vec4<f32>(posEC.xyz + miterPushNormal * (widthOffset * signMod), 1.0);

  let curClip = csm_depthClamp(u.projection * posEC);
  let prClip = u.prevViewProjection * vec4<f32>(worldPosUnextruded, 1.0);

  var output: VelocityVOut;
  output.pos = curClip;
  output.currClip = curClip;
  output.prevClip = prClip;
  let _bi = batchId;
  return output;
}

@fragment
fn fsVelocity(i: VelocityVOut) -> @location(0) vec2<f32> {
  let curW = i.currClip.w;
  let prevW = i.prevClip.w;
  if (curW <= 0.0 || prevW <= 0.0) {
    return vec2<f32>(0.0);
  }
  let curNdc = i.currClip.xy / curW;
  let prevNdc = i.prevClip.xy / prevW;
  return curNdc - prevNdc;
}
`;

  const mod = getClampedPolylineShaderCache(device).getOrCreate(
    ShaderSourceId.VECTOR_3DTILE_CLAMPED_POLYLINES,
    code,
    0,
    "Vector3DTileClampedPolylines",
  );

  const sharedBgl = makeBindGroupLayout(
    device,
    "Vector3DTileClampedPolylines Shared BGL",
    [
      uniformBuffer(0, Stage.VERTEX_FRAGMENT),
      storageBuffer(1, Stage.VERTEX_FRAGMENT, { readOnly: true }),
      storageBuffer(2, Stage.VERTEX_FRAGMENT, { readOnly: true }),
    ],
  );

  const depthSampleBgl = makeBindGroupLayout(
    device,
    "Vector3DTileClampedPolylines DepthSample BGL",
    [
      textureEntry(0, Stage.FRAGMENT, { sampleType: "float" }),
      samplerEntry(1, Stage.FRAGMENT, "filtering"),
    ],
  );

  const layout = device.createPipelineLayout({
    label: "Vector3DTileClampedPolylines PipelineLayout",
    bindGroupLayouts: [sharedBgl, depthSampleBgl],
  });

  // 96-byte interleaved layout. See VS argument order for shaderLocation
  // mapping. batchId sits at offset 12 to fill the 4-byte tail of the
  // first vec3 attribute and keep the next vec4 attributes vec4-aligned.
  const vertexBuffers = [
    {
      arrayStride: VERTEX_STRIDE_BYTES,
      attributes: [
        { shaderLocation: 0, offset: 0, format: "float32x3" },
        { shaderLocation: 6, offset: 12, format: "float32" },
        { shaderLocation: 1, offset: 16, format: "float32x3" },
        { shaderLocation: 2, offset: 32, format: "float32x4" },
        { shaderLocation: 3, offset: 48, format: "float32x4" },
        { shaderLocation: 4, offset: 64, format: "float32x4" },
        { shaderLocation: 5, offset: 80, format: "float32x4" },
      ],
    },
  ];

  const colorDescriptor = {
    name: `Vector3DTileClampedPolylines color [${format}/${depthFormat}]`,
    layout,
    vertex: { module: mod, entryPoint: "vsMain", buffers: vertexBuffers },
    fragment: {
      module: mod,
      entryPoint: "fsMain",
      targets: [
        {
          format,
          blend: {
            color: {
              srcFactor: "src-alpha",
              dstFactor: "one-minus-src-alpha",
              operation: "add",
            },
            alpha: {
              srcFactor: "one",
              dstFactor: "one-minus-src-alpha",
              operation: "add",
            },
          },
        },
      ],
    },
    // Cull FRONT — see Vector3DTileClampedPolylines.js::getRenderState
    // for the rationale (volumes are wound inside-out so the VS-driven
    // re-inversion makes the visible faces "outside"; back-face culling
    // would drop them).
    primitive: { topology: "triangle-list", cullMode: "front" },
    depthStencil: {
      format: depthFormat,
      depthWriteEnabled: false,
      // The volume must rasterize even where its z is past the depth
      // buffer. The classifier samples globe depth in the FS and decides
      // whether to draw, so the GPU's hardware depth test is bypassed
      // intentionally.
      depthCompare: "always",
    },
  };

  // Pick pipeline: same VS / depth-sample BGL / different FS entry.
  const pickDescriptor = {
    name: `Vector3DTileClampedPolylines pick [${format}/${depthFormat}]`,
    layout,
    vertex: { module: mod, entryPoint: "vsMain", buffers: vertexBuffers },
    fragment: {
      module: mod,
      entryPoint: "pickFS",
      targets: [{ format }],
    },
    primitive: { topology: "triangle-list", cullMode: "front" },
    depthStencil: {
      format: depthFormat,
      depthWriteEnabled: false,
      depthCompare: "always",
    },
  };

  // AUDIT_2026_05_02 A.2 (Batch 141) — IGNORE_SHOW stencil-write variant.
  const stencilDescriptor = {
    name: `Vector3DTileClampedPolylines stencil [${format}/${depthFormat}]`,
    layout,
    vertex: { module: mod, entryPoint: "vsMain", buffers: vertexBuffers },
    fragment: {
      module: mod,
      entryPoint: "stencilFS",
      targets: [{ format, writeMask: 0 }],
    },
    primitive: { topology: "triangle-list", cullMode: "front" },
    depthStencil: {
      format: depthFormat,
      depthWriteEnabled: false,
      depthCompare: "always",
      stencilFront: {
        compare: "always",
        failOp: "keep",
        depthFailOp: "keep",
        passOp: "replace",
      },
      stencilBack: {
        compare: "always",
        failOp: "keep",
        depthFailOp: "keep",
        passOp: "replace",
      },
      stencilReadMask: 0xff,
      stencilWriteMask: 0xff,
    },
  };

  // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — velocity
  // pipeline. Same VS extrusion math as the color pipeline (so coverage
  // matches), single rg16float color target, no blend, depth read-only.
  // The volume rasterizes with `cullMode: "front"` and
  // `depthCompare: "always"` matching the color pipeline.
  //
  // Visibility approximation: `fsVelocity` does NOT replicate the
  // color FS's `classifyFragment` check (would require carrying the
  // four plane varyings into VelocityVOut), so the velocity texture
  // emits motion for ALL volume-rasterized fragments — including sky
  // regions where the color pass would have discarded. This is
  // acceptable for v1 because TAA's reprojection samples are
  // dominantly determined by where the COLOR pass writes — sky pixels
  // reproject to sky (identical across frames) regardless of velocity
  // value, so the "extra" motion data has no visible effect. A future
  // refinement could replicate the plane-test in velocity FS for
  // exact visibility parity.
  const velocityDescriptor = {
    name: `Vector3DTileClampedPolylines velocity [${depthFormat}]`,
    layout,
    vertex: { module: mod, entryPoint: "vsVelocity", buffers: vertexBuffers },
    fragment: {
      module: mod,
      entryPoint: "fsVelocity",
      targets: [{ format: "rg16float" }],
    },
    primitive: { topology: "triangle-list", cullMode: "front" },
    depthStencil: {
      format: depthFormat,
      depthWriteEnabled: false,
      depthCompare: "always",
    },
  };

  return {
    colorDescriptor,
    pickDescriptor,
    stencilDescriptor,
    velocityDescriptor,
    sharedBgl,
    depthSampleBgl,
  };
}

function descriptorToGPU(d) {
  return {
    label: d.name,
    layout: d.layout ?? "auto",
    vertex: {
      module: d.vertex.module,
      entryPoint: d.vertex.entryPoint,
      buffers: d.vertex.buffers,
    },
    fragment: d.fragment
      ? {
          module: d.fragment.module,
          entryPoint: d.fragment.entryPoint,
          targets: d.fragment.targets,
        }
      : undefined,
    primitive: d.primitive,
    depthStencil: d.depthStencil,
    multisample: d.multisample,
  };
}

function tryResolvePipelines(device, pipelineCache, resources, cache) {
  if (cache.colorPipeline && cache.pickPipeline && cache.stencilPipeline) {
    return true;
  }
  if (pipelineCache) {
    if (!cache.colorPipeline) {
      const sync = pipelineCache.getPipelineSync(resources.colorDescriptor);
      if (sync) {
        cache.colorPipeline = sync;
      } else if (!cache.colorRequestPending) {
        cache.colorRequestPending = true;
        pipelineCache
          .getPipeline(resources.colorDescriptor)
          .then((p) => {
            cache.colorPipeline = p;
            cache.colorRequestPending = false;
          })
          .catch(() => {
            cache.colorRequestPending = false;
          });
      }
    }
    if (!cache.pickPipeline) {
      const pickSync = pipelineCache.getPipelineSync(resources.pickDescriptor);
      if (pickSync) {
        cache.pickPipeline = pickSync;
      } else if (!cache.pickRequestPending) {
        cache.pickRequestPending = true;
        pipelineCache
          .getPipeline(resources.pickDescriptor)
          .then((p) => {
            cache.pickPipeline = p;
            cache.pickRequestPending = false;
          })
          .catch(() => {
            cache.pickRequestPending = false;
          });
      }
    }
    if (!cache.stencilPipeline) {
      const stencilSync = pipelineCache.getPipelineSync(
        resources.stencilDescriptor,
      );
      if (stencilSync) {
        cache.stencilPipeline = stencilSync;
      } else if (!cache.stencilRequestPending) {
        cache.stencilRequestPending = true;
        pipelineCache
          .getPipeline(resources.stencilDescriptor)
          .then((p) => {
            cache.stencilPipeline = p;
            cache.stencilRequestPending = false;
          })
          .catch(() => {
            cache.stencilRequestPending = false;
          });
      }
    }
    // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — velocity
    // pipeline. Cache miss is non-fatal: color pass continues without
    // it; velocity-pass dispatch becomes a no-op until the variant
    // lands.
    if (!cache.velocityPipeline) {
      const velSync = pipelineCache.getPipelineSync(
        resources.velocityDescriptor,
      );
      if (velSync) {
        cache.velocityPipeline = velSync;
      } else if (!cache.velocityRequestPending) {
        cache.velocityRequestPending = true;
        pipelineCache
          .getPipeline(resources.velocityDescriptor)
          .then((p) => {
            cache.velocityPipeline = p;
            cache.velocityRequestPending = false;
          })
          .catch(() => {
            cache.velocityRequestPending = false;
          });
      }
    }
    return !!cache.colorPipeline;
  }
  if (!cache.colorPipeline) {
    cache.colorPipeline = device.createRenderPipeline(
      descriptorToGPU(resources.colorDescriptor),
    );
  }
  if (!cache.pickPipeline) {
    cache.pickPipeline = device.createRenderPipeline(
      descriptorToGPU(resources.pickDescriptor),
    );
  }
  if (!cache.stencilPipeline) {
    cache.stencilPipeline = device.createRenderPipeline(
      descriptorToGPU(resources.stencilDescriptor),
    );
  }
  // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — fallback path.
  if (!cache.velocityPipeline) {
    cache.velocityPipeline = device.createRenderPipeline(
      descriptorToGPU(resources.velocityDescriptor),
    );
  }
  return true;
}

const scratchModifiedView = new Matrix4();

function packUniforms(data, frameState, primitive) {
  const uniformState = frameState.context.uniformState;

  // u_modifiedModelView = view with translation set to view * center.
  // This matches the WebGL VS and keeps RTC precision intact.
  Matrix4.clone(uniformState.view, scratchModifiedView);
  const center = primitive._center;
  if (defined(center)) {
    const m = scratchModifiedView;
    const tx = m[0] * center.x + m[4] * center.y + m[8] * center.z + m[12];
    const ty = m[1] * center.x + m[5] * center.y + m[9] * center.z + m[13];
    const tz = m[2] * center.x + m[6] * center.y + m[10] * center.z + m[14];
    m[12] = tx;
    m[13] = ty;
    m[14] = tz;
  }
  Matrix4.pack(scratchModifiedView, data, 0);
  Matrix4.pack(uniformState.projection, data, 16);
  Matrix4.pack(uniformState.inverseProjection, data, 32);

  // czm_normal — Matrix3 stored column-major. Pack as 3 padded vec4
  // columns starting at float 48.
  const normal = uniformState.normal;
  data[48] = normal[0];
  data[49] = normal[1];
  data[50] = normal[2];
  data[51] = 0.0;
  data[52] = normal[3];
  data[53] = normal[4];
  data[54] = normal[5];
  data[55] = 0.0;
  data[56] = normal[6];
  data[57] = normal[7];
  data[58] = normal[8];
  data[59] = 0.0;

  // Viewport — source from context.drawingBufferWidth/Height directly.
  // See WebGPUGroundPolylineRenderer.js packUniforms for the full
  // explanation; same bug-pattern (uniformState.viewportCartesian4 is
  // zero-initialized at FR-update time and `??` doesn't fall through on 0).
  const ctx = frameState.context;
  data[60] = 0.0;
  data[61] = 0.0;
  data[62] = ctx?.drawingBufferWidth || 1;
  data[63] = ctx?.drawingBufferHeight || 1;

  const mmh = primitive._minimumMaximumVectorHeights;
  data[64] = mmh?.x ?? 0.0;
  data[65] = mmh?.y ?? 0.0;
  data[66] = uniformState.pixelRatio ?? 1.0;
  data[67] = 0.0;

  // AUDIT_2026_05_02 B.9 (Batch 153) — DP-H41 prev viewProjection at
  // floats 68..83 (272 bytes used → mat4 starts at 16-aligned offset).
  const prevVP = uniformState.previousViewProjection;
  if (prevVP) {
    Matrix4.pack(prevVP, data, 68);
  } else {
    data[68] = 1;
    data[69] = 0;
    data[70] = 0;
    data[71] = 0;
    data[72] = 0;
    data[73] = 1;
    data[74] = 0;
    data[75] = 0;
    data[76] = 0;
    data[77] = 0;
    data[78] = 1;
    data[79] = 0;
    data[80] = 0;
    data[81] = 0;
    data[82] = 0;
    data[83] = 1;
  }

  // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — primitive
  // center in world coordinates at floats 84..86 (vec3 + 1 pad). UBO
  // capacity is 384 bytes (96 floats); after prev-VP at 68..83 the
  // next 16-byte-aligned offset is 84.
  const centerWC =
    primitive._center && defined(primitive._center) ? primitive._center : null;
  if (centerWC) {
    data[84] = centerWC.x;
    data[85] = centerWC.y;
    data[86] = centerWC.z;
  } else {
    data[84] = 0;
    data[85] = 0;
    data[86] = 0;
  }
  data[87] = 0.0;
}

function ensureVertexBuffer(cache, primitive, device) {
  if (defined(cache.vertexGPUBuffer)) {
    return;
  }

  const startEN = primitive._startEllipsoidNormals;
  const endEN = primitive._endEllipsoidNormals;
  const startPosH = primitive._startPositionAndHeights;
  const endPosH = primitive._endPositionAndHeights;
  const startFaceNVC = primitive._startFaceNormalAndVertexCornerIds;
  const endFaceNHW = primitive._endFaceNormalAndHalfWidths;
  const vertexBatchIds = primitive._vertexBatchIds;
  if (
    !defined(startEN) ||
    !defined(endEN) ||
    !defined(startPosH) ||
    !defined(endPosH) ||
    !defined(startFaceNVC) ||
    !defined(endFaceNHW) ||
    !defined(vertexBatchIds)
  ) {
    return;
  }

  const numVerts = startEN.length / 3;
  if (numVerts === 0) {
    return;
  }

  const interleaved = new Float32Array(numVerts * VERTEX_STRIDE_FLOATS);
  for (let v = 0; v < numVerts; v++) {
    const dst = v * VERTEX_STRIDE_FLOATS;
    const s3 = v * 3;
    const s4 = v * 4;
    interleaved[dst] = startEN[s3];
    interleaved[dst + 1] = startEN[s3 + 1];
    interleaved[dst + 2] = startEN[s3 + 2];
    interleaved[dst + 3] = vertexBatchIds[v];
    interleaved[dst + 4] = endEN[s3];
    interleaved[dst + 5] = endEN[s3 + 1];
    interleaved[dst + 6] = endEN[s3 + 2];
    // dst + 7 padded by Float32Array zero init.
    interleaved[dst + 8] = startPosH[s4];
    interleaved[dst + 9] = startPosH[s4 + 1];
    interleaved[dst + 10] = startPosH[s4 + 2];
    interleaved[dst + 11] = startPosH[s4 + 3];
    interleaved[dst + 12] = endPosH[s4];
    interleaved[dst + 13] = endPosH[s4 + 1];
    interleaved[dst + 14] = endPosH[s4 + 2];
    interleaved[dst + 15] = endPosH[s4 + 3];
    interleaved[dst + 16] = startFaceNVC[s4];
    interleaved[dst + 17] = startFaceNVC[s4 + 1];
    interleaved[dst + 18] = startFaceNVC[s4 + 2];
    interleaved[dst + 19] = startFaceNVC[s4 + 3];
    interleaved[dst + 20] = endFaceNHW[s4];
    interleaved[dst + 21] = endFaceNHW[s4 + 1];
    interleaved[dst + 22] = endFaceNHW[s4 + 2];
    interleaved[dst + 23] = endFaceNHW[s4 + 3];
  }

  cache.vertexGPUBuffer = WebGPUBuffer.createVertexBuffer(
    device,
    interleaved,
    "Vector3DTileClampedPolylines VB",
  );
  cache.vertexCount = numVerts;
}

function ensureIndexBuffer(cache, primitive, device) {
  if (defined(cache.indexGPUBuffer)) {
    return;
  }
  const indices = primitive._indices;
  if (!defined(indices)) {
    return;
  }

  const needsU32 = indices.BYTES_PER_ELEMENT === 4;
  const typed = needsU32 ? new Uint32Array(indices) : new Uint16Array(indices);
  cache.indexFormat = needsU32 ? "uint32" : "uint16";
  cache.indexGPUBuffer = device.createBuffer({
    label: "Vector3DTileClampedPolylines IB",
    size: typed.byteLength,
    usage: GPUBufferUsage.INDEX | GPUBufferUsage.COPY_DST,
  });
  device.queue.writeBuffer(cache.indexGPUBuffer, 0, typed);
  cache.indexCount = indices.length;
}

function ensureBatchColorStorage(cache, primitive, device) {
  const featuresLength =
    primitive._batchTable?.featuresLength ??
    primitive._batchIds?.length ??
    INITIAL_BATCH_BUFFER_FEATURES;
  const requiredBytes = Math.max(
    featuresLength * BYTES_PER_BATCH_COLOR,
    INITIAL_BATCH_BUFFER_FEATURES * BYTES_PER_BATCH_COLOR,
  );

  if (
    defined(cache.batchColorBuffer) &&
    cache.batchColorBufferCapacity >= requiredBytes
  ) {
    return;
  }
  if (defined(cache.batchColorBuffer)) {
    cache.batchColorBuffer.destroy();
  }
  cache.batchColorBuffer = device.createBuffer({
    label: "Vector3DTileClampedPolylines batch colors",
    size: requiredBytes,
    usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
  });
  cache.batchColorBufferCapacity = requiredBytes;
  cache.batchColorScratch = new Float32Array(requiredBytes / 4);
  cache._sharedBindGroupDirty = true;
}

function uploadBatchColors(cache, primitive, device) {
  const scratch = cache.batchColorScratch;
  if (!defined(scratch)) {
    return;
  }

  // Default every feature to the primitive-level highlight color. The
  // batch-table style hook overrides per feature when applyStyle runs.
  const highlight = primitive._highlightColor;
  const r = highlight?.red ?? 1.0;
  const g = highlight?.green ?? 1.0;
  const b = highlight?.blue ?? 1.0;
  const a = highlight?.alpha ?? 1.0;
  for (let i = 0; i < scratch.length; i += 4) {
    scratch[i] = r;
    scratch[i + 1] = g;
    scratch[i + 2] = b;
    scratch[i + 3] = a;
  }

  // AUDIT_2026_05_02 B.1 — fold per-feature `Cesium3DTileFeature.show`
  // into batch alpha so the FS discard branch hides set-show-false
  // features.
  const batchTable = primitive._batchTable;
  if (defined(batchTable) && typeof batchTable.getShow === "function") {
    const featuresLength = batchTable.featuresLength ?? 0;
    for (let id = 0; id < featuresLength; id++) {
      const slot = id * 4 + 3;
      if (slot >= scratch.length) {
        break;
      }
      if (!batchTable.getShow(id)) {
        scratch[slot] = 0.0;
      }
    }
  }

  device.queue.writeBuffer(
    cache.batchColorBuffer,
    0,
    scratch.buffer,
    scratch.byteOffset,
    cache.batchColorBufferCapacity,
  );
}

function ensurePickColorStorage(cache, primitive, device) {
  // Mirror of `ensureBatchColorStorage`. Required at @group(0) @binding(2)
  // even when the pick pipeline isn't running this frame — WebGPU forbids
  // partial bind groups.
  const featuresLength =
    primitive._batchTable?.featuresLength ??
    primitive._batchIds?.length ??
    INITIAL_BATCH_BUFFER_FEATURES;
  const requiredBytes = Math.max(
    featuresLength * BYTES_PER_BATCH_COLOR,
    INITIAL_BATCH_BUFFER_FEATURES * BYTES_PER_BATCH_COLOR,
  );

  if (
    defined(cache.pickColorBuffer) &&
    cache.pickColorBufferCapacity >= requiredBytes
  ) {
    return;
  }
  if (defined(cache.pickColorBuffer)) {
    cache.pickColorBuffer.destroy();
  }
  cache.pickColorBuffer = device.createBuffer({
    label: "Vector3DTileClampedPolylines pick colors",
    size: requiredBytes,
    usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
  });
  cache.pickColorBufferCapacity = requiredBytes;
  cache.pickColorScratch = new Float32Array(requiredBytes / 4);
  cache._sharedBindGroupDirty = true;
  cache._pickColorsUploaded = false;
}

function uploadPickColors(cache, primitive, device) {
  const scratch = cache.pickColorScratch;
  if (!defined(scratch)) {
    return;
  }
  scratch.fill(0);

  const batchTable = primitive._batchTable;
  if (defined(batchTable) && typeof batchTable.getPickColor === "function") {
    const length = batchTable.featuresLength ?? 0;
    for (let i = 0; i < length; i++) {
      const pickId = batchTable.getPickColor(i);
      const color = pickId?.color;
      if (!defined(color)) {
        continue;
      }
      const slot = i * 4;
      if (slot + 3 < scratch.length) {
        scratch[slot] = color.red;
        scratch[slot + 1] = color.green;
        scratch[slot + 2] = color.blue;
        scratch[slot + 3] = color.alpha;
      }
    }
  }

  device.queue.writeBuffer(
    cache.pickColorBuffer,
    0,
    scratch.buffer,
    scratch.byteOffset,
    cache.pickColorBufferCapacity,
  );
}

function createWebGPUVector3DTileClampedPolylineCommands(
  primitive,
  frameState,
) {
  const context = frameState.context;
  const device = context.device;

  // AUDIT_2026_05_02 A.4 (Batch 150) — non-SCENE3D scene mode gate.
  // ClampedPolylines reads a 7-attribute interleaved vertex stream
  // tied to 3D ECEF positions and ellipsoid normals; 2D / Columbus
  // View support requires a parallel per-mode attribute set (mirroring
  // GroundPolyline's Batch 116/117 pattern). 3D Tiles vector tile
  // content is typically only viewed in 3D mode in production, so
  // silently skipping emission here matches user-expected behavior.
  // Tracked as a follow-up in DEFERRED_WORK.md.
  if (frameState?.mode !== SceneMode.SCENE3D) {
    //>>includeStart('debug', pragmas.debug);
    oneTimeWarning(
      "WebGPUVector3DTileClampedPolylines.sceneMode",
      "Vector3DTileClampedPolylines on WebGPU is currently only correct in " +
        "SceneMode.SCENE3D. Non-3D scene modes (2D, Columbus View, Morphing) " +
        "are silently skipped. Tracked as A.4 / NEW-CLASSIFIER-2D-CV-MORPH " +
        "in DEFERRED_WORK.md.",
    );
    //>>includeEnd('debug');
    return { colorCommands: [], pickCommands: [], ignoreShowCommands: [] };
  }

  if (!defined(primitive._webgpuCache)) {
    primitive._webgpuCache = {};
  }
  const cache = primitive._webgpuCache;

  const sceneGen = context._scenePipelineFormatGeneration ?? 0;
  if (
    defined(cache._pipelineResources) &&
    cache._pipelineFormatGeneration !== sceneGen
  ) {
    cache._pipelineResources = undefined;
    cache.colorPipeline = undefined;
    cache.pickPipeline = undefined;
    cache.stencilPipeline = undefined;
    // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — clear the
    // velocity pipeline alongside color/pick/stencil on format change
    // so the resolver re-runs against the new presentation format.
    cache.velocityPipeline = undefined;
    cache.sharedBindGroup = undefined;
    cache.depthSampleBindGroup = undefined;
  }
  if (!defined(cache._pipelineResources)) {
    const format = context.scenePipelineFormat || "bgra8unorm";
    const depthFmt = context.depthFormat || "depth24plus-stencil8";
    cache._pipelineResources = buildClampedPolylinePipelineResources(
      device,
      format,
      depthFmt,
    );
    cache._pipelineFormatGeneration = sceneGen;
    cache.colorRequestPending = false;
    cache.pickRequestPending = false;
    cache.stencilRequestPending = false;
    cache.velocityRequestPending = false;
  }
  if (
    !tryResolvePipelines(
      device,
      context.webgpuPipelineCache ?? null,
      cache._pipelineResources,
      cache,
    )
  ) {
    return { colorCommands: [], pickCommands: [] };
  }

  if (!defined(cache.uniformBuffer)) {
    cache.uniformBuffer = WebGPUBuffer.createUniformBuffer(
      device,
      UNIFORM_BUFFER_SIZE,
      "Vector3DTileClampedPolylines uniforms",
    );
    cache.uniformData = new Float32Array(UNIFORM_BUFFER_SIZE / 4);
  }
  ensureBatchColorStorage(cache, primitive, device);
  ensurePickColorStorage(cache, primitive, device);
  if (cache._sharedBindGroupDirty || !defined(cache.sharedBindGroup)) {
    cache.sharedBindGroup = device.createBindGroup({
      label: "Vector3DTileClampedPolylines shared BG",
      layout: cache._pipelineResources.sharedBgl,
      entries: [
        { binding: 0, resource: { buffer: cache.uniformBuffer.buffer } },
        { binding: 1, resource: { buffer: cache.batchColorBuffer } },
        { binding: 2, resource: { buffer: cache.pickColorBuffer } },
      ],
    });
    cache._sharedBindGroupDirty = false;
  }

  ensureVertexBuffer(cache, primitive, device);
  ensureIndexBuffer(cache, primitive, device);
  if (!defined(cache.vertexGPUBuffer) || !defined(cache.indexGPUBuffer)) {
    return { colorCommands: [], pickCommands: [] };
  }

  packUniforms(cache.uniformData, frameState, primitive);
  device.queue.writeBuffer(
    cache.uniformBuffer.buffer,
    0,
    cache.uniformData.buffer,
    0,
    UNIFORM_BUFFER_SIZE,
  );

  // AUDIT_2026_05_02 B.1 — re-upload on batch table dirty-values to
  // pick up per-feature `show` toggles.
  // (Audit-rereview correction: _batchValuesDirty lives on the
  // batchTable's _batchTexture, not on _batchTable directly.)
  const batchValuesDirty =
    primitive._batchTable?._batchTexture?._batchValuesDirty === true;
  if (!cache._batchColorsUploaded || batchValuesDirty) {
    uploadBatchColors(cache, primitive, device);
    cache._batchColorsUploaded = true;
  }
  if (!cache._pickColorsUploaded) {
    uploadPickColors(cache, primitive, device);
    cache._pickColorsUploaded = true;
  }

  // Depth-source resolver. Mirrors WebGPUVector3DTilePrimitiveRenderer:
  // pick `_packedTranslucentDepthView` if present (covers both terrain
  // + 3D-Tile depth), else fall back to `_globeDepthView`.
  const packedTranslucentView = context._packedTranslucentDepthView ?? null;
  const globeDepthView = context._globeDepthView ?? null;
  const depthSourceView = packedTranslucentView ?? globeDepthView;
  if (!depthSourceView) {
    return { colorCommands: [], pickCommands: [], ignoreShowCommands: [] };
  }
  if (!defined(cache.depthSampleSampler)) {
    cache.depthSampleSampler = device.createSampler({
      label: "Vector3DTileClampedPolylines depth-sample sampler",
      magFilter: "linear",
      minFilter: "linear",
      addressModeU: "clamp-to-edge",
      addressModeV: "clamp-to-edge",
    });
  }
  if (
    !defined(cache.depthSampleBindGroup) ||
    cache.depthSampleViewRef !== depthSourceView
  ) {
    cache.depthSampleBindGroup = device.createBindGroup({
      label: "Vector3DTileClampedPolylines depth-sample BG",
      layout: cache._pipelineResources.depthSampleBgl,
      entries: [
        { binding: 0, resource: depthSourceView },
        { binding: 1, resource: cache.depthSampleSampler },
      ],
    });
    cache.depthSampleViewRef = depthSourceView;
  }
  const resolveDepthSampleBindGroup = () => {
    const currentSource =
      context._packedTranslucentDepthView ?? context._globeDepthView;
    if (!currentSource) {
      return null;
    }
    if (cache.depthSampleViewRef !== currentSource) {
      cache.depthSampleBindGroup = device.createBindGroup({
        label: "Vector3DTileClampedPolylines depth-sample BG",
        layout: cache._pipelineResources.depthSampleBgl,
        entries: [
          { binding: 0, resource: currentSource },
          { binding: 1, resource: cache.depthSampleSampler },
        ],
      });
      cache.depthSampleViewRef = currentSource;
    }
    return cache.depthSampleBindGroup;
  };

  // Pass routing — emit one command per pass the primitive should
  // appear in (TERRAIN, 3D-TILE, or both).
  const classType =
    primitive._classificationType ?? CLASSIFICATION_TYPE_TERRAIN;
  const colorCommands = [];
  const pickCommands = [];
  const sharedDrawArgs = {
    bindGroups: [cache.sharedBindGroup, cache.depthSampleBindGroup],
    bindGroupResolvers: [undefined, resolveDepthSampleBindGroup],
    vertexBuffers: [cache.vertexGPUBuffer],
    indexBuffer: cache.indexGPUBuffer,
    indexFormat: cache.indexFormat,
    indexCount: cache.indexCount || 0,
    vertexCount: 0,
    owner: primitive,
  };
  const passes = [];
  if (
    classType === CLASSIFICATION_TYPE_TERRAIN ||
    classType === CLASSIFICATION_TYPE_BOTH
  ) {
    passes.push(PASS_TERRAIN_CLASSIFICATION);
  }
  if (
    classType === CLASSIFICATION_TYPE_3DTILE ||
    classType === CLASSIFICATION_TYPE_BOTH
  ) {
    passes.push(PASS_CESIUM_3D_TILE_CLASSIFICATION);
  }
  // AUDIT_2026_05_02 A.2 (Batch 141, NEW-INVERT-CLASS-STENCIL-CLASSIFIER) —
  // IGNORE_SHOW stencil-write commands. Only emitted for primitives that
  // classify 3D Tiles (TYPE_3DTILE or BOTH); TERRAIN-only doesn't
  // participate in invert classification. The pass is hard-coded to 7
  // (CESIUM_3D_TILE_CLASSIFICATION_IGNORE_SHOW); a TERRAIN-classifying
  // primitive that's also marked BOTH still gets one IGNORE_SHOW command
  // (the 3D Tile half), no separate TERRAIN_CLASSIFICATION_IGNORE_SHOW.
  const ignoreShowCommands = [];
  const emitsThreeDTileClassification =
    classType === CLASSIFICATION_TYPE_3DTILE ||
    classType === CLASSIFICATION_TYPE_BOTH;
  // NEW-ADVANCED-MOTION-VECTORS classifiers (Batch 179) — derive
  // velocity command alongside the color command when TAA is on. Only
  // attached to the FIRST color command (p === 0) — the BOTH-pass
  // dual-emit doesn't need duplicate velocity (per-feature animation
  // isn't possible for static classification volumes anyway). Same
  // pattern as Vector3DTilePrimitive (Batch 178) and the Polylines
  // sibling (Batch 179).
  const taaEnabled = frameState?.taaEnabled === true;
  for (let i = 0; i < passes.length; i++) {
    const passEnum = passes[i];
    const colorCmd = new WebGPUDrawCommand({
      ...sharedDrawArgs,
      pipeline: cache.colorPipeline,
      pass: passEnum,
    });
    if (taaEnabled && i === 0 && defined(cache.velocityPipeline)) {
      colorCmd.velocityCommand = new WebGPUDrawCommand({
        ...sharedDrawArgs,
        pipeline: cache.velocityPipeline,
        pass: passEnum,
      });
    }
    colorCommands.push(colorCmd);
    if (defined(cache.pickPipeline)) {
      pickCommands.push(
        new WebGPUDrawCommand({
          ...sharedDrawArgs,
          pipeline: cache.pickPipeline,
          pass: passEnum,
          pickOnly: true,
        }),
      );
    }
  }
  if (emitsThreeDTileClassification && defined(cache.stencilPipeline)) {
    ignoreShowCommands.push(
      new WebGPUDrawCommand({
        ...sharedDrawArgs,
        pipeline: cache.stencilPipeline,
        pass: 7 /* CESIUM_3D_TILE_CLASSIFICATION_IGNORE_SHOW */,
        renderState: { stencilTest: { reference: 0xff } },
      }),
    );
  }

  return { colorCommands, pickCommands, ignoreShowCommands };
}

function destroyWebGPUVector3DTileClampedPolylineResources(primitive) {
  const cache = primitive._webgpuCache;
  if (!defined(cache)) {
    return;
  }
  if (defined(cache.uniformBuffer)) {
    cache.uniformBuffer.destroy();
  }
  if (defined(cache.batchColorBuffer)) {
    cache.batchColorBuffer.destroy();
  }
  if (defined(cache.pickColorBuffer)) {
    cache.pickColorBuffer.destroy();
  }
  if (defined(cache.vertexGPUBuffer)) {
    cache.vertexGPUBuffer.destroy();
  }
  if (defined(cache.indexGPUBuffer)) {
    cache.indexGPUBuffer.destroy();
  }
  primitive._webgpuCache = undefined;
}

export {
  createWebGPUVector3DTileClampedPolylineCommands,
  destroyWebGPUVector3DTileClampedPolylineResources,
};
export default {
  createWebGPUVector3DTileClampedPolylineCommands,
  destroyWebGPUVector3DTileClampedPolylineResources,
};
