/**
 * @module WebGPUPrimitiveShaders
 *
 * Shader selection logic, vertex layout configuration, and uniform buffer sizing
 * for the WebGPU Primitive rendering pipeline.
 *
 * All WGSL shader source code is imported from pre-built JS modules under:
 *   Source/Shaders/WebGPU/Primitive/
 *
 * Each .wgsl file has a companion .js file (auto-generated by the build) that
 * exports the shader source as a string. This avoids runtime fetch() calls.
 *
 * @private
 */
import defined from "../../Core/defined.js";

// =========================================================================
// Static shader imports — bundled by esbuild, no runtime fetch needed
// =========================================================================
import PrimitiveBasicColor from "../../Shaders/WebGPU/Primitive/PrimitiveBasicColor.js";
import PrimitivePhongColor from "../../Shaders/WebGPU/Primitive/PrimitivePhongColor.js";
import PrimitiveBasicTexturedColor from "../../Shaders/WebGPU/Primitive/PrimitiveBasicTexturedColor.js";
import PrimitivePhongTexturedColor from "../../Shaders/WebGPU/Primitive/PrimitivePhongTexturedColor.js";
import PrimitivePickBasic from "../../Shaders/WebGPU/Primitive/PrimitivePickBasic.js";
import PrimitivePickPhong from "../../Shaders/WebGPU/Primitive/PrimitivePickPhong.js";
import PrimitivePickBasicTextured from "../../Shaders/WebGPU/Primitive/PrimitivePickBasicTextured.js";
import PrimitivePickPhongTextured from "../../Shaders/WebGPU/Primitive/PrimitivePickPhongTextured.js";
import PrimitiveMatColorFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatColorFlat.js";
import PrimitiveMatColorLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatColorLit.js";
import PrimitiveMatImageFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatImageFlat.js";
import PrimitiveMatImageLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatImageLit.js";
import PrimitiveMatCheckerFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatCheckerFlat.js";
import PrimitiveMatCheckerLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatCheckerLit.js";
import PrimitiveMatGridFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatGridFlat.js";
import PrimitiveMatGridLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatGridLit.js";
import PrimitiveMatStripeFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatStripeFlat.js";
import PrimitiveMatStripeLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatStripeLit.js";
import PrimitiveMatDotFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatDotFlat.js";
import PrimitiveMatDotLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatDotLit.js";
import PrimitiveMatFadeFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatFadeFlat.js";
import PrimitiveMatFadeLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatFadeLit.js";
import PrimitiveMatRimLightingFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatRimLightingFlat.js";
import PrimitiveMatRimLightingLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatRimLightingLit.js";
import PrimitiveMatAlphaMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatAlphaMapFlat.js";
import PrimitiveMatAlphaMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatAlphaMapLit.js";
import PrimitiveMatEmissionMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatEmissionMapFlat.js";
import PrimitiveMatEmissionMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatEmissionMapLit.js";
import PrimitiveMatSpecularMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatSpecularMapFlat.js";
import PrimitiveMatSpecularMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatSpecularMapLit.js";
import PrimitiveMatBumpMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatBumpMapFlat.js";
import PrimitiveMatBumpMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatBumpMapLit.js";
import PrimitiveMatNormalMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatNormalMapFlat.js";
import PrimitiveMatNormalMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatNormalMapLit.js";
import PrimitiveMatWaterFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatWaterFlat.js";
import PrimitiveMatWaterLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatWaterLit.js";
import PrimitiveMatElevContourFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatElevContourFlat.js";
import PrimitiveMatElevContourLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatElevContourLit.js";
import PrimitiveMatElevRampFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatElevRampFlat.js";
import PrimitiveMatElevRampLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatElevRampLit.js";
import PrimitiveMatSlopeRampFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatSlopeRampFlat.js";
import PrimitiveMatSlopeRampLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatSlopeRampLit.js";
import PrimitiveMatAspectRampFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatAspectRampFlat.js";
import PrimitiveMatAspectRampLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatAspectRampLit.js";
import PrimitivePickMatFlat from "../../Shaders/WebGPU/Primitive/PrimitivePickMatFlat.js";
import PrimitivePickMatLit from "../../Shaders/WebGPU/Primitive/PrimitivePickMatLit.js";
import PrimitivePBRSimple from "../../Shaders/WebGPU/Primitive/PrimitivePBRSimple.js";
import PrimitivePBRTextured from "../../Shaders/WebGPU/Primitive/PrimitivePBRTextured.js";

// =========================================================================
// Shader Cache — populated synchronously from static imports
// =========================================================================

const _shaderCache = {
  // Per-instance color shaders
  basic: PrimitiveBasicColor,
  phong: PrimitivePhongColor,
  basicTextured: PrimitiveBasicTexturedColor,
  phongTextured: PrimitivePhongTexturedColor,
  // Pick shaders (per-instance color layouts)
  pickBasic: PrimitivePickBasic,
  pickPhong: PrimitivePickPhong,
  pickBasicTextured: PrimitivePickBasicTextured,
  pickPhongTextured: PrimitivePickPhongTextured,
  // Material shaders
  matColorFlat: PrimitiveMatColorFlat,
  matColorLit: PrimitiveMatColorLit,
  matImageFlat: PrimitiveMatImageFlat,
  matImageLit: PrimitiveMatImageLit,
  matCheckerFlat: PrimitiveMatCheckerFlat,
  matCheckerLit: PrimitiveMatCheckerLit,
  matGridFlat: PrimitiveMatGridFlat,
  matGridLit: PrimitiveMatGridLit,
  matStripeFlat: PrimitiveMatStripeFlat,
  matStripeLit: PrimitiveMatStripeLit,
  matDotFlat: PrimitiveMatDotFlat,
  matDotLit: PrimitiveMatDotLit,
  matFadeFlat: PrimitiveMatFadeFlat,
  matFadeLit: PrimitiveMatFadeLit,
  matRimLightingFlat: PrimitiveMatRimLightingFlat,
  matRimLightingLit: PrimitiveMatRimLightingLit,
  matAlphaMapFlat: PrimitiveMatAlphaMapFlat,
  matAlphaMapLit: PrimitiveMatAlphaMapLit,
  matEmissionMapFlat: PrimitiveMatEmissionMapFlat,
  matEmissionMapLit: PrimitiveMatEmissionMapLit,
  matSpecularMapFlat: PrimitiveMatSpecularMapFlat,
  matSpecularMapLit: PrimitiveMatSpecularMapLit,
  matBumpMapFlat: PrimitiveMatBumpMapFlat,
  matBumpMapLit: PrimitiveMatBumpMapLit,
  matNormalMapFlat: PrimitiveMatNormalMapFlat,
  matNormalMapLit: PrimitiveMatNormalMapLit,
  matWaterFlat: PrimitiveMatWaterFlat,
  matWaterLit: PrimitiveMatWaterLit,
  matElevContourFlat: PrimitiveMatElevContourFlat,
  matElevContourLit: PrimitiveMatElevContourLit,
  matElevRampFlat: PrimitiveMatElevRampFlat,
  matElevRampLit: PrimitiveMatElevRampLit,
  matSlopeRampFlat: PrimitiveMatSlopeRampFlat,
  matSlopeRampLit: PrimitiveMatSlopeRampLit,
  matAspectRampFlat: PrimitiveMatAspectRampFlat,
  matAspectRampLit: PrimitiveMatAspectRampLit,
  // Pick shaders (material layouts)
  pickMatFlat: PrimitivePickMatFlat,
  pickMatLit: PrimitivePickMatLit,
  // PBR shaders
  pbrSimple: PrimitivePBRSimple,
  pbrTextured: PrimitivePBRTextured,
};

// Shaders are always available — no async loading needed
const _shadersLoaded = true;

// =========================================================================
// Shader Loading (kept for API compatibility, now a no-op)
// =========================================================================

/**
 * Initializes the primitive shader cache.
 * With static imports, this is a no-op — shaders are available immediately.
 * Kept for API compatibility with callers that expect an async init step.
 *
 * @returns {Promise<void>} Resolves immediately.
 * @private
 */
async function initPrimitiveShaders() {
  // No-op: shaders are statically imported and always available
  return;
}

/**
 * Returns the cached WGSL source for a shader key.
 *
 * @param {string} key - Shader key (e.g., 'basic', 'phong', 'matColorFlat', 'pbrSimple')
 * @returns {string} WGSL shader source code
 * @private
 */
function getShaderSource(key) {
  const source = _shaderCache[key];
  if (!defined(source)) {
    throw new Error(
      `[WebGPUPrimitiveShaders] Unknown shader key: "${key}". Available: ${Object.keys(_shaderCache).join(", ")}`,
    );
  }
  return source;
}

/**
 * Returns true if the shader cache has been populated.
 * @returns {boolean}
 * @private
 */
function areShadersLoaded() {
  return _shadersLoaded;
}

// =========================================================================
// Per-Instance Color Shader Selection
// =========================================================================

/**
 * Determines which WGSL shader to use based on available geometry attributes.
 * Shader selection hierarchy:
 * - phongTextured: position + normal + st → Phong lighting + texture sampling
 * - basicTextured: position + st → Texture sampling + color
 * - phong: position + normal → Phong lighting + color
 * - basic: position → Color only
 *
 * @param {object} attributes - Geometry attributes
 * @returns {{ type: string, code: string, hasUV: boolean }} Shader type, WGSL code, and UV flag
 * @private
 */
function selectWebGPUShader(attributes) {
  const hasNormals =
    defined(attributes.normal) && defined(attributes.normal.values);
  const hasST = defined(attributes.st) && defined(attributes.st.values);

  if (hasNormals && hasST) {
    return {
      type: "phongTextured",
      code: getShaderSource("phongTextured"),
      hasUV: true,
    };
  }
  if (hasST) {
    return {
      type: "basicTextured",
      code: getShaderSource("basicTextured"),
      hasUV: true,
    };
  }
  if (hasNormals) {
    return { type: "phong", code: getShaderSource("phong"), hasUV: false };
  }
  return { type: "basic", code: getShaderSource("basic"), hasUV: false };
}

// =========================================================================
// Vertex Layout Configurations
// =========================================================================

/**
 * Returns the vertex buffer layout descriptor for a given shader type.
 *
 * @param {string} shaderType - Shader type identifier
 * @returns {{ floatsPerVertex: number, stride: number, layout: GPUVertexBufferLayout }}
 * @private
 */
function getVertexLayoutForShader(shaderType) {
  // RTE: All layouts include positionHigh(3) + positionLow(3) at locations 0-1
  if (shaderType === "phongTextured") {
    // posHigh(3) + posLow(3) + normal(3) + uv(2) + color(4) = 15 floats = 60 bytes
    return {
      floatsPerVertex: 15,
      stride: 60,
      layout: {
        arrayStride: 60,
        attributes: [
          { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
          { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
          { shaderLocation: 2, offset: 24, format: "float32x3" }, // normal
          { shaderLocation: 3, offset: 36, format: "float32x2" }, // texCoord
          { shaderLocation: 4, offset: 44, format: "float32x4" }, // color
        ],
      },
    };
  }
  if (shaderType === "basicTextured") {
    // posHigh(3) + posLow(3) + uv(2) + color(4) = 12 floats = 48 bytes
    return {
      floatsPerVertex: 12,
      stride: 48,
      layout: {
        arrayStride: 48,
        attributes: [
          { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
          { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
          { shaderLocation: 2, offset: 24, format: "float32x2" }, // texCoord
          { shaderLocation: 3, offset: 32, format: "float32x4" }, // color
        ],
      },
    };
  }
  if (shaderType === "phong") {
    // posHigh(3) + posLow(3) + normal(3) + color(4) = 13 floats = 52 bytes
    return {
      floatsPerVertex: 13,
      stride: 52,
      layout: {
        arrayStride: 52,
        attributes: [
          { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
          { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
          { shaderLocation: 2, offset: 24, format: "float32x3" }, // normal
          { shaderLocation: 3, offset: 36, format: "float32x4" }, // color
        ],
      },
    };
  }
  // basic: posHigh(3) + posLow(3) + color(4) = 10 floats = 40 bytes
  return {
    floatsPerVertex: 10,
    stride: 40,
    layout: {
      arrayStride: 40,
      attributes: [
        { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
        { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
        { shaderLocation: 2, offset: 24, format: "float32x4" }, // color
      ],
    },
  };
}

/**
 * Returns the uniform buffer size for a given shader type (256-byte aligned).
 * @param {string} shaderType
 * @returns {number}
 * @private
 */
function getUniformSizeForShader(shaderType) {
  // All shader types use 256-byte uniform buffers
  return 256;
}

/**
 * Returns true if the shader type uses Phong lighting (needs normal matrix uniforms).
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isPhongShader(shaderType) {
  return shaderType === "phong" || shaderType === "phongTextured";
}

/**
 * Returns true if the shader type needs a texture bind group (group 1).
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isTexturedShader(shaderType) {
  return shaderType === "basicTextured" || shaderType === "phongTextured";
}

// =========================================================================
// Pick Shader Selection
// =========================================================================

/**
 * Returns the WGSL pick shader code for a given color shader type.
 * @param {string} shaderType - Color shader type
 * @returns {string} WGSL pick shader source
 * @private
 */
function getPickShaderForType(shaderType) {
  if (shaderType === "phongTextured") {
    return getShaderSource("pickPhongTextured");
  }
  if (shaderType === "basicTextured") {
    return getShaderSource("pickBasicTextured");
  }
  if (shaderType === "phong") {
    return getShaderSource("pickPhong");
  }
  return getShaderSource("pickBasic");
}

/**
 * Returns the WGSL pick shader code for a material shader type.
 * @param {string} shaderType - Material shader type
 * @returns {string} WGSL pick shader source
 * @private
 */
function getMaterialPickShaderForType(shaderType) {
  if (isMaterialLitShader(shaderType) || isPBRShader(shaderType)) {
    return getShaderSource("pickMatLit");
  }
  return getShaderSource("pickMatFlat");
}

/**
 * Returns the uniform buffer size for pick shaders (256-byte aligned).
 * @returns {number}
 * @private
 */
function getPickUniformSize() {
  return 256;
}

// =========================================================================
// Material Shader Selection
// =========================================================================

/**
 * Determines which WGSL material shader to use based on material type and geometry attributes.
 *
 * @param {object} material - The CesiumJS Material object
 * @param {boolean} isFlat - Whether the appearance uses flat shading
 * @param {boolean} hasNormals - Whether the geometry has normals
 * @param {boolean} hasST - Whether the geometry has texture coordinates
 * @returns {{ type: string, code: string, needsTexture: boolean }} Shader info
 * @private
 */
function selectMaterialShader(material, isFlat, hasNormals, hasST) {
  const materialType = defined(material) ? material.type : "Color";
  const useLighting = hasNormals && !isFlat;

  if (materialType === "Image" || materialType === "DiffuseMap") {
    if (useLighting && hasST) {
      return {
        type: "matImageLit",
        code: getShaderSource("matImageLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matImageFlat",
      code: getShaderSource("matImageFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "Checkerboard") {
    if (useLighting && hasST) {
      return {
        type: "matCheckerLit",
        code: getShaderSource("matCheckerLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matCheckerFlat",
      code: getShaderSource("matCheckerFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "Grid") {
    if (useLighting && hasST) {
      return {
        type: "matGridLit",
        code: getShaderSource("matGridLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matGridFlat",
      code: getShaderSource("matGridFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "Stripe") {
    if (useLighting && hasST) {
      return {
        type: "matStripeLit",
        code: getShaderSource("matStripeLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matStripeFlat",
      code: getShaderSource("matStripeFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "Dot") {
    if (useLighting && hasST) {
      return {
        type: "matDotLit",
        code: getShaderSource("matDotLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matDotFlat",
      code: getShaderSource("matDotFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "Fade") {
    if (useLighting && hasST) {
      return {
        type: "matFadeLit",
        code: getShaderSource("matFadeLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matFadeFlat",
      code: getShaderSource("matFadeFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "RimLighting") {
    if (useLighting && hasST) {
      return {
        type: "matRimLightingLit",
        code: getShaderSource("matRimLightingLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matRimLightingFlat",
      code: getShaderSource("matRimLightingFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "AlphaMap") {
    if (useLighting && hasST) {
      return {
        type: "matAlphaMapLit",
        code: getShaderSource("matAlphaMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matAlphaMapFlat",
      code: getShaderSource("matAlphaMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "EmissionMap") {
    if (useLighting && hasST) {
      return {
        type: "matEmissionMapLit",
        code: getShaderSource("matEmissionMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matEmissionMapFlat",
      code: getShaderSource("matEmissionMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "SpecularMap") {
    if (useLighting && hasST) {
      return {
        type: "matSpecularMapLit",
        code: getShaderSource("matSpecularMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matSpecularMapFlat",
      code: getShaderSource("matSpecularMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "BumpMap") {
    if (useLighting && hasST) {
      return {
        type: "matBumpMapLit",
        code: getShaderSource("matBumpMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matBumpMapFlat",
      code: getShaderSource("matBumpMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "NormalMap") {
    if (useLighting && hasST) {
      return {
        type: "matNormalMapLit",
        code: getShaderSource("matNormalMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matNormalMapFlat",
      code: getShaderSource("matNormalMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "Water") {
    if (useLighting && hasST) {
      return {
        type: "matWaterLit",
        code: getShaderSource("matWaterLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matWaterFlat",
      code: getShaderSource("matWaterFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "ElevationContour") {
    if (useLighting && hasST) {
      return {
        type: "matElevContourLit",
        code: getShaderSource("matElevContourLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matElevContourFlat",
      code: getShaderSource("matElevContourFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "ElevationRamp") {
    if (useLighting && hasST) {
      return {
        type: "matElevRampLit",
        code: getShaderSource("matElevRampLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matElevRampFlat",
      code: getShaderSource("matElevRampFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "SlopeRamp") {
    if (useLighting && hasST) {
      return {
        type: "matSlopeRampLit",
        code: getShaderSource("matSlopeRampLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matSlopeRampFlat",
      code: getShaderSource("matSlopeRampFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "AspectRamp") {
    if (useLighting && hasST) {
      return {
        type: "matAspectRampLit",
        code: getShaderSource("matAspectRampLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matAspectRampFlat",
      code: getShaderSource("matAspectRampFlat"),
      needsTexture: true,
    };
  }

  // Color material (default)
  if (useLighting && hasST) {
    return {
      type: "matColorLit",
      code: getShaderSource("matColorLit"),
      needsTexture: false,
    };
  }
  return {
    type: "matColorFlat",
    code: getShaderSource("matColorFlat"),
    needsTexture: false,
  };
}

/**
 * Returns the vertex buffer layout for material shaders (no per-vertex color).
 * @param {string} shaderType - Material shader type
 * @returns {{ floatsPerVertex: number, stride: number, layout: GPUVertexBufferLayout }}
 * @private
 */
function getMaterialVertexLayout(shaderType) {
  // RTE: All layouts include positionHigh(3) + positionLow(3) at locations 0-1
  if (isMaterialLitShader(shaderType) || isPBRShader(shaderType)) {
    // posHigh(3) + posLow(3) + normal(3) + st(2) = 11 floats = 44 bytes
    return {
      floatsPerVertex: 11,
      stride: 44,
      layout: {
        arrayStride: 44,
        attributes: [
          { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
          { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
          { shaderLocation: 2, offset: 24, format: "float32x3" }, // normal
          { shaderLocation: 3, offset: 36, format: "float32x2" }, // texCoord
        ],
      },
    };
  }

  // Flat variants: posHigh(3) + posLow(3) + st(2) = 8 floats = 32 bytes
  return {
    floatsPerVertex: 8,
    stride: 32,
    layout: {
      arrayStride: 32,
      attributes: [
        { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
        { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
        { shaderLocation: 2, offset: 24, format: "float32x2" }, // texCoord
      ],
    },
  };
}

/**
 * Returns the uniform buffer size for material shaders (256-byte aligned).
 * @param {string} shaderType
 * @returns {number}
 * @private
 */
function getMaterialUniformSize(shaderType) {
  return 256;
}

/**
 * Returns true if a material shader type uses Phong lighting.
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isMaterialLitShader(shaderType) {
  return defined(shaderType) && shaderType.endsWith("Lit");
}

/**
 * Returns true if a shader type is a material shader (starts with "mat").
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isMaterialShader(shaderType) {
  return defined(shaderType) && shaderType.startsWith("mat");
}

/**
 * Returns true if a material shader needs a texture bind group (group 1).
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isMaterialTexturedShader(shaderType) {
  return (
    shaderType === "matImageFlat" ||
    shaderType === "matImageLit" ||
    shaderType === "matAlphaMapFlat" ||
    shaderType === "matAlphaMapLit" ||
    shaderType === "matEmissionMapFlat" ||
    shaderType === "matEmissionMapLit" ||
    shaderType === "matSpecularMapFlat" ||
    shaderType === "matSpecularMapLit" ||
    shaderType === "matBumpMapFlat" ||
    shaderType === "matBumpMapLit" ||
    shaderType === "matNormalMapFlat" ||
    shaderType === "matNormalMapLit" ||
    shaderType === "matWaterFlat" ||
    shaderType === "matWaterLit" ||
    shaderType === "matElevRampFlat" ||
    shaderType === "matElevRampLit" ||
    shaderType === "matSlopeRampFlat" ||
    shaderType === "matSlopeRampLit" ||
    shaderType === "matAspectRampFlat" ||
    shaderType === "matAspectRampLit"
  );
}

// =========================================================================
// PBR Shader Selection
// =========================================================================

/**
 * Returns true if a shader type is a PBR shader.
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isPBRShader(shaderType) {
  return shaderType === "pbrSimple" || shaderType === "pbrTextured";
}

/**
 * Returns true if a PBR shader needs a texture bind group (group 1).
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isPBRTexturedShader(shaderType) {
  return shaderType === "pbrTextured";
}

/**
 * Selects the appropriate PBR shader.
 * @param {boolean} hasBaseColorTexture - Whether a base color texture is available
 * @returns {{ type: string, code: string, needsTexture: boolean }}
 * @private
 */
function selectPBRShader(hasBaseColorTexture) {
  if (hasBaseColorTexture) {
    return {
      type: "pbrTextured",
      code: getShaderSource("pbrTextured"),
      needsTexture: true,
    };
  }
  return {
    type: "pbrSimple",
    code: getShaderSource("pbrSimple"),
    needsTexture: false,
  };
}

// =========================================================================
// Exports
// =========================================================================

const WebGPUPrimitiveShaders = {
  // Initialization
  initPrimitiveShaders,
  areShadersLoaded,
  getShaderSource,
  // Per-instance color
  selectWebGPUShader,
  getVertexLayoutForShader,
  getUniformSizeForShader,
  isPhongShader,
  isTexturedShader,
  // Pick
  getPickShaderForType,
  getMaterialPickShaderForType,
  getPickUniformSize,
  // Material
  selectMaterialShader,
  getMaterialVertexLayout,
  getMaterialUniformSize,
  isMaterialLitShader,
  isMaterialShader,
  isMaterialTexturedShader,
  // PBR
  isPBRShader,
  isPBRTexturedShader,
  selectPBRShader,
};

export default WebGPUPrimitiveShaders;
export {
  initPrimitiveShaders,
  areShadersLoaded,
  getShaderSource,
  selectWebGPUShader,
  getVertexLayoutForShader,
  getUniformSizeForShader,
  isPhongShader,
  isTexturedShader,
  getPickShaderForType,
  getMaterialPickShaderForType,
  getPickUniformSize,
  selectMaterialShader,
  getMaterialVertexLayout,
  getMaterialUniformSize,
  isMaterialLitShader,
  isMaterialShader,
  isMaterialTexturedShader,
  isPBRShader,
  isPBRTexturedShader,
  selectPBRShader,
};
