/**
 * Shader selection logic, vertex layout configuration, and uniform buffer sizing
 * for the WebGPU Primitive rendering pipeline.
 *
 * All WGSL shader source code is imported from pre-built JS modules under:
 *   Source/Shaders/WebGPU/Primitive/
 *
 * Each .wgsl file has a companion .js file (auto-generated by the build) that
 * exports the shader source as a string. This avoids runtime fetch() calls.
 *
 * @private
 * @module WebGPUPrimitiveShaders
 */
import defined from "../../Core/defined.js";

// Emit one warning per material type that lacks a compatible WGSL shader so
// long-running applications do not flood the console.
const _warnedMissingMaterial = new Set();
function _warnMissingMaterialOnce(materialType) {
  if (_warnedMissingMaterial.has(materialType)) {
    return;
  }
  _warnedMissingMaterial.add(materialType);
  //>>includeStart('debug', pragmas.debug);
  // The warned-about types are Polyline materials, whose collection-specific
  // vertex layout cannot be used by arbitrary primitives.
  console.warn(
    `[WebGPU:Primitive] Material type "${materialType}" is not supported on this pipeline — falling back to Color. ` +
      `${materialType} materials only render through PolylineCollection, not on arbitrary primitives — apply them to a PolylineCollection instead of setting Material.fromType("${materialType}") on a Box/Ellipsoid/etc.`,
  );
  //>>includeEnd('debug');
}

// =========================================================================
// Static shader imports — bundled by esbuild, no runtime fetch needed
// =========================================================================
import PrimitiveBasicColor from "../../Shaders/WebGPU/Primitive/PrimitiveBasicColor.js";
import PrimitivePhongColor from "../../Shaders/WebGPU/Primitive/PrimitivePhongColor.js";
import PrimitiveBasicTexturedColor from "../../Shaders/WebGPU/Primitive/PrimitiveBasicTexturedColor.js";
import PrimitivePhongTexturedColor from "../../Shaders/WebGPU/Primitive/PrimitivePhongTexturedColor.js";
import PrimitivePickBasic from "../../Shaders/WebGPU/Primitive/PrimitivePickBasic.js";
import PrimitivePickPhong from "../../Shaders/WebGPU/Primitive/PrimitivePickPhong.js";
import PrimitivePickBasicTextured from "../../Shaders/WebGPU/Primitive/PrimitivePickBasicTextured.js";
import PrimitivePickPhongTextured from "../../Shaders/WebGPU/Primitive/PrimitivePickPhongTextured.js";
import PrimitiveMatColorFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatColorFlat.js";
import PrimitiveMatColorLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatColorLit.js";
import PrimitiveMatImageFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatImageFlat.js";
import PrimitiveMatImageLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatImageLit.js";
import PrimitiveMatCheckerFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatCheckerFlat.js";
import PrimitiveMatCheckerLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatCheckerLit.js";
import PrimitiveMatGridFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatGridFlat.js";
import PrimitiveMatGridLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatGridLit.js";
import PrimitiveMatStripeFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatStripeFlat.js";
import PrimitiveMatStripeLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatStripeLit.js";
import PrimitiveMatDotFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatDotFlat.js";
import PrimitiveMatDotLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatDotLit.js";
import PrimitiveMatFadeFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatFadeFlat.js";
import PrimitiveMatFadeLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatFadeLit.js";
import PrimitiveMatRimLightingFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatRimLightingFlat.js";
import PrimitiveMatRimLightingLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatRimLightingLit.js";
import PrimitiveMatAlphaMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatAlphaMapFlat.js";
import PrimitiveMatAlphaMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatAlphaMapLit.js";
import PrimitiveMatEmissionMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatEmissionMapFlat.js";
import PrimitiveMatEmissionMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatEmissionMapLit.js";
import PrimitiveMatDiffuseMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatDiffuseMapFlat.js";
import PrimitiveMatDiffuseMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatDiffuseMapLit.js";
import PrimitiveMatSpecularMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatSpecularMapFlat.js";
import PrimitiveMatSpecularMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatSpecularMapLit.js";
import PrimitiveMatBumpMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatBumpMapFlat.js";
import PrimitiveMatBumpMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatBumpMapLit.js";
import PrimitiveMatNormalMapFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatNormalMapFlat.js";
import PrimitiveMatNormalMapLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatNormalMapLit.js";
import PrimitiveMatWaterFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatWaterFlat.js";
import PrimitiveMatWaterLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatWaterLit.js";
import PrimitiveMatElevBandFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatElevBandFlat.js";
import PrimitiveMatElevBandLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatElevBandLit.js";
import PrimitiveMatElevContourFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatElevContourFlat.js";
import PrimitiveMatElevContourLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatElevContourLit.js";
import PrimitiveMatElevRampFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatElevRampFlat.js";
import PrimitiveMatElevRampLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatElevRampLit.js";
import PrimitiveMatSlopeRampFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatSlopeRampFlat.js";
import PrimitiveMatSlopeRampLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatSlopeRampLit.js";
import PrimitiveMatAspectRampFlat from "../../Shaders/WebGPU/Primitive/PrimitiveMatAspectRampFlat.js";
import PrimitiveMatAspectRampLit from "../../Shaders/WebGPU/Primitive/PrimitiveMatAspectRampLit.js";
import PrimitivePickMatFlat from "../../Shaders/WebGPU/Primitive/PrimitivePickMatFlat.js";
import PrimitivePickMatLit from "../../Shaders/WebGPU/Primitive/PrimitivePickMatLit.js";
import PrimitivePBRSimple from "../../Shaders/WebGPU/Primitive/PrimitivePBRSimple.js";
import PrimitivePBRTextured from "../../Shaders/WebGPU/Primitive/PrimitivePBRTextured.js";
// This shader handles a `Primitive` with `PolylineColorAppearance` over a
// `PolylineGeometry`. It expands four coincident quad vertices into a screen-space
// ribbon via the ported PolylineCommon window-coordinate math.
import PolylineColorAppearance from "../../Shaders/WebGPU/Primitive/PolylineColorAppearance.js";
import csm_polylineCommon from "../../Shaders/WebGPU/chunks/functions/csm_polylineCommon.js";
// These shaders handle a `Primitive` with `PolylineMaterialAppearance` over
// a `PolylineGeometry`. The shared polyline VS (color VS minus per-vertex
// color, plus `st`) feeds a per-material-type FS (Color / Dash / Glow / Arrow /
// Outline). Each variant carries the same
// `// @chunk functions/csm_polylineCommon` marker, so getShaderSource prepends
// the (angle-capable) PolylineCommon functions.
import PolylineMatColor from "../../Shaders/WebGPU/Primitive/PolylineMatColor.js";
// Textured polyline materials add a group-2 texture and sampler that the other
// PolylineMat shaders do not use.
import PolylineMatImage from "../../Shaders/WebGPU/Primitive/PolylineMatImage.js";
import PolylineMatDash from "../../Shaders/WebGPU/Primitive/PolylineMatDash.js";
import PolylineMatGlow from "../../Shaders/WebGPU/Primitive/PolylineMatGlow.js";
import PolylineMatArrow from "../../Shaders/WebGPU/Primitive/PolylineMatArrow.js";
import PolylineMatOutline from "../../Shaders/WebGPU/Primitive/PolylineMatOutline.js";

// Point-light cube depth comparison is shared as a WGSL chunk. Shaders opt in
// with the `// @chunk csm_samplePointShadow` marker, avoiding copies of the
// dominant-axis perspective-depth and five-tap filtering implementation.
import csm_samplePointShadow from "../../Shaders/WebGPU/chunks/functions/csm_samplePointShadow.js";

// Splice chunks into a shader source if it carries the corresponding
// marker comment. WGSL doesn't have an `@include` directive of its own;
// this is the lightest-weight equivalent — markers stay benign comments
// when the chunk isn't injected (e.g., during isolated-shader testing),
// so the shader file remains a valid WGSL source on disk.
// Match the chunk directive anywhere in a comment line because generated WGSL
// may put explanatory text before it. Requiring a comment-line prefix prevents
// code and string literals from accidentally triggering injection.
const POINT_SHADOW_MARKER_REGEX = /^\s*\/\/.*@chunk\s+csm_samplePointShadow\b/m;
// PolylineColorAppearance.wgsl carries the PolylineCommon chunk
// directive; prepend the ported PolylineCommon window-coordinate functions
// when the marker is present. Same comment-only matching
// contract as the point-shadow marker.
const POLYLINE_COMMON_MARKER_REGEX =
  /^\s*\/\/.*@chunk\s+functions\/csm_polylineCommon\b/m;
function injectChunks(src) {
  if (typeof src !== "string") {
    return src;
  }
  let out = src;
  if (POINT_SHADOW_MARKER_REGEX.test(out)) {
    out = `${csm_samplePointShadow}\n${out}`;
  }
  if (POLYLINE_COMMON_MARKER_REGEX.test(out)) {
    out = `${csm_polylineCommon}\n${out}`;
  }
  return out;
}

// =========================================================================
// Shader Cache — populated synchronously from static imports
// =========================================================================

const _shaderCache = {
  // Per-instance color shaders
  basic: PrimitiveBasicColor,
  phong: PrimitivePhongColor,
  basicTextured: PrimitiveBasicTexturedColor,
  phongTextured: PrimitivePhongTexturedColor,
  // Pick shaders (per-instance color layouts)
  pickBasic: PrimitivePickBasic,
  pickPhong: PrimitivePickPhong,
  pickBasicTextured: PrimitivePickBasicTextured,
  pickPhongTextured: PrimitivePickPhongTextured,
  // Material shaders
  matColorFlat: PrimitiveMatColorFlat,
  matColorLit: PrimitiveMatColorLit,
  matImageFlat: PrimitiveMatImageFlat,
  matImageLit: PrimitiveMatImageLit,
  matCheckerFlat: PrimitiveMatCheckerFlat,
  matCheckerLit: PrimitiveMatCheckerLit,
  matGridFlat: PrimitiveMatGridFlat,
  matGridLit: PrimitiveMatGridLit,
  matStripeFlat: PrimitiveMatStripeFlat,
  matStripeLit: PrimitiveMatStripeLit,
  matDotFlat: PrimitiveMatDotFlat,
  matDotLit: PrimitiveMatDotLit,
  matFadeFlat: PrimitiveMatFadeFlat,
  matFadeLit: PrimitiveMatFadeLit,
  matRimLightingFlat: PrimitiveMatRimLightingFlat,
  matRimLightingLit: PrimitiveMatRimLightingLit,
  matAlphaMapFlat: PrimitiveMatAlphaMapFlat,
  matAlphaMapLit: PrimitiveMatAlphaMapLit,
  matEmissionMapFlat: PrimitiveMatEmissionMapFlat,
  matEmissionMapLit: PrimitiveMatEmissionMapLit,
  matDiffuseMapFlat: PrimitiveMatDiffuseMapFlat,
  matDiffuseMapLit: PrimitiveMatDiffuseMapLit,
  matSpecularMapFlat: PrimitiveMatSpecularMapFlat,
  matSpecularMapLit: PrimitiveMatSpecularMapLit,
  matBumpMapFlat: PrimitiveMatBumpMapFlat,
  matBumpMapLit: PrimitiveMatBumpMapLit,
  matNormalMapFlat: PrimitiveMatNormalMapFlat,
  matNormalMapLit: PrimitiveMatNormalMapLit,
  matWaterFlat: PrimitiveMatWaterFlat,
  matWaterLit: PrimitiveMatWaterLit,
  matElevBandFlat: PrimitiveMatElevBandFlat,
  matElevBandLit: PrimitiveMatElevBandLit,
  matElevContourFlat: PrimitiveMatElevContourFlat,
  matElevContourLit: PrimitiveMatElevContourLit,
  matElevRampFlat: PrimitiveMatElevRampFlat,
  matElevRampLit: PrimitiveMatElevRampLit,
  matSlopeRampFlat: PrimitiveMatSlopeRampFlat,
  matSlopeRampLit: PrimitiveMatSlopeRampLit,
  matAspectRampFlat: PrimitiveMatAspectRampFlat,
  matAspectRampLit: PrimitiveMatAspectRampLit,
  // Pick shaders (material layouts)
  pickMatFlat: PrimitivePickMatFlat,
  pickMatLit: PrimitivePickMatLit,
  // PBR shaders
  pbrSimple: PrimitivePBRSimple,
  pbrTextured: PrimitivePBRTextured,
  // Polyline color appearance
  polylineColor: PolylineColorAppearance,
  // Polyline material appearances
  polylineMatColor: PolylineMatColor,
  polylineMatImage: PolylineMatImage,
  polylineMatDash: PolylineMatDash,
  polylineMatGlow: PolylineMatGlow,
  polylineMatArrow: PolylineMatArrow,
  polylineMatOutline: PolylineMatOutline,
};

// Shaders are always available — no async loading needed
const _shadersLoaded = true;

// =========================================================================
// Shader Loading (kept for API compatibility, now a no-op)
// =========================================================================

/**
 * Initializes the primitive shader cache.
 * With static imports, this is a no-op — shaders are available immediately.
 * Kept for API compatibility with callers that expect an async init step.
 *
 * @returns {Promise<void>} Resolves immediately.
 * @private
 */
async function initPrimitiveShaders() {
  // No-op: shaders are statically imported and always available
  return;
}

/**
 * Returns the cached WGSL source for a shader key.
 *
 * @param {string} key - Shader key (e.g., 'basic', 'phong', 'matColorFlat', 'pbrSimple')
 * @returns {string} WGSL shader source code
 * @private
 */
function getShaderSource(key) {
  const source = _shaderCache[key];
  if (!defined(source)) {
    throw new Error(
      `[WebGPUPrimitiveShaders] Unknown shader key: "${key}". Available: ${Object.keys(_shaderCache).join(", ")}`,
    );
  }
  // Splice in chunks when the shader includes a marker comment. Cache the
  // result so repeated calls do not allocate; this is safe because
  // shader source strings are immutable once imported. Map (not WeakMap)
  // because keys are strings (primitives don't support WeakMap).
  if (!_chunkInjectedCache.has(source)) {
    _chunkInjectedCache.set(source, injectChunks(source));
  }
  return _chunkInjectedCache.get(source);
}

const _chunkInjectedCache = new Map();

/**
 * Returns true if the shader cache has been populated.
 * @returns {boolean}
 * @private
 */
function areShadersLoaded() {
  return _shadersLoaded;
}

// =========================================================================
// Per-Instance Color Shader Selection
// =========================================================================

/**
 * Determines which WGSL shader to use based on available geometry attributes.
 * Shader selection hierarchy:
 * - phongTextured: position + normal + st → Phong lighting + texture sampling
 * - basicTextured: position + st → Texture sampling + color
 * - phong: position + normal → Phong lighting + color
 * - basic: position → Color only
 *
 * @param {object} attributes - Geometry attributes
 * @returns {{ type: string, code: string, hasUV: boolean }} Shader type, WGSL code, and UV flag
 * @private
 */
function selectWebGPUShader(attributes) {
  const hasNormals =
    defined(attributes.normal) && defined(attributes.normal.values);
  const hasST = defined(attributes.st) && defined(attributes.st.values);

  if (hasNormals && hasST) {
    return {
      type: "phongTextured",
      code: getShaderSource("phongTextured"),
      hasUV: true,
    };
  }
  if (hasST) {
    return {
      type: "basicTextured",
      code: getShaderSource("basicTextured"),
      hasUV: true,
    };
  }
  if (hasNormals) {
    return { type: "phong", code: getShaderSource("phong"), hasUV: false };
  }
  return { type: "basic", code: getShaderSource("basic"), hasUV: false };
}

// =========================================================================
// Vertex Layout Configurations
// =========================================================================

/**
 * Returns the vertex buffer layout descriptor for a given shader type.
 *
 * @param {string} shaderType - Shader type identifier
 * @param {object} [options] - Optional layout modifiers (e.g. `compressedVertices`).
 * @returns {{ floatsPerVertex: number, stride: number, layout: GPUVertexBufferLayout }}
 * @private
 */
function getVertexLayoutForShader(shaderType, options) {
  const compressed = defined(options) && options.compressedVertices === true;

  // The compressed `phong` variant consumes one f32 at location 2 for the
  // octahedrally packed normal instead of
  // the plain `normal: vec3<f32>`. The compressed payload comes straight
  // from `compressedAttributes` (normal-only slot) without the CPU-side
  // octDecode expansion in `ensureUncompressedAttributes`. The material
  // shader must carry the matching `//>>ifdef COMPRESSED_VERTICES` block.
  if (compressed && shaderType === "phong") {
    // posHigh(3) + posLow(3) + compressedAttributes(1 f32) + color(4) = 11 floats = 44 bytes
    return {
      floatsPerVertex: 11,
      stride: 44,
      compressed: true,
      layout: {
        arrayStride: 44,
        attributes: [
          { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
          { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
          { shaderLocation: 2, offset: 24, format: "float32" }, // compressedAttributes (packed normal)
          { shaderLocation: 3, offset: 28, format: "float32x4" }, // color
        ],
      },
    };
  }

  // RTE: All layouts include positionHigh(3) + positionLow(3) at locations 0-1
  if (shaderType === "phongTextured") {
    // posHigh(3) + posLow(3) + normal(3) + uv(2) + color(4) = 15 floats = 60 bytes
    return {
      floatsPerVertex: 15,
      stride: 60,
      layout: {
        arrayStride: 60,
        attributes: [
          { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
          { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
          { shaderLocation: 2, offset: 24, format: "float32x3" }, // normal
          { shaderLocation: 3, offset: 36, format: "float32x2" }, // texCoord
          { shaderLocation: 4, offset: 44, format: "float32x4" }, // color
        ],
      },
    };
  }
  if (shaderType === "basicTextured") {
    // posHigh(3) + posLow(3) + uv(2) + color(4) = 12 floats = 48 bytes
    return {
      floatsPerVertex: 12,
      stride: 48,
      layout: {
        arrayStride: 48,
        attributes: [
          { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
          { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
          { shaderLocation: 2, offset: 24, format: "float32x2" }, // texCoord
          { shaderLocation: 3, offset: 32, format: "float32x4" }, // color
        ],
      },
    };
  }
  if (shaderType === "phong") {
    // posHigh(3) + posLow(3) + normal(3) + color(4) = 13 floats = 52 bytes
    return {
      floatsPerVertex: 13,
      stride: 52,
      layout: {
        arrayStride: 52,
        attributes: [
          { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
          { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
          { shaderLocation: 2, offset: 24, format: "float32x3" }, // normal
          { shaderLocation: 3, offset: 36, format: "float32x4" }, // color
        ],
      },
    };
  }
  // basic: posHigh(3) + posLow(3) + color(4) = 10 floats = 40 bytes
  return {
    floatsPerVertex: 10,
    stride: 40,
    layout: {
      arrayStride: 40,
      attributes: [
        { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
        { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
        { shaderLocation: 2, offset: 24, format: "float32x4" }, // color
      ],
    },
  };
}

/**
 * Returns the vertex layout for the polyline color-appearance shader. Its
 * original attributes occupy 96 bytes (24 floats):
 *   loc0 positionHigh   @0   (f32x3)
 *   loc1 positionLow    @12  (f32x3)
 *   loc2 prevPositionHigh @24 (f32x3)
 *   loc3 prevPositionLow  @36 (f32x3)
 *   loc4 nextPositionHigh @48 (f32x3)
 *   loc5 nextPositionLow  @60 (f32x3)
 *   loc6 expandAndWidth  @72  (f32x2)
 *   loc7 color           @80  (f32x4)
 * Byte-locked to the packer in WebGPUPrimitiveCommands.js and the
 * VertexInput in PolylineColorAppearance.wgsl.
 * @returns {{ floatsPerVertex: number, stride: number, layout: GPUVertexBufferLayout }}
 * @private
 */
function getPolylineAppearanceVertexLayout() {
  // Locations 8-13 carry projected positions for 2D, Columbus View, and morphing
  // (position2DHigh/Low + prev/next 2D) so the VS can blend 3D↔2D by morphTime.
  // Stride 96→168 (24→42 floats). In scene3DOnly mode these attrs are absent in
  // the geometry; the packer zero-fills them and morphTime stays 1.0 (3D path).
  return {
    floatsPerVertex: 42,
    stride: 168,
    layout: {
      arrayStride: 168,
      attributes: [
        { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
        { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
        { shaderLocation: 2, offset: 24, format: "float32x3" }, // prevPositionHigh
        { shaderLocation: 3, offset: 36, format: "float32x3" }, // prevPositionLow
        { shaderLocation: 4, offset: 48, format: "float32x3" }, // nextPositionHigh
        { shaderLocation: 5, offset: 60, format: "float32x3" }, // nextPositionLow
        { shaderLocation: 6, offset: 72, format: "float32x2" }, // expandAndWidth
        { shaderLocation: 7, offset: 80, format: "float32x4" }, // color
        { shaderLocation: 8, offset: 96, format: "float32x3" }, // position2DHigh
        { shaderLocation: 9, offset: 108, format: "float32x3" }, // position2DLow
        { shaderLocation: 10, offset: 120, format: "float32x3" }, // prevPosition2DHigh
        { shaderLocation: 11, offset: 132, format: "float32x3" }, // prevPosition2DLow
        { shaderLocation: 12, offset: 144, format: "float32x3" }, // nextPosition2DHigh
        { shaderLocation: 13, offset: 156, format: "float32x3" }, // nextPosition2DLow
      ],
    },
  };
}

/**
 * Selects the polyline-material fragment variant for a Cesium `Material`.
 * The shared polyline vertex shader
 * is the same across all variants; only the FS + MaterialUniforms struct
 * differ. PolylineDash / PolylineGlow / PolylineArrow / PolylineOutline route
 * to their dedicated WGSL; everything else (plain Color and any non-polyline
 * material reaching this path) falls back to the Color FS, mirroring WebGL's
 * default-Color fallthrough for unrecognized materials.
 *
 * @param {object} material - The CesiumJS Material (may be undefined).
 * @returns {{ type: string, code: string }} Shader type + WGSL source.
 * @private
 */
function selectPolylineMaterialShader(material) {
  const materialType = defined(material) ? material.type : "Color";
  if (materialType === "PolylineDash") {
    return {
      type: "polylineMatDash",
      code: getShaderSource("polylineMatDash"),
      needsTexture: false,
    };
  }
  if (materialType === "PolylineGlow") {
    return {
      type: "polylineMatGlow",
      code: getShaderSource("polylineMatGlow"),
      needsTexture: false,
    };
  }
  if (materialType === "PolylineArrow") {
    return {
      type: "polylineMatArrow",
      code: getShaderSource("polylineMatArrow"),
      needsTexture: false,
    };
  }
  if (materialType === "PolylineOutline") {
    return {
      type: "polylineMatOutline",
      code: getShaderSource("polylineMatOutline"),
      needsTexture: false,
    };
  }
  // Image samples a texture along the line using `st` and has
  // `{ repeat: vec2, color: vec4 }` plus its image texture. DiffuseMap has a
  // different uniform layout, so routing it through this shader would read
  // incompatible bytes; it falls through to the supported color material.
  if (materialType === "Image") {
    return {
      type: "polylineMatImage",
      code: getShaderSource("polylineMatImage"),
      needsTexture: true,
    };
  }
  // Color material (default) + any material without a dedicated polyline FS.
  return {
    type: "polylineMatColor",
    code: getShaderSource("polylineMatColor"),
    needsTexture: false,
  };
}

/**
 * Returns the vertex layout for the polyline-material shaders. It uses the
 * color-appearance attributes without `color`, plus
 * `st` (PolylineMaterialAppearance.VERTEX_FORMAT = POSITION_AND_ST). arrayStride
 * 88 = 22 floats:
 *   loc0 positionHigh     @0   (f32x3)
 *   loc1 positionLow      @12  (f32x3)
 *   loc2 prevPositionHigh @24  (f32x3)
 *   loc3 prevPositionLow  @36  (f32x3)
 *   loc4 nextPositionHigh @48  (f32x3)
 *   loc5 nextPositionLow  @60  (f32x3)
 *   loc6 expandAndWidth   @72  (f32x2)
 *   loc7 st               @80  (f32x2)
 * Byte-locked to the packer in WebGPUPrimitiveCommands.js and the VertexInput
 * in every PolylineMat*.wgsl.
 * @returns {{ floatsPerVertex: number, stride: number, layout: GPUVertexBufferLayout }}
 * @private
 */
function getPolylineMaterialVertexLayout() {
  // Locations 8-13 carry projected 2D positions; see the appearance layout.
  // Stride 88→160 (22→40 floats).
  return {
    floatsPerVertex: 40,
    stride: 160,
    layout: {
      arrayStride: 160,
      attributes: [
        { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
        { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
        { shaderLocation: 2, offset: 24, format: "float32x3" }, // prevPositionHigh
        { shaderLocation: 3, offset: 36, format: "float32x3" }, // prevPositionLow
        { shaderLocation: 4, offset: 48, format: "float32x3" }, // nextPositionHigh
        { shaderLocation: 5, offset: 60, format: "float32x3" }, // nextPositionLow
        { shaderLocation: 6, offset: 72, format: "float32x2" }, // expandAndWidth
        { shaderLocation: 7, offset: 80, format: "float32x2" }, // st
        { shaderLocation: 8, offset: 88, format: "float32x3" }, // position2DHigh
        { shaderLocation: 9, offset: 100, format: "float32x3" }, // position2DLow
        { shaderLocation: 10, offset: 112, format: "float32x3" }, // prevPosition2DHigh
        { shaderLocation: 11, offset: 124, format: "float32x3" }, // prevPosition2DLow
        { shaderLocation: 12, offset: 136, format: "float32x3" }, // nextPosition2DHigh
        { shaderLocation: 13, offset: 148, format: "float32x3" }, // nextPosition2DLow
      ],
    },
  };
}

/**
 * Returns the uniform buffer size for a given shader type (256-byte aligned).
 * @param {string} shaderType
 * @returns {number}
 * @private
 */
function getUniformSizeForShader(shaderType) {
  // All shader types use 256-byte uniform buffers
  return 256;
}

/**
 * Returns true if the shader type uses Phong lighting (needs normal matrix uniforms).
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isPhongShader(shaderType) {
  return shaderType === "phong" || shaderType === "phongTextured";
}

// This set identifies shader types with GPU-side compressed-vertex decode.
// Consult it at pipeline build time: if the geometry carries
// `compressedAttributes` AND the shader is in this set, route through the
// compressed vertex layout + set the `COMPRESSED_VERTICES` define on the
// shader module key. If the shader isn't in the set, fall back to the CPU
// decompression path in `ensureUncompressedAttributes`.
//
// Add-as-you-extend. Each addition requires:
//   1. A `//>>ifdef COMPRESSED_VERTICES` / `//>>else` block in the
//      shader's `struct VertexInput`.
//   2. Inline decode helpers (mirror of `csm_decodeCompressedVertex.wgsl`)
//      inside the same ifdef.
//   3. A compressed branch in `getVertexLayoutForShader` that emits the
//      narrower per-vertex stride.
const _SHADERS_WITH_GPU_DECODE = new Set(["phong"]);

/**
 * @param {string} shaderType
 * @returns {boolean} true when the shader declares `//>>ifdef COMPRESSED_VERTICES`
 *   blocks and a matching compressed layout in `getVertexLayoutForShader`.
 * @private
 */
function shaderSupportsCompressedVertices(shaderType) {
  return _SHADERS_WITH_GPU_DECODE.has(shaderType);
}

// GPU-side compressed-vertex decode is an intentionally disabled pilot whose
// shader coverage is currently limited to `phong`. Keep this flag, its setter,
// and the supported-shader set: the flag controls whether decode is attempted,
// while the set controls which shaders can use it. Until the pilot is enabled,
// `ensureUncompressedAttributes` remains the authoritative CPU path.
let _compressedVertexDecodeEnabled = false;

/**
 * @param {boolean} enabled
 * @private
 */
function setCompressedVertexDecodeEnabled(enabled) {
  _compressedVertexDecodeEnabled = enabled === true;
}

/**
 * @returns {boolean}
 * @private
 */
function isCompressedVertexDecodeEnabled() {
  return _compressedVertexDecodeEnabled;
}

/**
 * Returns true if the shader type needs a texture bind group (group 1).
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isTexturedShader(shaderType) {
  return shaderType === "basicTextured" || shaderType === "phongTextured";
}

// =========================================================================
// Pick Shader Selection
// =========================================================================

/**
 * Returns the WGSL pick shader code for a given color shader type.
 * @param {string} shaderType - Color shader type
 * @returns {string} WGSL pick shader source
 * @private
 */
function getPickShaderForType(shaderType) {
  if (shaderType === "phongTextured") {
    return getShaderSource("pickPhongTextured");
  }
  if (shaderType === "basicTextured") {
    return getShaderSource("pickBasicTextured");
  }
  if (shaderType === "phong") {
    return getShaderSource("pickPhong");
  }
  return getShaderSource("pickBasic");
}

/**
 * Returns the WGSL pick shader code for a material shader type.
 * @param {string} shaderType - Material shader type
 * @returns {string} WGSL pick shader source
 * @private
 */
function getMaterialPickShaderForType(shaderType) {
  if (isMaterialLitShader(shaderType) || isPBRShader(shaderType)) {
    return getShaderSource("pickMatLit");
  }
  return getShaderSource("pickMatFlat");
}

/**
 * Returns the uniform buffer size for pick shaders (256-byte aligned).
 * @returns {number}
 * @private
 */
function getPickUniformSize() {
  return 256;
}

// =========================================================================
// Material Shader Selection
// =========================================================================

/**
 * Determines which WGSL material shader to use based on material type and geometry attributes.
 *
 * @param {object} material - The CesiumJS Material object
 * @param {boolean} isFlat - Whether the appearance uses flat shading
 * @param {boolean} hasNormals - Whether the geometry has normals
 * @param {boolean} hasST - Whether the geometry has texture coordinates
 * @returns {{ type: string, code: string, needsTexture: boolean }} Shader info
 * @private
 */
function selectMaterialShader(material, isFlat, hasNormals, hasST) {
  const materialType = defined(material) ? material.type : "Color";
  const useLighting = hasNormals && !isFlat;

  if (materialType === "Image") {
    if (useLighting && hasST) {
      return {
        type: "matImageLit",
        code: getShaderSource("matImageLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matImageFlat",
      code: getShaderSource("matImageFlat"),
      needsTexture: true,
    };
  }

  // DiffuseMap needs its own shader pair because its fabric is
  // { channels:vec3, repeat:vec2 }, which does not match the Image shader's
  // { repeat:vec2, color:vec4 } MaterialUniforms struct. Sharing the Image
  // shader silently corrupted the UBO read (repeat read channels, color read
  // repeat+pad). See PrimitiveMatDiffuseMap{Flat,Lit}.wgsl.
  if (materialType === "DiffuseMap") {
    if (useLighting && hasST) {
      return {
        type: "matDiffuseMapLit",
        code: getShaderSource("matDiffuseMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matDiffuseMapFlat",
      code: getShaderSource("matDiffuseMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "Checkerboard") {
    if (useLighting && hasST) {
      return {
        type: "matCheckerLit",
        code: getShaderSource("matCheckerLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matCheckerFlat",
      code: getShaderSource("matCheckerFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "Grid") {
    if (useLighting && hasST) {
      return {
        type: "matGridLit",
        code: getShaderSource("matGridLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matGridFlat",
      code: getShaderSource("matGridFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "Stripe") {
    if (useLighting && hasST) {
      return {
        type: "matStripeLit",
        code: getShaderSource("matStripeLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matStripeFlat",
      code: getShaderSource("matStripeFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "Dot") {
    if (useLighting && hasST) {
      return {
        type: "matDotLit",
        code: getShaderSource("matDotLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matDotFlat",
      code: getShaderSource("matDotFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "Fade") {
    if (useLighting && hasST) {
      return {
        type: "matFadeLit",
        code: getShaderSource("matFadeLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matFadeFlat",
      code: getShaderSource("matFadeFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "RimLighting") {
    if (useLighting && hasST) {
      return {
        type: "matRimLightingLit",
        code: getShaderSource("matRimLightingLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matRimLightingFlat",
      code: getShaderSource("matRimLightingFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "AlphaMap") {
    if (useLighting && hasST) {
      return {
        type: "matAlphaMapLit",
        code: getShaderSource("matAlphaMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matAlphaMapFlat",
      code: getShaderSource("matAlphaMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "EmissionMap") {
    if (useLighting && hasST) {
      return {
        type: "matEmissionMapLit",
        code: getShaderSource("matEmissionMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matEmissionMapFlat",
      code: getShaderSource("matEmissionMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "SpecularMap") {
    if (useLighting && hasST) {
      return {
        type: "matSpecularMapLit",
        code: getShaderSource("matSpecularMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matSpecularMapFlat",
      code: getShaderSource("matSpecularMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "BumpMap") {
    if (useLighting && hasST) {
      return {
        type: "matBumpMapLit",
        code: getShaderSource("matBumpMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matBumpMapFlat",
      code: getShaderSource("matBumpMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "NormalMap") {
    if (useLighting && hasST) {
      return {
        type: "matNormalMapLit",
        code: getShaderSource("matNormalMapLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matNormalMapFlat",
      code: getShaderSource("matNormalMapFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "Water") {
    if (useLighting && hasST) {
      return {
        type: "matWaterLit",
        code: getShaderSource("matWaterLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matWaterFlat",
      code: getShaderSource("matWaterFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "ElevationContour") {
    if (useLighting && hasST) {
      return {
        type: "matElevContourLit",
        code: getShaderSource("matElevContourLit"),
        needsTexture: false,
      };
    }
    return {
      type: "matElevContourFlat",
      code: getShaderSource("matElevContourFlat"),
      needsTexture: false,
    };
  }

  if (materialType === "ElevationRamp") {
    if (useLighting && hasST) {
      return {
        type: "matElevRampLit",
        code: getShaderSource("matElevRampLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matElevRampFlat",
      code: getShaderSource("matElevRampFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "SlopeRamp") {
    if (useLighting && hasST) {
      return {
        type: "matSlopeRampLit",
        code: getShaderSource("matSlopeRampLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matSlopeRampFlat",
      code: getShaderSource("matSlopeRampFlat"),
      needsTexture: true,
    };
  }

  if (materialType === "AspectRamp") {
    if (useLighting && hasST) {
      return {
        type: "matAspectRampLit",
        code: getShaderSource("matAspectRampLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matAspectRampFlat",
      code: getShaderSource("matAspectRampFlat"),
      needsTexture: true,
    };
  }

  // ElevationBand uses dedicated WGSL shaders that perform a 16-step binary
  // search over a heights texture and color
  // ramp (see PrimitiveMatElevBandFlat.wgsl / PrimitiveMatElevBandLit.wgsl).
  // Its material texture bind group provides the two texture slots through
  // `_imageSources.heights` and `_imageSources.colors`.
  if (materialType === "ElevationBand") {
    if (useLighting && hasST) {
      return {
        type: "matElevBandLit",
        code: getShaderSource("matElevBandLit"),
        needsTexture: true,
      };
    }
    return {
      type: "matElevBandFlat",
      code: getShaderSource("matElevBandFlat"),
      needsTexture: true,
    };
  }

  // Diagnose material families that are unavailable on this pipeline.
  //
  //   Polyline* materials (Arrow, Dash, Glow, Outline) have WGSL
  //   implementations only for the Polyline COLLECTION renderer (see
  //   Shaders/WebGPU/Collections/Polyline*.wgsl). Their vertex layout is
  //   Polyline-specific — they can't be applied to arbitrary primitives
  //   through Material.fromType("PolylineGlow", ...) on a box or ellipsoid.
  //   Use the supported Color fallback and emit a one-time warning per
  //   material type so the incompatible integration point is visible.
  if (
    materialType === "PolylineArrow" ||
    materialType === "PolylineDash" ||
    materialType === "PolylineGlow" ||
    materialType === "PolylineOutline"
  ) {
    _warnMissingMaterialOnce(materialType);
    // Fall through to the Color default below. Single Color render
    // preserves the primitive's visible shape even though the fancy
    // material styling is lost.
  }

  // Color material (default)
  if (useLighting && hasST) {
    return {
      type: "matColorLit",
      code: getShaderSource("matColorLit"),
      needsTexture: false,
    };
  }
  return {
    type: "matColorFlat",
    code: getShaderSource("matColorFlat"),
    needsTexture: false,
  };
}

/**
 * Returns the vertex buffer layout for material shaders (no per-vertex color).
 * @param {string} shaderType - Material shader type
 * @returns {{ floatsPerVertex: number, stride: number, layout: GPUVertexBufferLayout }}
 * @private
 */
function getMaterialVertexLayout(shaderType) {
  // RTE: All layouts include positionHigh(3) + positionLow(3) at locations 0-1
  if (isMaterialLitShader(shaderType) || isPBRShader(shaderType)) {
    // posHigh(3) + posLow(3) + normal(3) + st(2) = 11 floats = 44 bytes
    return {
      floatsPerVertex: 11,
      stride: 44,
      layout: {
        arrayStride: 44,
        attributes: [
          { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
          { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
          { shaderLocation: 2, offset: 24, format: "float32x3" }, // normal
          { shaderLocation: 3, offset: 36, format: "float32x2" }, // texCoord
        ],
      },
    };
  }

  // Flat variants: posHigh(3) + posLow(3) + st(2) = 8 floats = 32 bytes
  return {
    floatsPerVertex: 8,
    stride: 32,
    layout: {
      arrayStride: 32,
      attributes: [
        { shaderLocation: 0, offset: 0, format: "float32x3" }, // positionHigh
        { shaderLocation: 1, offset: 12, format: "float32x3" }, // positionLow
        { shaderLocation: 2, offset: 24, format: "float32x2" }, // texCoord
      ],
    },
  };
}

/**
 * Returns the uniform buffer size for material shaders (256-byte aligned).
 * @param {string} shaderType
 * @returns {number}
 * @private
 */
function getMaterialUniformSize(shaderType) {
  return 256;
}

/**
 * Returns true if a material shader type uses Phong lighting.
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isMaterialLitShader(shaderType) {
  return defined(shaderType) && shaderType.endsWith("Lit");
}

/**
 * Returns true if a shader type is a material shader (starts with "mat").
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isMaterialShader(shaderType) {
  return defined(shaderType) && shaderType.startsWith("mat");
}

/**
 * Returns true if a material shader needs a texture bind group (group 1).
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isMaterialTexturedShader(shaderType) {
  return (
    shaderType === "matImageFlat" ||
    shaderType === "matImageLit" ||
    shaderType === "matAlphaMapFlat" ||
    shaderType === "matAlphaMapLit" ||
    shaderType === "matEmissionMapFlat" ||
    shaderType === "matEmissionMapLit" ||
    shaderType === "matDiffuseMapFlat" ||
    shaderType === "matDiffuseMapLit" ||
    shaderType === "matSpecularMapFlat" ||
    shaderType === "matSpecularMapLit" ||
    shaderType === "matBumpMapFlat" ||
    shaderType === "matBumpMapLit" ||
    shaderType === "matNormalMapFlat" ||
    shaderType === "matNormalMapLit" ||
    shaderType === "matWaterFlat" ||
    shaderType === "matWaterLit" ||
    shaderType === "matElevBandFlat" ||
    shaderType === "matElevBandLit" ||
    shaderType === "matElevRampFlat" ||
    shaderType === "matElevRampLit" ||
    shaderType === "matSlopeRampFlat" ||
    shaderType === "matSlopeRampLit" ||
    shaderType === "matAspectRampFlat" ||
    shaderType === "matAspectRampLit"
  );
}

// =========================================================================
// PBR Shader Selection
// =========================================================================

/**
 * Returns true if a shader type is a PBR shader.
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isPBRShader(shaderType) {
  return shaderType === "pbrSimple" || shaderType === "pbrTextured";
}

/**
 * Returns true if a PBR shader needs a texture bind group (group 1).
 * @param {string} shaderType
 * @returns {boolean}
 * @private
 */
function isPBRTexturedShader(shaderType) {
  return shaderType === "pbrTextured";
}

/**
 * Selects the appropriate PBR shader.
 * @param {boolean} hasBaseColorTexture - Whether a base color texture is available
 * @returns {{ type: string, code: string, needsTexture: boolean }}
 * @private
 */
function selectPBRShader(hasBaseColorTexture) {
  if (hasBaseColorTexture) {
    return {
      type: "pbrTextured",
      code: getShaderSource("pbrTextured"),
      needsTexture: true,
    };
  }
  return {
    type: "pbrSimple",
    code: getShaderSource("pbrSimple"),
    needsTexture: false,
  };
}

// =========================================================================
// Exports
// =========================================================================

const WebGPUPrimitiveShaders = {
  // Initialization
  initPrimitiveShaders,
  areShadersLoaded,
  getShaderSource,
  // Per-instance color
  selectWebGPUShader,
  getVertexLayoutForShader,
  getPolylineAppearanceVertexLayout,
  selectPolylineMaterialShader,
  getPolylineMaterialVertexLayout,
  getUniformSizeForShader,
  isPhongShader,
  isTexturedShader,
  shaderSupportsCompressedVertices,
  setCompressedVertexDecodeEnabled,
  isCompressedVertexDecodeEnabled,
  // Pick
  getPickShaderForType,
  getMaterialPickShaderForType,
  getPickUniformSize,
  // Material
  selectMaterialShader,
  getMaterialVertexLayout,
  getMaterialUniformSize,
  isMaterialLitShader,
  isMaterialShader,
  isMaterialTexturedShader,
  // PBR
  isPBRShader,
  isPBRTexturedShader,
  selectPBRShader,
};

export default WebGPUPrimitiveShaders;
export {
  initPrimitiveShaders,
  areShadersLoaded,
  getShaderSource,
  selectWebGPUShader,
  getVertexLayoutForShader,
  getPolylineAppearanceVertexLayout,
  selectPolylineMaterialShader,
  getPolylineMaterialVertexLayout,
  getUniformSizeForShader,
  isPhongShader,
  isTexturedShader,
  shaderSupportsCompressedVertices,
  setCompressedVertexDecodeEnabled,
  isCompressedVertexDecodeEnabled,
  getPickShaderForType,
  getMaterialPickShaderForType,
  getPickUniformSize,
  selectMaterialShader,
  getMaterialVertexLayout,
  getMaterialUniformSize,
  isMaterialLitShader,
  isMaterialShader,
  isMaterialTexturedShader,
  isPBRShader,
  isPBRTexturedShader,
  selectPBRShader,
};
