/**
 * @module WebGPUVolumetricFogRenderer
 *
 * **Phase 5a infrastructure** for the celestial atmosphere design's
 * froxel-grid participating media renderer (`CELESTIAL_ATMOSPHERE_DESIGN.md`
 * §4.8). Allocates the 3D texture pair (density + scattered light + integrated
 * volume), creates compute pipelines for the three Frostbite-style passes
 * (density injection, light scattering, ray-march integration), and
 * runs a final full-screen composite pass that samples the integrated
 * volume in screen UV + linearized depth and modulates the scene color.
 *
 * Phase 5a contract — **no visual change**. The compute kernels in
 * `VolumetricFog.wgsl` are placeholders that clear their output
 * textures to zero (or `(0, 0, 0, 1)` for the integrated volume so
 * `transmittance = 1`). The composite pass samples the cleared volume
 * and applies `out = sceneColor * 1 + 0 = sceneColor`. Phase 5b/5c/5d
 * fill in the actual density / scattering / integration math without
 * touching this scaffolding.
 *
 * Architecture:
 *   1. `update(context, frameState, scene)` — runs the three compute
 *      passes once per frame when `enableVolumetricFog` is true.
 *      Allocates GPU resources lazily on first call.
 *   2. `composite(context, frameState, colorView, depthView, outputView)` —
 *      runs the full-screen composite pass that samples the integrated
 *      volume and writes the modulated scene color to the output view.
 *      Wired into `WebGPUSceneRenderer._executeEnvironmentalEffects()`
 *      after procedural clouds / SSR / weather particles, before
 *      post-processing (matches B22 placement).
 *
 * Resource budget (medium quality, 160×90×128 = 1.8M froxels):
 *   - 2 × rgba16float 3D textures @ 1.8M voxels × 8 bytes = ~28 MB each
 *   - 1 × rgba16float 3D integrated volume = ~28 MB
 *   - Total: ~84 MB
 *
 * Quality bands:
 *   low    →  80 ×  45 ×  64  ≈  230K froxels  ≈  11 MB
 *   medium → 160 ×  90 × 128  ≈  1.8M froxels  ≈  84 MB
 *   high   → 240 × 135 × 192  ≈  6.2M froxels  ≈  300 MB
 *
 * The `auto` setting picks one of the above based on the
 * VisualPerformanceTargetService's init benchmark (B7/B17 lock).
 */

/// <reference types="@webgpu/types" />

import Matrix4 from "../../Core/Matrix4.js";

// Scratch matrices for the per-frame inverse view-projection
// composition. The kernels need invVP for screen UV → world ray
// reconstruction; we compose `view × projection` then invert when the
// camera doesn't already cache the result.
const _scratchVP = new Matrix4();
const _scratchInvVP = new Matrix4();

// WGSL sources — auto-generated by `gulp build` via wgslToJavaScript.
import VolumetricFogComputeSource from "../../Shaders/WebGPU/Compute/VolumetricFog.js";
import VolumetricFogCompositeSource from "../../Shaders/WebGPU/PostProcess/VolumetricFogComposite.js";

/** Quality preset → 3D texture resolution mapping (W × H × D). */
const QUALITY_RESOLUTIONS = {
  low: { width: 80, height: 45, depth: 64 },
  medium: { width: 160, height: 90, depth: 128 },
  high: { width: 240, height: 135, depth: 192 },
} as const;

type QualityKey = keyof typeof QUALITY_RESOLUTIONS;

/** Number of floats in the VolumetricFogParams uniform buffer.
 *  Phase 5d layout (64 floats, 256 bytes):
 *    0..3   resolution (uint xyzw)
 *    4..7   scattering (near, maxDist, density, falloff)
 *    8..11  albedo + anisotropy
 *    12..27 invViewProj (mat4)
 *    28..43 sunShadowMatrix (mat4)
 *    44..47 cameraXYZ + innerRadius
 *    48..51 sunDirXYZ + sunIntensity
 *    52..55 moonDirXYZ + moonPhase × moonIntensity
 *    56..59 occlusion (enableScatteringOcclusion, ambientStrength,
 *                      shadowMapValid, shadowDarkness)
 *    60..63 noise (enableVaryingDensity, noiseScale, noiseStrength, _pad)
 */
const VOLUMETRIC_FOG_PARAMS_FLOATS = 64;
const VOLUMETRIC_FOG_PARAMS_BYTES = VOLUMETRIC_FOG_PARAMS_FLOATS * 4;

/** CompositeUniforms float count: mat4 (16) + 2 × vec4 (8) = 24 floats. */
const COMPOSITE_UNIFORMS_FLOATS = 24;
const COMPOSITE_UNIFORMS_BYTES = COMPOSITE_UNIFORMS_FLOATS * 4;

/**
 * GPU resources owned by one VolumetricFog renderer instance. Allocated
 * lazily on first `update()` call and rebuilt when the resolution band
 * changes (quality preset switch or VPT auto-tune).
 */
interface VolumetricFogResources {
  // Resolution band currently allocated. Used to detect quality changes.
  resolutionKey: QualityKey;
  width: number;
  height: number;
  depth: number;

  // 3D textures.
  densityTexture: GPUTexture;
  densityView: GPUTextureView;
  scatteringTexture: GPUTexture;
  scatteringView: GPUTextureView;
  integratedTexture: GPUTexture;
  integratedView: GPUTextureView;
  // Sampling view (filterable) for the composite pass — same texture
  // as `integratedView` but created with default usage so the composite
  // shader can sample it.
  integratedSampleView: GPUTextureView;

  // Compute pipelines — one per pass. Phase 5b uses three distinct
  // bind group layouts (and matching pipeline layouts) because the
  // density / scattering / integrate passes have different read-vs-write
  // texture access patterns and WGSL doesn't permit aliasing the same
  // `@binding` slot across access modes.
  computeShaderModule: GPUShaderModule;
  densityBindGroupLayout: GPUBindGroupLayout;
  densityPipeline: GPUComputePipeline;
  densityBindGroup: GPUBindGroup;
  scatteringBindGroupLayout: GPUBindGroupLayout;
  scatteringPipeline: GPUComputePipeline;
  // Phase 5c: scattering bind group is rebuilt when the bound sun
  // shadow map view changes (initially the placeholder, then the real
  // map once a shadow-casting sun is active).
  scatteringBindGroup: GPUBindGroup;
  scatteringBoundShadowView: GPUTextureView | null;
  integrateBindGroupLayout: GPUBindGroupLayout;
  integratePipeline: GPUComputePipeline;
  integrateBindGroup: GPUBindGroup;

  // Phase 5c — sun shadow map placeholder + comparison sampler.
  // The placeholder is a 1×1 depth32float texture cleared to 1.0
  // (max depth = "fully lit"). When a real shadow map is bound the
  // scattering bind group is rebuilt to point at it; the placeholder
  // stays around for the fallback path.
  shadowPlaceholderTexture: GPUTexture;
  shadowPlaceholderView: GPUTextureView;
  shadowComparisonSampler: GPUSampler;

  // Params uniform for the compute passes.
  paramsBuffer: GPUBuffer;
  paramsData: Float32Array;
  paramsU32: Uint32Array;

  // Composite pass resources.
  compositeShaderModule: GPUShaderModule;
  compositeBindGroupLayout: GPUBindGroupLayout;
  compositePipeline: GPURenderPipeline;
  compositeUniformBuffer: GPUBuffer;
  compositeUniformData: Float32Array;
  compositeSampler: GPUSampler;
  // Composite bind group — recreated when the input scene color/depth
  // texture views change (e.g., on resize). Cached on the bind group
  // build site to avoid every-frame allocation.
  compositeBindGroup: GPUBindGroup | null;
  compositeBoundColorView: GPUTextureView | null;
  compositeBoundDepthView: GPUTextureView | null;
  compositeBoundOutputFormat: GPUTextureFormat | null;
}

/**
 * Per-context state for the volumetric fog renderer. The feature
 * renderer creates one of these on first invocation and reuses it for
 * the lifetime of the GraphicsContext.
 */
class WebGPUVolumetricFogRenderer {
  private _device: GPUDevice;
  private _resources: VolumetricFogResources | null = null;
  private _isDestroyed = false;
  // Phase 6 audit fix — snapshot mode coordination state. The freezable
  // is registered on the scene's SnapshotModeService once on first
  // sight; it just toggles `_frozen`, which the per-frame `update()`
  // checks to skip the compute passes entirely. The service reference
  // is stashed so `destroy()` can unregister cleanly.
  private _frozen = false;
  private _snapshotRegistered = false;
  private _snapshotService: any = null;
  // Phase 6 debug surface — frame counters split between "compute
  // dispatched" and "skipped because frozen". Cheap to maintain and
  // tells the operator at a glance whether snapshot mode is biting.
  private _updatesDispatched = 0;
  private _updatesSkippedFrozen = 0;
  private _composites = 0;
  private _lastEnabled = false;

  constructor(device: GPUDevice) {
    this._device = device;
  }

  /**
   * Returns a SnapshotFreezable-shaped object suitable for passing to
   * `SnapshotModeService.registerFreezable()`. Mirrors the pattern used
   * by `WebGPURenderBundleManager.asFreezable()` so the registration
   * site is symmetric and the spec layer can drive the contract
   * without faking out a GPU device.
   */
  asFreezable(): {
    name: string;
    freeze: () => void;
    thaw: () => void;
    isFrozen: () => boolean;
  } {
    return {
      name: "webgpu-volumetric-fog",
      freeze: () => {
        this._frozen = true;
      },
      thaw: () => {
        this._frozen = false;
      },
      isFrozen: () => this._frozen,
    };
  }

  /**
   * Diagnostic snapshot for the central debug surface
   * (`Scene.getDebugSnapshot()`). Pure read; safe to call any time.
   */
  getStatistics(): {
    enabled: boolean;
    frozen: boolean;
    snapshotRegistered: boolean;
    destroyed: boolean;
    resolutionKey: string | null;
    dimensions: { width: number; height: number; depth: number } | null;
    updatesDispatched: number;
    updatesSkippedFrozen: number;
    composites: number;
  } {
    const r = this._resources;
    return {
      enabled: this._lastEnabled,
      frozen: this._frozen,
      snapshotRegistered: this._snapshotRegistered,
      destroyed: this._isDestroyed,
      resolutionKey: r ? r.resolutionKey : null,
      dimensions: r
        ? { width: r.width, height: r.height, depth: r.depth }
        : null,
      updatesDispatched: this._updatesDispatched,
      updatesSkippedFrozen: this._updatesSkippedFrozen,
      composites: this._composites,
    };
  }

  /**
   * Resolve the active quality band from `atmosphericConditions.volumetricFog.quality`.
   * "auto" maps to "low" until the VisualPerformanceTargetService wires
   * its init benchmark in (Phase 0.4 skeleton; benchmark is a future
   * follow-up).
   */
  private _resolveQuality(quality: string | undefined): QualityKey {
    if (quality === "high" || quality === "medium" || quality === "low") {
      return quality;
    }
    // "auto" or unknown → conservative default. The VPT auto-tune is
    // designed to UPGRADE this from low to medium on capable hardware
    // (or downgrade if frame budget is exceeded), but the benchmark
    // hookup is queued behind Phase 5b's actual rendering work — there's
    // nothing to measure until the compute kernels do real work.
    return "low";
  }

  /**
   * Lazy-create or rebuild the GPU resources. Called from `update()` on
   * the first frame and whenever the quality band changes. Idempotent.
   */
  private _ensureResources(quality: QualityKey): VolumetricFogResources {
    if (this._resources && this._resources.resolutionKey === quality) {
      return this._resources;
    }
    // Quality changed (or first allocation) — destroy any existing
    // textures + pipelines and rebuild from scratch. Pipeline layouts
    // can stay constant because they don't depend on resolution, but
    // we tear them down too for a clean reset path.
    if (this._resources) {
      this._destroyResources();
    }

    const dims = QUALITY_RESOLUTIONS[quality];
    const device = this._device;

    // ── 3D textures ──
    // STORAGE_BINDING for the compute write target; TEXTURE_BINDING for
    // the composite shader sample. Both bits are core WebGPU; no
    // optional features required.
    const usage =
      GPUTextureUsage.STORAGE_BINDING | GPUTextureUsage.TEXTURE_BINDING;

    const densityTexture = device.createTexture({
      label: "VolumetricFog_Density",
      size: {
        width: dims.width,
        height: dims.height,
        depthOrArrayLayers: dims.depth,
      },
      format: "rgba16float",
      dimension: "3d",
      usage,
    });
    const scatteringTexture = device.createTexture({
      label: "VolumetricFog_Scattering",
      size: {
        width: dims.width,
        height: dims.height,
        depthOrArrayLayers: dims.depth,
      },
      format: "rgba16float",
      dimension: "3d",
      usage,
    });
    const integratedTexture = device.createTexture({
      label: "VolumetricFog_Integrated",
      size: {
        width: dims.width,
        height: dims.height,
        depthOrArrayLayers: dims.depth,
      },
      format: "rgba16float",
      dimension: "3d",
      usage,
    });

    const densityView = densityTexture.createView({
      label: "VolumetricFog_Density_View",
      dimension: "3d",
    });
    const scatteringView = scatteringTexture.createView({
      label: "VolumetricFog_Scattering_View",
      dimension: "3d",
    });
    const integratedView = integratedTexture.createView({
      label: "VolumetricFog_Integrated_View",
      dimension: "3d",
    });
    const integratedSampleView = integratedTexture.createView({
      label: "VolumetricFog_Integrated_SampleView",
      dimension: "3d",
    });

    // ── Compute shader module + per-pass pipelines ──
    // Phase 5b uses one shader module containing all three entry points
    // and disjoint @binding numbers so we can declare write/read access
    // for the SAME texture without WGSL `@binding` collisions. Each
    // pipeline gets its own BGL containing only the bindings its entry
    // point references; WebGPU validates per-entry-point.
    const computeShaderModule = device.createShaderModule({
      label: "VolumetricFog_Compute",
      code: VolumetricFogComputeSource,
    });

    // Helper for the storage texture entries — same shape repeated.
    const writeStorageEntry = {
      access: "write-only" as GPUStorageTextureAccess,
      format: "rgba16float" as GPUTextureFormat,
      viewDimension: "3d" as GPUTextureViewDimension,
    };
    const readStorageEntry = {
      access: "read-only" as GPUStorageTextureAccess,
      format: "rgba16float" as GPUTextureFormat,
      viewDimension: "3d" as GPUTextureViewDimension,
    };

    const densityBindGroupLayout = device.createBindGroupLayout({
      label: "VolumetricFog_DensityBGL",
      entries: [
        {
          binding: 0,
          visibility: GPUShaderStage.COMPUTE,
          buffer: { type: "uniform" },
        },
        {
          binding: 1,
          visibility: GPUShaderStage.COMPUTE,
          storageTexture: writeStorageEntry,
        },
      ],
    });

    const scatteringBindGroupLayout = device.createBindGroupLayout({
      label: "VolumetricFog_ScatteringBGL",
      entries: [
        {
          binding: 0,
          visibility: GPUShaderStage.COMPUTE,
          buffer: { type: "uniform" },
        },
        {
          binding: 2,
          visibility: GPUShaderStage.COMPUTE,
          storageTexture: readStorageEntry,
        },
        {
          binding: 3,
          visibility: GPUShaderStage.COMPUTE,
          storageTexture: writeStorageEntry,
        },
        // Phase 5c — sun shadow map (depth texture + comparison sampler).
        {
          binding: 6,
          visibility: GPUShaderStage.COMPUTE,
          texture: { sampleType: "depth", viewDimension: "2d" },
        },
        {
          binding: 7,
          visibility: GPUShaderStage.COMPUTE,
          sampler: { type: "comparison" },
        },
      ],
    });

    const integrateBindGroupLayout = device.createBindGroupLayout({
      label: "VolumetricFog_IntegrateBGL",
      entries: [
        {
          binding: 0,
          visibility: GPUShaderStage.COMPUTE,
          buffer: { type: "uniform" },
        },
        {
          binding: 4,
          visibility: GPUShaderStage.COMPUTE,
          storageTexture: readStorageEntry,
        },
        {
          binding: 5,
          visibility: GPUShaderStage.COMPUTE,
          storageTexture: writeStorageEntry,
        },
      ],
    });

    const densityPipeline = device.createComputePipeline({
      label: "VolumetricFog_DensityPipeline",
      layout: device.createPipelineLayout({
        bindGroupLayouts: [densityBindGroupLayout],
      }),
      compute: { module: computeShaderModule, entryPoint: "densityInjection" },
    });
    const scatteringPipeline = device.createComputePipeline({
      label: "VolumetricFog_ScatteringPipeline",
      layout: device.createPipelineLayout({
        bindGroupLayouts: [scatteringBindGroupLayout],
      }),
      compute: { module: computeShaderModule, entryPoint: "lightScattering" },
    });
    const integratePipeline = device.createComputePipeline({
      label: "VolumetricFog_IntegratePipeline",
      layout: device.createPipelineLayout({
        bindGroupLayouts: [integrateBindGroupLayout],
      }),
      compute: { module: computeShaderModule, entryPoint: "integrate" },
    });

    // ── Params UBO ──
    const paramsData = new Float32Array(VOLUMETRIC_FOG_PARAMS_FLOATS);
    const paramsU32 = new Uint32Array(
      paramsData.buffer,
      paramsData.byteOffset,
      paramsData.length,
    );
    const paramsBuffer = device.createBuffer({
      label: "VolumetricFog_Params",
      size: Math.max(VOLUMETRIC_FOG_PARAMS_BYTES, 256),
      usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,
    });

    const densityBindGroup = device.createBindGroup({
      label: "VolumetricFog_DensityBindGroup",
      layout: densityBindGroupLayout,
      entries: [
        { binding: 0, resource: { buffer: paramsBuffer } },
        { binding: 1, resource: densityView },
      ],
    });

    // Phase 5c — sun shadow placeholder. 1×1 depth texture cleared to
    // 1.0 (= "fully lit" for the comparison sampler — no shadow). Stays
    // bound when no real sun shadow map is active so the kernel's
    // texture sample never tries to read an unbound texture.
    const shadowPlaceholderTexture = device.createTexture({
      label: "VolumetricFog_ShadowPlaceholder",
      size: { width: 1, height: 1 },
      format: "depth32float",
      usage:
        GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.RENDER_ATTACHMENT,
    });
    // We can't initialize a depth texture via writeBuffer; instead, use
    // a one-shot render pass that clears it to 1.0.
    {
      const initEncoder = device.createCommandEncoder({
        label: "VolumetricFog_ShadowPlaceholder_Init",
      });
      const initPass = initEncoder.beginRenderPass({
        label: "VolumetricFog_ShadowPlaceholder_Clear",
        colorAttachments: [],
        depthStencilAttachment: {
          view: shadowPlaceholderTexture.createView(),
          depthLoadOp: "clear",
          depthClearValue: 1.0,
          depthStoreOp: "store",
        },
      });
      initPass.end();
      device.queue.submit([initEncoder.finish()]);
    }
    const shadowPlaceholderView = shadowPlaceholderTexture.createView({
      label: "VolumetricFog_ShadowPlaceholder_View",
    });
    const shadowComparisonSampler = device.createSampler({
      label: "VolumetricFog_ShadowComparisonSampler",
      compare: "less-equal",
      magFilter: "linear",
      minFilter: "linear",
      addressModeU: "clamp-to-edge",
      addressModeV: "clamp-to-edge",
    });

    const scatteringBindGroup = device.createBindGroup({
      label: "VolumetricFog_ScatteringBindGroup",
      layout: scatteringBindGroupLayout,
      entries: [
        { binding: 0, resource: { buffer: paramsBuffer } },
        { binding: 2, resource: densityView },
        { binding: 3, resource: scatteringView },
        { binding: 6, resource: shadowPlaceholderView },
        { binding: 7, resource: shadowComparisonSampler },
      ],
    });

    const integrateBindGroup = device.createBindGroup({
      label: "VolumetricFog_IntegrateBindGroup",
      layout: integrateBindGroupLayout,
      entries: [
        { binding: 0, resource: { buffer: paramsBuffer } },
        { binding: 4, resource: scatteringView },
        { binding: 5, resource: integratedView },
      ],
    });

    // ── Composite pass resources ──
    const compositeShaderModule = device.createShaderModule({
      label: "VolumetricFog_Composite",
      code: VolumetricFogCompositeSource,
    });

    const compositeBindGroupLayout = device.createBindGroupLayout({
      label: "VolumetricFog_CompositeBGL",
      entries: [
        {
          binding: 0,
          visibility: GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT,
          buffer: { type: "uniform" },
        },
        {
          binding: 1,
          visibility: GPUShaderStage.FRAGMENT,
          sampler: { type: "filtering" },
        },
        {
          binding: 2,
          visibility: GPUShaderStage.FRAGMENT,
          texture: { sampleType: "float", viewDimension: "2d" },
        },
        {
          binding: 3,
          visibility: GPUShaderStage.FRAGMENT,
          texture: { sampleType: "depth", viewDimension: "2d" },
        },
        {
          binding: 4,
          visibility: GPUShaderStage.FRAGMENT,
          texture: { sampleType: "float", viewDimension: "3d" },
        },
      ],
    });

    const compositePipelineLayout = device.createPipelineLayout({
      label: "VolumetricFog_CompositePipelineLayout",
      bindGroupLayouts: [compositeBindGroupLayout],
    });

    const compositePipeline = device.createRenderPipeline({
      label: "VolumetricFog_CompositePipeline",
      layout: compositePipelineLayout,
      vertex: { module: compositeShaderModule, entryPoint: "vertexMain" },
      fragment: {
        module: compositeShaderModule,
        entryPoint: "fragmentMain",
        // The output format gets set when the bind group is built
        // (we don't know it at allocation time). The pipeline is
        // created with `bgra8unorm` as a placeholder; the real format
        // is verified at composite() call time.
        targets: [{ format: "bgra8unorm" }],
      },
      primitive: { topology: "triangle-list" },
    });

    const compositeUniformData = new Float32Array(COMPOSITE_UNIFORMS_FLOATS);
    const compositeUniformBuffer = device.createBuffer({
      label: "VolumetricFog_CompositeUniforms",
      size: Math.max(COMPOSITE_UNIFORMS_BYTES, 256),
      usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,
    });

    const compositeSampler = device.createSampler({
      label: "VolumetricFog_CompositeSampler",
      magFilter: "linear",
      minFilter: "linear",
      addressModeU: "clamp-to-edge",
      addressModeV: "clamp-to-edge",
      addressModeW: "clamp-to-edge",
    });

    this._resources = {
      resolutionKey: quality,
      width: dims.width,
      height: dims.height,
      depth: dims.depth,
      densityTexture,
      densityView,
      scatteringTexture,
      scatteringView,
      integratedTexture,
      integratedView,
      integratedSampleView,
      computeShaderModule,
      densityBindGroupLayout,
      densityPipeline,
      densityBindGroup,
      scatteringBindGroupLayout,
      scatteringPipeline,
      scatteringBindGroup,
      scatteringBoundShadowView: shadowPlaceholderView,
      integrateBindGroupLayout,
      integratePipeline,
      integrateBindGroup,
      shadowPlaceholderTexture,
      shadowPlaceholderView,
      shadowComparisonSampler,
      paramsBuffer,
      paramsData,
      paramsU32,
      compositeShaderModule,
      compositeBindGroupLayout,
      compositePipeline,
      compositeUniformBuffer,
      compositeUniformData,
      compositeSampler,
      compositeBindGroup: null,
      compositeBoundColorView: null,
      compositeBoundDepthView: null,
      compositeBoundOutputFormat: null,
    };
    return this._resources;
  }

  private _destroyResources(): void {
    if (!this._resources) return;
    const r = this._resources;
    r.densityTexture.destroy();
    r.scatteringTexture.destroy();
    r.integratedTexture.destroy();
    r.shadowPlaceholderTexture.destroy();
    r.paramsBuffer.destroy();
    r.compositeUniformBuffer.destroy();
    this._resources = null;
  }

  /**
   * Run the three compute passes for one frame. No-op when
   * `enableVolumetricFog` is off — caller is responsible for the
   * top-level toggle check, but we double-check here as defense in
   * depth.
   *
   * Phase 5a: dispatches the placeholder kernels that clear their
   * outputs. Phase 5b/5c populate density / scattering / integration
   * with real math.
   */
  update(context: CesiumGraphicsContext, frameState: CesiumFrameState, scene: CesiumScene): void {
    if (this._isDestroyed) return;
    const _scene = scene;
    const ac = frameState.atmosphericConditions;
    const vf = ac && ac.volumetricFog ? ac.volumetricFog : undefined;
    if (!vf || vf.enabled !== true) {
      this._lastEnabled = false;
      return;
    }
    this._lastEnabled = true;

    const device: GPUDevice = context.device;
    if (!device) return;

    const quality = this._resolveQuality(vf.quality);
    const r = this._ensureResources(quality);

    // Phase 6 audit fix — snapshot mode integration. When the snapshot
    // service has frozen the scene, the integrated 3D volume from the
    // previous frame is still visually correct (the camera is locked,
    // sun direction is locked, density field is unchanged). Skipping
    // the three compute dispatches saves ~2.7ms/frame at medium
    // resolution and is the entire reason snapshot mode exists.
    //
    // Late-registration pattern: each context's fog instance registers
    // its freezable on first sight. The freezable just toggles the
    // local `_frozen` flag — there's no separate cache to invalidate
    // because the integrated texture IS the cache.
    if (!this._snapshotRegistered && scene && scene.snapshotMode) {
      // Use asFreezable() so the registered closure matches the
      // direct-API path the spec layer drives.
      scene.snapshotMode.registerFreezable(
        "webgpu-volumetric-fog",
        this.asFreezable(),
      );
      this._snapshotRegistered = true;
      this._snapshotService = scene.snapshotMode;
    }
    if (this._frozen) {
      // Skip all three compute passes — last frame's integrated
      // volume is still bound and the composite pass will sample it.
      this._updatesSkippedFrozen++;
      return;
    }
    this._updatesDispatched++;

    // ── Pack params UBO ──
    // Resolution.
    r.paramsU32[0] = r.width;
    r.paramsU32[1] = r.height;
    r.paramsU32[2] = r.depth;
    r.paramsU32[3] = 0;
    // Scattering params.
    r.paramsData[4] = frameState.camera?.frustum?.near ?? 1.0;
    r.paramsData[5] = vf.maxDistance ?? 50000;
    r.paramsData[6] = vf.density ?? 1.0;
    r.paramsData[7] = vf.falloff ?? 0.0001;
    // Albedo + anisotropy.
    const albedo = vf.fogAlbedo ?? { r: 0.9, g: 0.92, b: 0.95 };
    r.paramsData[8] = albedo.r;
    r.paramsData[9] = albedo.g;
    r.paramsData[10] = albedo.b;
    r.paramsData[11] = vf.fogAnisotropy ?? 0.3;

    // Inverse view-projection matrix (offsets 12..27). The kernels
    // unproject screen UV + slice depth → world position via this.
    // Camera should provide it pre-computed; if not, compose it from
    // view × projection on the fly.
    const camera = frameState.camera;
    let invVP: ArrayLike<number> | undefined = camera?.inverseViewProjection;
    if (!invVP && camera) {
      // Compose view × projection then invert.
      Matrix4.multiply(
        camera.frustum.projectionMatrix,
        camera.viewMatrix,
        _scratchVP,
      );
      Matrix4.inverse(_scratchVP, _scratchInvVP);
      // Matrix4 is structurally indexable but its inferred type from the
      // JS constructor body doesn't list `length`; cast to satisfy the
      // ArrayLike-typed local var.
      invVP = _scratchInvVP as unknown as ArrayLike<number>;
    }
    if (invVP) {
      for (let i = 0; i < 16; i++) {
        r.paramsData[12 + i] = invVP[i];
      }
    } else {
      // Identity fallback — produces a valid no-op composite when the
      // camera isn't ready yet (first frame edge case).
      for (let i = 0; i < 16; i++) {
        r.paramsData[12 + i] = i % 5 === 0 ? 1.0 : 0.0;
      }
    }

    // Phase 5c — sun shadow matrix (offsets 28..43). Fetched from the
    // first active shadow map on frameState. The kernel uses this to
    // project each froxel's world position into shadow clip space and
    // sample the depth comparison; god ray formation depends on this.
    // When no shadow map is active, fill identity (the kernel skips
    // sampling via `occlusion.z = 0` instead of relying on the matrix).
    const shadowMaps = frameState.shadowMaps;
    let activeShadowMap: CesiumShadowMap | null = null;
    if (Array.isArray(shadowMaps) && shadowMaps.length > 0) {
      activeShadowMap = shadowMaps[0] as CesiumShadowMap;
    }
    let sunShadowMatrix: ArrayLike<number> | null = null;
    let realShadowView: GPUTextureView | null = null;
    if (activeShadowMap?._shadowMapMatrix) {
      sunShadowMatrix = activeShadowMap._shadowMapMatrix;
      const shadowCache = activeShadowMap._webgpuCache;
      if (shadowCache?.depthTextureView) {
        realShadowView = shadowCache.depthTextureView;
      }
    }
    if (sunShadowMatrix) {
      for (let i = 0; i < 16; i++) {
        r.paramsData[28 + i] = sunShadowMatrix[i];
      }
    } else {
      // Identity placeholder. Kernel skips the sample so the contents
      // here don't matter functionally, but we keep them clean.
      for (let i = 0; i < 16; i++) {
        r.paramsData[28 + i] = i % 5 === 0 ? 1.0 : 0.0;
      }
    }

    // Camera position WC + planet inner radius (offsets 44..47).
    const camPos = camera?.positionWC;
    r.paramsData[44] = camPos?.x ?? 0;
    r.paramsData[45] = camPos?.y ?? 0;
    r.paramsData[46] = camPos?.z ?? 0;
    // Planet inner radius — derive from the globe ellipsoid if attached.
    const globeEllipsoid = _scene?.globe?._ellipsoid as { radii: CesiumCartesian3 } | undefined;
    const innerRadius = globeEllipsoid
      ? Math.max(globeEllipsoid.radii.x, globeEllipsoid.radii.y, globeEllipsoid.radii.z)
      : 6378137;
    r.paramsData[47] = innerRadius;

    // Sun direction + intensity (offsets 48..51).
    const sunDir = frameState.sunDirectionWC;
    r.paramsData[48] = sunDir?.x ?? 0;
    r.paramsData[49] = sunDir?.y ?? 0;
    r.paramsData[50] = sunDir?.z ?? 1;
    // Sun intensity — currently a constant; Phase 1.4 humidity / airQuality
    // already modulate the LUT, so the sun-as-light intensity through
    // fog is the same as the LUT input. Hard-code 1.0 for the kernel
    // and let the albedo + density carry the rest.
    r.paramsData[51] = 1.0;

    // Moon direction + (phase × intensity) (offsets 52..55).
    const moonDir = frameState.moonDirectionWC;
    r.paramsData[52] = moonDir?.x ?? 0;
    r.paramsData[53] = moonDir?.y ?? 0;
    r.paramsData[54] = moonDir?.z ?? 1;
    const moonPhase = frameState.moonPhaseFraction ?? 1.0;
    const moonIntensity = ac?.lighting?.moonIntensity ?? 0.05;
    r.paramsData[55] = moonPhase * moonIntensity;

    // Phase 5c — occlusion controls (offsets 56..59).
    //   x = enableScatteringOcclusion (B20: default FALSE)
    //   y = ambientStrength (constant for now; Phase 5e can wire LUT)
    //   z = shadowMapValid (kernel skips sample when 0)
    //   w = shadowDarkness (matches the WebGPU shadow renderer's `darkness`)
    const occlusionEnabled = vf.enableScatteringOcclusion === true;
    r.paramsData[56] = occlusionEnabled ? 1.0 : 0.0;
    r.paramsData[57] = vf.ambientStrength ?? 0.05;
    r.paramsData[58] = realShadowView ? 1.0 : 0.0;
    r.paramsData[59] = activeShadowMap?.darkness ?? 0.3;

    // Phase 5d — varying atmosphere density (offsets 60..63).
    // Sourced from `atmosphericConditions.varyingAtmosphereDensity` —
    // a sibling leaf to volumetricFog. Per B21, this is silently a
    // no-op when volumetricFog is off (we only run the kernels at all
    // when vf.enabled is true), so reading it here is fine.
    const varyingRaw = ac?.varyingAtmosphereDensity;
    const varying = typeof varyingRaw === "object" ? varyingRaw : undefined;
    const varyingEnabled = varying?.enabled === true;
    r.paramsData[60] = varyingEnabled ? 1.0 : 0.0;
    r.paramsData[61] = varying?.noiseScale ?? 5000;
    r.paramsData[62] = varying?.noiseStrength ?? 0.3;
    r.paramsData[63] = 0.0;

    // Rebuild the scattering bind group when the shadow view changes.
    // The placeholder view is the initial state; once a real shadow map
    // arrives we swap to it. The bind group rebuild is rare (only when
    // the active shadow map's texture changes — typically once per
    // viewer session) so the cost is amortized to zero.
    const desiredShadowView = realShadowView ?? r.shadowPlaceholderView;
    if (r.scatteringBoundShadowView !== desiredShadowView) {
      r.scatteringBindGroup = device.createBindGroup({
        label: "VolumetricFog_ScatteringBindGroup",
        layout: r.scatteringBindGroupLayout,
        entries: [
          { binding: 0, resource: { buffer: r.paramsBuffer } },
          { binding: 2, resource: r.densityView },
          { binding: 3, resource: r.scatteringView },
          { binding: 6, resource: desiredShadowView },
          { binding: 7, resource: r.shadowComparisonSampler },
        ],
      });
      r.scatteringBoundShadowView = desiredShadowView;
    }

    device.queue.writeBuffer(
      r.paramsBuffer,
      0,
      r.paramsData.buffer,
      r.paramsData.byteOffset,
      r.paramsData.byteLength,
    );

    // ── Dispatch the three compute passes ──
    // Density and scattering: full 3D dispatch (W × H × D froxels).
    // Integrate: 2D dispatch (W × H), each thread serial-walks Z.
    const encoder = device.createCommandEncoder({
      label: "VolumetricFog_ComputeEncoder",
    });

    const wgX = Math.ceil(r.width / 8);
    const wgY = Math.ceil(r.height / 8);
    const wgZ = r.depth;

    {
      const pass = encoder.beginComputePass({
        label: "VolumetricFog_DensityPass",
      });
      pass.setPipeline(r.densityPipeline);
      pass.setBindGroup(0, r.densityBindGroup);
      pass.dispatchWorkgroups(wgX, wgY, wgZ);
      pass.end();
    }
    {
      const pass = encoder.beginComputePass({
        label: "VolumetricFog_ScatteringPass",
      });
      pass.setPipeline(r.scatteringPipeline);
      pass.setBindGroup(0, r.scatteringBindGroup);
      pass.dispatchWorkgroups(wgX, wgY, wgZ);
      pass.end();
    }
    {
      const pass = encoder.beginComputePass({
        label: "VolumetricFog_IntegratePass",
      });
      pass.setPipeline(r.integratePipeline);
      pass.setBindGroup(0, r.integrateBindGroup);
      // Phase 5b: each thread walks the depth axis serially, so Z=1.
      pass.dispatchWorkgroups(wgX, wgY, 1);
      pass.end();
    }

    device.queue.submit([encoder.finish()]);
  }

  /**
   * Run the composite pass: full-screen triangle that samples the
   * integrated 3D volume in screen UV + linearized depth and writes
   * `out = sceneColor * transmittance + scatteredLight` to `outputView`.
   *
   * Phase 5a: with cleared volume contents, this is visually a no-op.
   * Caller is still responsible for checking `enableVolumetricFog` —
   * we early-out here as defense in depth.
   */
  composite(
    context: CesiumGraphicsContext,
    frameState: CesiumFrameState,
    colorView: GPUTextureView,
    depthView: GPUTextureView,
    outputView: GPUTextureView,
    outputFormat: GPUTextureFormat,
  ): void {
    if (this._isDestroyed || !this._resources) return;
    const ac = frameState.atmosphericConditions;
    const vf = ac && ac.volumetricFog ? ac.volumetricFog : undefined;
    if (!vf || vf.enabled !== true) return;

    const device: GPUDevice = context.device;
    if (!device) return;

    this._composites++;
    const r = this._resources;

    // Pack the composite uniform buffer.
    const camera = frameState.camera;
    const inverseViewProjection = camera?.inverseViewProjection;
    if (inverseViewProjection) {
      for (let i = 0; i < 16; i++) {
        r.compositeUniformData[i] = inverseViewProjection[i];
      }
    } else {
      // Fallback to identity if the inverse VP isn't available — the
      // composite still produces the correct visual no-op because the
      // integrated volume is cleared, so depth-direction precision
      // doesn't matter.
      for (let i = 0; i < 16; i++) {
        r.compositeUniformData[i] = i % 5 === 0 ? 1.0 : 0.0;
      }
    }
    r.compositeUniformData[16] = camera?.frustum?.near ?? 1.0;
    r.compositeUniformData[17] = camera?.frustum?.far ?? 1.0e9;
    r.compositeUniformData[18] = vf.maxDistance ?? 50000;
    r.compositeUniformData[19] = 0;
    r.compositeUniformData[20] = context.drawingBufferWidth ?? 1;
    r.compositeUniformData[21] = context.drawingBufferHeight ?? 1;
    r.compositeUniformData[22] = 0;
    r.compositeUniformData[23] = 0;

    device.queue.writeBuffer(
      r.compositeUniformBuffer,
      0,
      r.compositeUniformData.buffer,
      r.compositeUniformData.byteOffset,
      r.compositeUniformData.byteLength,
    );

    // (Re)build the composite bind group when the input views change.
    // The output format check is informational only — the composite
    // pipeline was created with bgra8unorm; if the actual output format
    // differs the renderpass would fail. Phase 5b can rebuild the
    // pipeline on demand to match the actual format.
    if (
      r.compositeBindGroup === null ||
      r.compositeBoundColorView !== colorView ||
      r.compositeBoundDepthView !== depthView ||
      r.compositeBoundOutputFormat !== outputFormat
    ) {
      r.compositeBindGroup = device.createBindGroup({
        label: "VolumetricFog_CompositeBindGroup",
        layout: r.compositeBindGroupLayout,
        entries: [
          { binding: 0, resource: { buffer: r.compositeUniformBuffer } },
          { binding: 1, resource: r.compositeSampler },
          { binding: 2, resource: colorView },
          { binding: 3, resource: depthView },
          { binding: 4, resource: r.integratedSampleView },
        ],
      });
      r.compositeBoundColorView = colorView;
      r.compositeBoundDepthView = depthView;
      r.compositeBoundOutputFormat = outputFormat;
    }

    const encoder = device.createCommandEncoder({
      label: "VolumetricFog_CompositeEncoder",
    });
    const pass = encoder.beginRenderPass({
      label: "VolumetricFog_CompositePass",
      colorAttachments: [
        {
          view: outputView,
          loadOp: "load",
          storeOp: "store",
        },
      ],
    });
    pass.setPipeline(r.compositePipeline);
    pass.setBindGroup(0, r.compositeBindGroup);
    pass.draw(3);
    pass.end();
    device.queue.submit([encoder.finish()]);
  }

  destroy(): void {
    if (this._isDestroyed) return;
    // Phase 6 audit fix — unregister the snapshot freezable so the
    // service's Map doesn't hold a closure reference to a destroyed
    // renderer. Idempotent on the service side.
    if (this._snapshotRegistered && this._snapshotService) {
      try {
        this._snapshotService.unregisterFreezable("webgpu-volumetric-fog");
      } catch (e) {
        console.warn("[WebGPU:VolumetricFog] unregisterFreezable failed:", e);
      }
      this._snapshotRegistered = false;
      this._snapshotService = null;
    }
    this._destroyResources();
    this._isDestroyed = true;
  }
}

// ─── Feature renderer factory + entry points ───────────────────────

const _instances = new WeakMap<CesiumGraphicsContext, WebGPUVolumetricFogRenderer>();

function getOrCreate(context: CesiumGraphicsContext): WebGPUVolumetricFogRenderer {
  let inst = _instances.get(context);
  if (!inst) {
    inst = new WebGPUVolumetricFogRenderer(context.device);
    _instances.set(context, inst);
  }
  return inst;
}

/**
 * Feature renderer entry point: dispatch the three compute passes.
 * Called from `WebGPUSceneRenderer._executeEnvironmentalEffects()` once
 * per frame when `atmosphericConditions.volumetricFog.enabled` is true.
 */
export function updateWebGPUVolumetricFog(
  context: CesiumGraphicsContext,
  frameState: CesiumFrameState,
  scene: CesiumScene,
): void {
  if (!context || !context.device) return;
  const inst = getOrCreate(context);
  inst.update(context, frameState, scene);
}

/**
 * Feature renderer entry point: composite the integrated volume into
 * the scene color. Called from `WebGPUSceneRenderer._executeEnvironmentalEffects()`
 * after `updateWebGPUVolumetricFog()` and the other environmental
 * effects (procedural clouds, SSR, weather particles), before
 * post-processing.
 */
export function compositeWebGPUVolumetricFog(
  context: CesiumGraphicsContext,
  frameState: CesiumFrameState,
  colorView: GPUTextureView,
  depthView: GPUTextureView,
  outputView: GPUTextureView,
  outputFormat: GPUTextureFormat,
): void {
  if (!context || !context.device) return;
  const inst = _instances.get(context);
  if (!inst) return;
  inst.composite(
    context,
    frameState,
    colorView,
    depthView,
    outputView,
    outputFormat,
  );
}

/**
 * Feature renderer destroy entry point. Releases all GPU resources for
 * the given context's volumetric fog instance.
 */
export function destroyWebGPUVolumetricFog(context: CesiumGraphicsContext): void {
  const inst = _instances.get(context);
  if (inst) {
    inst.destroy();
    _instances.delete(context);
  }
}

/**
 * Phase 6 debug surface entry point — return the per-context volumetric
 * fog statistics, or `null` if the renderer has not been touched yet
 * for this context. Called by `WebGPUContext.getRendererStatistics()`.
 */
export function getWebGPUVolumetricFogStatistics(context: CesiumGraphicsContext): object | null {
  const inst = _instances.get(context);
  return inst ? inst.getStatistics() : null;
}

export { WebGPUVolumetricFogRenderer };
