// metrics-polyline.spec.mjs — the polyline family's metric extraction (probe-kit
// harvest, DX-108). Pure Node: no browser, no GPU, no network.
//
// @purpose Proves lib/metrics/colour-mask, line-structure, curve-bow and velocity-texels reproduce the polyline probes' pre-harvest pixel arithmetic exactly over seeded frames, and pins each function's behaviour on hand-derived cases.
// @status ACTIVE
//
// TWO KINDS OF CASE, FOR TWO DIFFERENT QUESTIONS.
//
//   E (equivalence) — "did the move change a number?" Each probe's pre-harvest
//   body, copied verbatim into `fixtures/polyline-metrics-references.mjs`, is
//   run beside the kit over the same frames and the two must agree exactly
//   (`deepStrictEqual`, no tolerance). The frames are seeded: boundary-value
//   noise drawn from every threshold the family uses and its two neighbours,
//   plus drawn scenes that make every structural branch fire. Each E case also
//   asserts a non-vacuity floor on a drawn scene, so "both returned zero" can
//   never be the agreement.
//
//   B (behaviour) — "is the function right on its own terms?" Hand-derived
//   literals with a one-line derivation each; nothing here is read back from
//   the module under test.
//
// The inertness mutants that prove these cases are live (one per extracted
// function, the working branch made unreachable with `false &&`) are run by
// the lane's harness and recorded in the landing packet.

import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
  referenceAppearance2d,
  referenceAppearancePrimitive,
  referenceCloudConsume,
  referenceCountLinePixels,
  referenceCoverage,
  referenceDiffRgba,
  referenceImageMaterial,
  referenceLogDepth,
  referenceMaterialPrimitive,
  referenceMeasureArc,
  referenceMultimaterial,
  referencePickSamples,
} from "./fixtures/polyline-metrics-references.mjs";
import { diffImages } from "./lib/image-diff.mjs";
import {
  anyChannelAbove,
  channelThresholds,
  maskCentroid,
  maskCount,
  maskSamples,
} from "./lib/metrics/colour-mask.mjs";
import {
  curveBowAgainstChord,
  topmostPerColumn,
} from "./lib/metrics/curve-bow.mjs";
import {
  arrowHeadProfile,
  columnHeights,
  outlineCrossSection,
  rowRunProfile,
} from "./lib/metrics/line-structure.mjs";
import {
  VELOCITY_NOISE_FLOOR,
  countNonZeroVelocityTexels,
  countNonZeroVelocityTexelsInRegion,
  decodeHalf,
} from "./lib/metrics/velocity-texels.mjs";
import { CYAN as CYAN_2D } from "./probe-polyline-appearance-2d.mjs";
import {
  CYAN as CYAN_LOGDEPTH,
  MAGENTA,
} from "./probe-polyline-appearance-logdepth.mjs";
import { CYAN as CYAN_PICK } from "./probe-polyline-appearance-pick.mjs";
import {
  CYAN as CYAN_PRIMITIVE,
  NON_BLACK,
} from "./probe-polyline-appearance-primitive.mjs";
import {
  CLOUDISH,
  CYAN as CYAN_CONSUME,
} from "./probe-polyline-cloud-consume.mjs";
import {
  COVERED,
  CYAN as CYAN_GEODESIC,
  RED as RED_CHORD,
  measureGeodesic,
} from "./probe-polyline-geodesic.mjs";
import { BLUE, RED } from "./probe-polyline-image-material.mjs";
import { COLORED } from "./probe-polyline-material-primitive.mjs";
import { measureMultimaterialFrame } from "./probe-polyline-multimaterial.mjs";
import { countLinePixels } from "./probe-polyline-taa-velocity.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Frames
// ---------------------------------------------------------------------------

/** An opaque black frame. */
function blank(width, height) {
  const data = new Uint8Array(width * height * 4);
  for (let i = 3; i < data.length; i += 4) {
    data[i] = 255;
  }
  return { width, height, data };
}

function put(image, x, y, [r, g, b]) {
  const i = (y * image.width + x) * 4;
  image.data[i] = r;
  image.data[i + 1] = g;
  image.data[i + 2] = b;
}

function fill(image, x0, y0, x1, y1, rgb) {
  for (let y = y0; y <= y1; y++) {
    for (let x = x0; x <= x1; x++) {
      put(image, x, y, rgb);
    }
  }
}

/** Every threshold the family uses, with its two neighbours. */
const BOUNDARY_VALUES = [
  0, 9, 10, 11, 19, 20, 21, 29, 30, 31, 39, 40, 41, 79, 80, 81, 89, 90, 91, 109,
  110, 111, 119, 120, 121, 139, 140, 141, 149, 150, 151, 179, 180, 181, 199,
  200, 201, 254, 255,
];

/** Deterministic LCG, so a failing frame can be regenerated by its seed. */
function rng(seed) {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 2 ** 32;
  };
}

function boundaryNoise(seed, width = 48, height = 40) {
  const next = rng(seed);
  const image = blank(width, height);
  const pick = () =>
    BOUNDARY_VALUES[Math.floor(next() * BOUNDARY_VALUES.length)];
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      put(image, x, y, [pick(), pick(), pick()]);
    }
  }
  return image;
}

/**
 * The five-material scene, drawn: a solid red band, a dashed cyan band, a
 * yellow glow with a linear profile, a magenta arrow (shaft + tapering head),
 * a lime core bracketed by blue outline rows, and a grey-white block.
 */
function linesFrame() {
  const image = blank(160, 64);
  fill(image, 10, 4, 150, 7, [255, 0, 0]);
  for (let x = 10; x <= 150; x++) {
    if ((x - 10) % 18 < 12) {
      fill(image, x, 12, x, 15, [0, 255, 255]);
    }
  }
  for (let y = 19; y <= 31; y++) {
    const v = Math.max(0, 255 - 40 * Math.abs(y - 25));
    fill(image, 10, y, 150, y, [v, v, 0]);
  }
  fill(image, 10, 36, 120, 41, [255, 0, 255]);
  for (let k = 0; k < 12; k++) {
    const half = 12 - k;
    fill(image, 121 + k, 39 - half, 121 + k, 38 + half, [255, 0, 255]);
  }
  fill(image, 10, 47, 150, 49, [0, 0, 255]);
  fill(image, 10, 50, 150, 53, [0, 255, 0]);
  fill(image, 10, 54, 150, 56, [0, 0, 255]);
  fill(image, 0, 58, 8, 62, [200, 200, 210]);
  return image;
}

/** A cyan arc bowing above a red chord, over boundary noise in one corner. */
function arcFrame(bow = 25) {
  const image = blank(120, 60);
  for (let x = 10; x <= 110; x++) {
    const t = (x - 60) / 50;
    const y = 40 - Math.round(bow * (1 - t * t));
    fill(image, x, y, x, y + 1, [0, 255, 255]);
    fill(image, x, 45, x, 46, [255, 0, 0]);
  }
  const noise = boundaryNoise(7, 8, 8);
  for (let y = 0; y < 8; y++) {
    for (let x = 0; x < 8; x++) {
      const i = (y * 8 + x) * 4;
      put(image, 112 + x, 52 + y, [...noise.data.slice(i, i + 3)]);
    }
  }
  return image;
}

/** A cyan block large enough to sample every 200th pixel more than once. */
function cyanBlock() {
  const image = blank(64, 48);
  fill(image, 4, 4, 59, 19, [0, 255, 255]);
  fill(image, 30, 25, 40, 30, [0, 230, 240]);
  return image;
}

/** The split texture on screen: red then blue along a horizontal band. */
function splitFrame() {
  const image = blank(100, 30);
  fill(image, 10, 10, 49, 19, [255, 0, 0]);
  fill(image, 50, 10, 89, 19, [0, 0, 255]);
  return image;
}

function fragmentFrame() {
  const image = blank(60, 30);
  fill(image, 20, 10, 29, 11, [0, 255, 255]);
  return image;
}

const FRAMES = Object.freeze({
  noise1: boundaryNoise(1),
  noise2: boundaryNoise(2),
  noise3: boundaryNoise(3, 64, 33),
  lines: linesFrame(),
  arc: arcFrame(),
  flatArc: arcFrame(0),
  cyanBlock: cyanBlock(),
  split: splitFrame(),
  fragment: fragmentFrame(),
  empty: blank(32, 24),
});

const each = (fn) => {
  for (const [name, image] of Object.entries(FRAMES)) {
    fn(name, image);
  }
};

// ---------------------------------------------------------------------------
// E. Equivalence with the pre-harvest bodies
// ---------------------------------------------------------------------------

test("E1 multimaterial: every hue's runs/FWHM, the arrow head and the outline cross-section match the in-page analysis", () => {
  each((name, image) => {
    const kit = measureMultimaterialFrame(image, {
      renderer: "stub",
      devicePixelRatio: 1,
    });
    const { renderer, width, height, devicePixelRatio, ...measured } = kit;
    assert.deepEqual(
      [renderer, width, height, devicePixelRatio],
      ["stub", image.width, image.height, 1],
    );
    assert.deepStrictEqual(
      measured,
      referenceMultimaterial(image.data, image.width, image.height),
      name,
    );
  });
  const lines = referenceMultimaterial(FRAMES.lines.data, 160, 64);
  assert.ok(lines.solid.colored > 0, "the solid band is seen");
  assert.ok(lines.dash.runsPerRow > 2, "the dash band is dashed");
  assert.ok(lines.glow.fwhm > 0, "the glow has a profile");
  assert.ok(lines.arrowProfile.headColumns > 0, "the arrow has a head");
  assert.ok(
    lines.outlineCrossSection.edgeAbove > 0 &&
      lines.outlineCrossSection.edgeBelow > 0,
    "the outline brackets its core",
  );
});

test("E2 material-primitive: colored, runs, coloredRows and runsPerRow match", () => {
  each((name, image) => {
    const { colored, runs, coloredRows, runsPerRow } = rowRunProfile(
      image,
      COLORED,
    );
    assert.deepStrictEqual(
      { colored, runs, coloredRows, runsPerRow },
      referenceMaterialPrimitive(image.data, image.width, image.height),
      name,
    );
  });
  assert.ok(rowRunProfile(FRAMES.lines, COLORED).runsPerRow > 1);
});

test("E3 appearance-primitive: the cyan and non-black counts match", () => {
  each((name, image) => {
    assert.deepStrictEqual(
      {
        cyan: maskCount(image, CYAN_PRIMITIVE),
        nonBlack: maskCount(image, NON_BLACK),
      },
      referenceAppearancePrimitive(image.data),
      name,
    );
  });
  assert.ok(maskCount(FRAMES.cyanBlock, CYAN_PRIMITIVE) > 200);
});

test("E4 appearance-2d: the cyan count and rounded centroid match", () => {
  each((name, image) => {
    const c = maskCentroid(image, CYAN_2D);
    assert.deepStrictEqual(
      {
        cyan: c.count,
        cx: c.count ? Math.round(c.meanX) : -1,
        cy: c.count ? Math.round(c.meanY) : -1,
      },
      referenceAppearance2d(image.data, image.width),
      name,
    );
  });
  assert.ok(maskCentroid(FRAMES.cyanBlock, CYAN_2D).count > 200);
});

test("E5 appearance-pick: every 200th on-line pixel is the same pixel", () => {
  each((name, image) => {
    const { count, samples } = maskSamples(image, CYAN_PICK, 200);
    assert.deepStrictEqual(
      { n: count, cyanPts: samples },
      referencePickSamples(image.data, image.width),
      name,
    );
  });
  assert.ok(maskSamples(FRAMES.cyanBlock, CYAN_PICK, 200).samples.length >= 2);
});

test("E6 appearance-logdepth: the cyan and magenta counts match", () => {
  each((name, image) => {
    assert.deepStrictEqual(
      {
        cyan: maskCount(image, CYAN_LOGDEPTH),
        magenta: maskCount(image, MAGENTA),
      },
      referenceLogDepth(image.data),
      name,
    );
  });
  const lines = referenceLogDepth(FRAMES.lines.data);
  assert.ok(lines.cyan > 0 && lines.magenta > 0);
});

test("E7 image-material: the red and blue counts and mean x match", () => {
  each((name, image) => {
    const red = maskCentroid(image, RED);
    const blue = maskCentroid(image, BLUE);
    assert.deepStrictEqual(
      {
        red: red.count,
        blue: blue.count,
        redMeanX: red.count ? Math.round(red.meanX) : -1,
        blueMeanX: blue.count ? Math.round(blue.meanX) : -1,
      },
      referenceImageMaterial(image.data, image.width),
      name,
    );
  });
  const split = referenceImageMaterial(FRAMES.split.data, 100);
  assert.ok(
    split.red > 100 && split.blue > 100 && split.redMeanX < split.blueMeanX,
  );
});

test("E8 cloud-consume: the cyan and cloud-white counts match the if/else-if original", () => {
  each((name, image) => {
    assert.deepStrictEqual(
      {
        cyan: maskCount(image, CYAN_CONSUME),
        cloudish: maskCount(image, CLOUDISH),
      },
      referenceCloudConsume(image.data),
      name,
    );
  });
  assert.ok(referenceCloudConsume(FRAMES.lines.data).cloudish > 0);
});

test("E9 geodesic: the arc, the coverage and the mismatch match measureArc, coverage and diffRGBA", () => {
  each((name, image) => {
    const kit = curveBowAgainstChord(image, CYAN_GEODESIC, RED_CHORD);
    const ref = referenceMeasureArc(image.data, image.width, image.height);
    const mapped = {
      ok: kit.ok,
      maxBow: kit.maxBow,
      maxCyanVsRed: kit.maxSeparation,
      cols: kit.curveColumns,
    };
    if (kit.ok) {
      mapped.bothCols = kit.sharedColumns;
    }
    assert.deepStrictEqual(mapped, ref, name);
    assert.equal(
      maskCount(image, COVERED),
      referenceCoverage(image.data),
      name,
    );
  });
  for (const [a, b] of [
    ["noise1", "noise2"],
    ["arc", "flatArc"],
    ["arc", "arc"],
  ]) {
    // The probe's own arithmetic, through the kit's diff, against diffRGBA.
    assert.equal(
      measureGeodesic(
        { image: FRAMES[a], subdividedCount: 0 },
        { image: FRAMES[b] },
      ).raw.diffPct,
      referenceDiffRgba(FRAMES[a].data, FRAMES[b].data),
      `${a} vs ${b}`,
    );
    // The kit's changed-pixel count is the original's mismatch count.
    assert.equal(
      diffImages(FRAMES[a], FRAMES[b], { tolerance: 24 }).changedPx,
      Math.round(
        (referenceDiffRgba(FRAMES[a].data, FRAMES[b].data) / 100) *
          FRAMES[a].width *
          FRAMES[a].height,
      ),
      `${a} vs ${b} count`,
    );
  }
  const arc = curveBowAgainstChord(FRAMES.arc, CYAN_GEODESIC, RED_CHORD);
  assert.ok(arc.ok && arc.maxBow > 8 && arc.maxSeparation > 8);
  assert.equal(
    curveBowAgainstChord(FRAMES.fragment, CYAN_GEODESIC, RED_CHORD).ok,
    false,
  );
});

test("E10 taa-velocity: countLinePixels on the kit matches the original loop", () => {
  each((name, image) => {
    assert.equal(countLinePixels(image), referenceCountLinePixels(image), name);
  });
  assert.ok(countLinePixels(FRAMES.cyanBlock) > 0);
});

// ---------------------------------------------------------------------------
// B. Behaviour, on hand-derived cases
// ---------------------------------------------------------------------------

test("B1 channelThresholds: every bound is strict", () => {
  const p = channelThresholds({ rBelow: 80, gAbove: 200, bAbove: 200 });
  assert.equal(p(79, 201, 201), true); // inside every bound
  assert.equal(p(80, 201, 201), false); // r == rBelow is excluded
  assert.equal(p(79, 200, 201), false); // g == gAbove is excluded
  assert.equal(p(79, 201, 200), false); // b == bAbove is excluded
  const open = channelThresholds({ rAbove: 150 });
  assert.equal(open(151, 0, 0), true); // undeclared channels are unbounded
  assert.equal(open(150, 255, 255), false);
});

test("B2 channelThresholds refuses what it cannot read", () => {
  assert.throws(() => channelThresholds({}), /at least one bound/);
  assert.throws(() => channelThresholds({ redAbove: 1 }), /unknown bound/);
  assert.throws(() => channelThresholds({ rAbove: Number.NaN }), /finite/);
  assert.throws(() => channelThresholds(null), /object/);
});

test("B3 anyChannelAbove: one channel strictly above the floor is enough", () => {
  const p = anyChannelAbove(30);
  assert.equal(p(30, 30, 30), false); // all at the floor
  assert.equal(p(31, 0, 0), true);
  assert.equal(p(0, 0, 31), true);
  assert.throws(() => anyChannelAbove(Number.NaN), /finite/);
});

test("B4 the frame and predicate guards refuse a ragged frame", () => {
  const ragged = { width: 2, height: 2, data: new Uint8Array(12) }; // 4 short
  assert.throws(
    () => maskCount(ragged, () => true),
    /exactly width\*height\*4/,
  );
  assert.throws(() => rowRunProfile(ragged, () => true), /exactly/);
  assert.throws(() => topmostPerColumn(ragged, () => true), /exactly/);
  assert.throws(() => maskCount(blank(2, 2), "cyan"), /predicate/);
});

test("B5 maskCount and maskCentroid: counts, sums and a null mean for no subject", () => {
  const image = blank(5, 4);
  put(image, 1, 0, [0, 255, 255]);
  put(image, 3, 2, [0, 255, 255]);
  const cyan = channelThresholds({ gAbove: 200, bAbove: 200 });
  assert.equal(maskCount(image, cyan), 2);
  // sumX = 1 + 3, sumY = 0 + 2, so the mean is (2, 1).
  assert.deepEqual(maskCentroid(image, cyan), {
    count: 2,
    sumX: 4,
    sumY: 2,
    meanX: 2,
    meanY: 1,
  });
  assert.deepEqual(maskCentroid(blank(3, 3), cyan), {
    count: 0,
    sumX: 0,
    sumY: 0,
    meanX: null,
    meanY: null,
  });
});

test("B6 maskSamples keeps the every-th match in raster order, never the first", () => {
  const image = blank(4, 2);
  for (const [x, y] of [
    [0, 0],
    [2, 0],
    [3, 0],
    [1, 1],
    [3, 1],
  ]) {
    put(image, x, y, [255, 255, 255]);
  }
  // Matches in raster order: (0,0) (2,0) (3,0) (1,1) (3,1); every 2nd keeps
  // the 2nd and the 4th.
  assert.deepEqual(maskSamples(image, anyChannelAbove(0), 2), {
    count: 5,
    samples: [
      [2, 0],
      [1, 1],
    ],
  });
  assert.throws(() => maskSamples(image, anyChannelAbove(0), 0), /every/);
});

test("B7 rowRunProfile: runs per row tell dash from solid, FWHM counts the rows at half the peak", () => {
  const image = blank(7, 3);
  // Row 0: XX.XX.X — three runs of a 200-bright class; row 1: XXXXXXX — one
  // run; row 2 empty.
  for (const x of [0, 1, 3, 4, 6]) put(image, x, 0, [200, 0, 0]);
  for (let x = 0; x < 7; x++) put(image, x, 1, [200, 0, 0]);
  const profile = rowRunProfile(image, anyChannelAbove(30));
  // colored 5 + 7, runs 3 + 1 over 2 colored rows; row sums 1000 and 1400,
  // half the peak is 700, so both rows count toward the FWHM.
  assert.deepEqual(profile, {
    colored: 12,
    runs: 4,
    coloredRows: 2,
    fwhm: 2,
    runsPerRow: 2,
  });
  assert.deepEqual(rowRunProfile(blank(3, 3), anyChannelAbove(30)), {
    colored: 0,
    runs: 0,
    coloredRows: 0,
    fwhm: 0,
    runsPerRow: 0,
  });
  // A row exactly AT half the peak counts. Rows of 4, 2 and 1 pixels at 200
  // sum to 800, 400 and 200; half the peak is exactly 400, so rows 0 and 1
  // count and row 2 does not. A strict `>` would count row 0 alone.
  const atHalf = blank(4, 3);
  fill(atHalf, 0, 0, 3, 0, [200, 0, 0]);
  fill(atHalf, 0, 1, 1, 1, [200, 0, 0]);
  put(atHalf, 0, 2, [200, 0, 0]);
  assert.equal(rowRunProfile(atHalf, anyChannelAbove(30)).fwhm, 2);
});

test("B8 columnHeights counts each column's matching pixels", () => {
  const image = blank(3, 4);
  fill(image, 0, 0, 0, 3, [255, 0, 0]); // column 0: 4
  fill(image, 2, 1, 2, 2, [255, 0, 0]); // column 2: 2
  assert.deepEqual([...columnHeights(image, anyChannelAbove(30))], [4, 0, 2]);
});

/** A shaft of height 4 over 40 columns, then a head of the given heights. */
function arrowFrame(head) {
  const image = blank(60, 30);
  fill(image, 2, 13, 41, 16, [255, 0, 255]);
  head.forEach((height, k) => {
    const top = 15 - Math.floor(height / 2);
    fill(image, 42 + k, top, 42 + k, top + height - 1, [255, 0, 255]);
  });
  return image;
}

test("B9 arrowHeadProfile separates a triangular head from a rectangular one of the same box", () => {
  const magenta = channelThresholds({ rAbove: 30, gBelow: 30, bAbove: 30 });
  // Triangle: heights 12, 10, 8, 6, 4, 2 after a body of 4 (flare 6): the head
  // starts at the 12 and runs to the tip, sum 42 over peak 12 x 6 columns.
  const triangle = arrowHeadProfile(arrowFrame([12, 10, 8, 6, 4, 2]), magenta);
  assert.equal(triangle.body, 4);
  assert.equal(triangle.headColumns, 6);
  assert.equal(triangle.headPeak, 12);
  assert.equal(triangle.headFill, 42 / 72);
  // Rectangle: six columns of 12 — same box, fill 1.
  const rectangle = arrowHeadProfile(
    arrowFrame([12, 12, 12, 12, 12, 12]),
    magenta,
  );
  assert.equal(rectangle.headFill, 1);
  // No column flares past 1.5x the shaft: no head at all.
  assert.deepEqual(arrowHeadProfile(arrowFrame([5, 5]), magenta), {
    body: 4,
    headColumns: 0,
    headPeak: 0,
    headFill: null,
    head: [],
  });
  assert.equal(arrowHeadProfile(blank(4, 4), magenta), null);
  // The shaft is the median over the leading 80 % of the span, and the
  // columns between 70 % and 80 % decide it here. Over 20 columns whose
  // heights are eight 2s, nine 4s, then 10, 7, 3, the leading 80 % (columns
  // 0-16) holds eight 2s and nine 4s, so the median shaft is 4, the flare
  // bar is 6 and the head is columns 17-19 (sum 20 over peak 10 x 3). A 70 %
  // split (columns 0-14) would hold eight 2s and seven 4s, put the shaft at 2
  // and run the head back to column 8.
  const split = blank(24, 20);
  [2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 10, 7, 3].forEach(
    (height, x) => {
      const top = 10 - Math.floor(height / 2);
      fill(split, x, top, x, top + height - 1, [255, 0, 255]);
    },
  );
  const shaft = arrowHeadProfile(split, magenta);
  assert.equal(shaft.body, 4);
  assert.equal(shaft.headStart, 17);
  assert.equal(shaft.headColumns, 3);
  assert.equal(shaft.headFill, 20 / 30);
});

test("B10 outlineCrossSection counts outline rows above and below the core at its widest column", () => {
  const lime = channelThresholds({ rBelow: 30, gAbove: 30, bBelow: 30 });
  const blue = channelThresholds({ rBelow: 30, gBelow: 30, bAbove: 30 });
  const image = blank(4, 8);
  fill(image, 1, 3, 1, 4, [0, 255, 0]); // core rows 3-4, column 1
  fill(image, 1, 1, 1, 2, [0, 0, 255]); // two outline rows above
  fill(image, 1, 5, 1, 5, [0, 0, 255]); // one below
  assert.deepEqual(outlineCrossSection(image, lime, blue), {
    column: 1,
    coreRows: 2,
    coreMin: 3,
    coreMax: 4,
    edgeAbove: 2,
    edgeBelow: 1,
  });
  // A flood of outline with no core has no column to read.
  const flood = blank(4, 8);
  fill(flood, 0, 0, 3, 7, [0, 0, 255]);
  assert.equal(outlineCrossSection(flood, lime, blue), null);
});

test("B11 curveBowAgainstChord: a straight curve does not bow, a V does, a fragment refuses", () => {
  const cyan = channelThresholds({ rBelow: 80, gAbove: 140, bAbove: 140 });
  const red = channelThresholds({ rAbove: 150, gBelow: 90, bBelow: 90 });
  const straight = blank(30, 20);
  fill(straight, 0, 5, 29, 5, [0, 255, 255]);
  fill(straight, 0, 8, 29, 8, [255, 0, 0]);
  // Topmost cyan is row 5 in every column, red row 8: no bow, separation 3.
  assert.deepEqual(curveBowAgainstChord(straight, cyan, red), {
    ok: true,
    maxBow: 0,
    maxSeparation: 3,
    curveColumns: 30,
    sharedColumns: 30,
  });
  // A V from (0,0) down to (10,10) and back up to (20,0): the line through the
  // ends is row 0, so the bow is the depth of the vertex, 10.
  const v = blank(21, 12);
  for (let x = 0; x <= 20; x++) put(v, x, 10 - Math.abs(x - 10), [0, 255, 255]);
  const bowed = curveBowAgainstChord(v, cyan, red);
  assert.equal(bowed.maxBow, 10);
  assert.equal(bowed.sharedColumns, 0);
  assert.equal(
    curveBowAgainstChord(v, cyan, red, { minColumns: 22 }).ok,
    false,
  );
  assert.throws(
    () => curveBowAgainstChord(v, cyan, red, { minColumns: 1 }),
    /minColumns/,
  );
});

test("B12 velocity-texels: binary16 decoding and the noise floor", () => {
  assert.equal(decodeHalf(0x3c00), 1); // exponent 15, mantissa 0
  assert.equal(decodeHalf(0xc000), -2); // sign, exponent 16
  assert.equal(decodeHalf(0x0400), 2 ** -14); // smallest normal
  assert.equal(decodeHalf(0x0001), 2 ** -24); // smallest denormal
  assert.equal(decodeHalf(0x7c00), Infinity);
  assert.ok(Number.isNaN(decodeHalf(0x7e00)));
  assert.equal(VELOCITY_NOISE_FLOOR, 1e-4);
  // Three texels: (1, 0) moves; (0, 0) is still; (2^-24, 0) is under the
  // floor, so one clears it and the largest magnitude is 1.
  const halves = [0x3c00, 0, 0, 0, 0x0001, 0];
  assert.deepEqual(countNonZeroVelocityTexels(halves), {
    nonZero: 1,
    total: 3,
    maxMagnitude: 1,
  });
  // The same texels as a 3x1 target; a rectangle over x 1..2 sees no motion.
  assert.deepEqual(
    countNonZeroVelocityTexelsInRegion(halves, 3, 1, {
      x0: 1,
      y0: 0,
      x1: 2,
      y1: 0,
    }),
    { nonZero: 0, total: 2, maxMagnitude: 2 ** -24 },
  );
  assert.equal(
    countNonZeroVelocityTexelsInRegion(halves, 3, 1, null).invalid,
    true,
  );
  // A rectangle over x 0..1 holds the moving texel and a still one.
  assert.deepEqual(
    countNonZeroVelocityTexelsInRegion(halves, 3, 1, {
      x0: 0,
      y0: 0,
      x1: 1,
      y1: 0,
    }),
    { nonZero: 1, total: 2, maxMagnitude: 1 },
  );
});

test("B13 the extracted metric modules import only lib/metrics siblings, and hold one copy of the frame checks", () => {
  const metricsDirectory = path.join(HERE, "lib", "metrics");
  const names = [
    "colour-mask.mjs",
    "line-structure.mjs",
    "curve-bow.mjs",
    "velocity-texels.mjs",
  ];
  const definitions = { requireImage: [], requirePredicate: [] };
  for (const name of names) {
    const source = readFileSync(path.join(metricsDirectory, name), "utf8");
    const specifiers = [
      ...source.matchAll(/^\s*import\s+(?:[\s\S]*?\sfrom\s+)?"([^"]+)"/gm),
    ].map((match) => match[1]);
    for (const specifier of specifiers) {
      assert.match(
        specifier,
        /^\.\/[\w-]+\.mjs$/,
        `${name} imports ${specifier}, which is not a lib/metrics sibling`,
      );
      assert.ok(
        existsSync(path.join(metricsDirectory, specifier)),
        `${name} imports ${specifier}, which does not exist`,
      );
    }
    for (const check of Object.keys(definitions)) {
      if (new RegExp(`function ${check}\\(`).test(source)) {
        definitions[check].push(name);
      }
    }
  }
  assert.deepEqual(definitions, {
    requireImage: ["colour-mask.mjs"],
    requirePredicate: ["colour-mask.mjs"],
  });
});
