// pipeline-cache-invalidation-subscriptions.spec.mjs
// @purpose Proves the two WebGPUContext pipeline-cache lazy getters hold one device-invalidation subscription each across repeated device-loss recoveries instead of stacking a new closure per rebuild.
// @status ACTIVE
//
// WHAT THIS SPEC IS FOR. Both pipeline caches are nulled on device loss and
// rebuilt on the next getter access, so the lazy branch inside each getter runs
// once per recovery. Each run used to call
// `this.onDeviceInvalidated(() => { ... = null; })` with a fresh arrow
// function, and `WebGPUDeviceInvalidationBus.subscribe` is a `Set.add` keyed on
// the callback reference. A new identity every rebuild meant a new Set entry
// every rebuild: one dead closure per recovery, each still invoked on every
// later loss, each holding the Context alive.
//
// The bus's own doc calls subscribe "idempotent over a given callback
// reference", which is exactly the property the getters were not supplying.
//
// HOW IT IS TESTED. The real `WebGPUDeviceInvalidationBus`, the real
// `WebGPUContext` getters, and the real pipeline-cache constructors — nothing
// about the subscription path is re-implemented here. The context instance is
// built with `Object.create(WebGPUContext.prototype)` and given only the fields
// the getters read, which is the pattern `texture-mip-queue-safety.spec.mjs`
// and `perf-manager-teardown.spec.mjs` already use for this class. In
// particular the two unsubscribe fields are NOT primed: they are left absent so
// the getter has to behave correctly on a context whose constructor never ran,
// and so this harness cannot supply the very state the fix depends on.
//
// The observable asserted is the bus's own subscriber count, which is what a
// leak consumes, rather than any private bookkeeping the fix introduced.
//
// Run: node --test Tools/visual-regression/pipeline-cache-invalidation-subscriptions.spec.mjs

import assert from "node:assert/strict";
import fs from "node:fs";
import { registerHooks } from "node:module";
import path from "node:path";
import test from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

import ts from "typescript";

import { enableEngineTsResolution } from "./lib/engine-ts-resolver.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const engineWebGPU = path.resolve(
  here,
  "../../packages/engine/Source/Renderer/WebGPU",
);

registerHooks({
  resolve(specifier, context, nextResolve) {
    // Engine shader barrels are generated by the build and are not on disk in
    // a source-only checkout. Nothing on the subscription path reads one.
    if (
      (specifier.startsWith("./") || specifier.startsWith("../")) &&
      specifier.endsWith(".js") &&
      typeof context.parentURL === "string" &&
      context.parentURL.startsWith("file:")
    ) {
      const asJs = new URL(specifier, context.parentURL);
      if (
        asJs.pathname.includes("/packages/engine/Source/Shaders/") &&
        !fs.existsSync(fileURLToPath(asJs))
      ) {
        return {
          url: "data:text/javascript,export default%20%22%22%3B",
          shortCircuit: true,
        };
      }
    }
    return nextResolve(specifier, context);
  },
  load(url, context, nextLoad) {
    if (url.endsWith(".ts")) {
      const source = fs.readFileSync(fileURLToPath(url), "utf8");
      return {
        format: "module",
        source: ts.transpileModule(source, {
          compilerOptions: {
            module: ts.ModuleKind.ESNext,
            target: ts.ScriptTarget.ES2022,
            verbatimModuleSyntax: false,
          },
        }).outputText,
        shortCircuit: true,
      };
    }
    return nextLoad(url, context);
  },
});

enableEngineTsResolution();

globalThis.GPUTextureUsage ??= Object.freeze({
  STORAGE_BINDING: 1,
  TEXTURE_BINDING: 2,
  COPY_SRC: 4,
  COPY_DST: 8,
  RENDER_ATTACHMENT: 16,
});
globalThis.GPUBufferUsage ??= Object.freeze({
  UNIFORM: 1,
  COPY_DST: 2,
  STORAGE: 4,
  VERTEX: 8,
  INDEX: 16,
  COPY_SRC: 32,
});
globalThis.GPUShaderStage ??= Object.freeze({
  VERTEX: 1,
  FRAGMENT: 2,
  COMPUTE: 4,
});

const { default: WebGPUContext } = await import(
  pathToFileURL(path.resolve(engineWebGPU, "WebGPUContext.ts")).href
);
const { WebGPUDeviceInvalidationBus, markDeviceLost } = await import(
  pathToFileURL(path.resolve(engineWebGPU, "WebGPUDeviceInvalidationBus.ts"))
    .href
);
const { WebGPURenderPipelineCache } = await import(
  pathToFileURL(path.resolve(engineWebGPU, "WebGPURenderPipelineCache.ts")).href
);
const { WebGPUComputePipelineCache } = await import(
  pathToFileURL(path.resolve(engineWebGPU, "WebGPUComputePipelineCache.ts"))
    .href
);

const renderCacheGetter = Object.getOwnPropertyDescriptor(
  WebGPUContext.prototype,
  "webgpuPipelineCache",
).get;
const computeCacheGetter = Object.getOwnPropertyDescriptor(
  WebGPUContext.prototype,
  "webgpuComputePipelineCache",
).get;

/**
 * A context whose prototype methods and accessors are the real ones and whose
 * instance state is the minimum the two getters read. TypeScript `private` is
 * erased, so the engine's own fields are ordinary properties.
 *
 * Deliberately absent: `_pipelineCacheInvalidationUnsubscribe` and
 * `_computePipelineCacheInvalidationUnsubscribe`. A harness that primed them
 * would be supplying the state under test.
 */
function makeContext(device) {
  const context = Object.create(WebGPUContext.prototype);
  context._id = "spec";
  context._device = device;
  // `_isDeviceUnavailable` is a derived getter over these three, so the
  // availability arm of each getter runs its real predicate rather than a
  // harness boolean.
  context._isDestroyed = false;
  context._terminallyLost = false;
  context._webgpuPipelineCache = null;
  context._webgpuComputePipelineCache = null;
  context._asyncResources = null;
  context._deviceInvalidationBus = new WebGPUDeviceInvalidationBus(
    () => context._id,
  );
  return context;
}

/** One device-loss recovery: fire the bus, then hand over a new device. */
function recover(context, device) {
  context._deviceInvalidationBus.fire();
  context._device = device;
}

test("the render pipeline cache holds one subscription across repeated recoveries", () => {
  const context = makeContext({ name: "device-0" });

  const first = renderCacheGetter.call(context);
  assert.ok(first instanceof WebGPURenderPipelineCache);
  assert.equal(first.device, context._device);

  // The asyncResources getter subscribes once for the monitor reset, and it is
  // reached from inside the pipeline-cache getter. Take the count AFTER the
  // first build so what is measured is growth, not the absolute total.
  const baseline = context._deviceInvalidationBus.size;
  assert.ok(baseline >= 1, "the cache must be dropped on invalidation at all");

  const devices = [{ name: "device-1" }, { name: "device-2" }];
  const caches = [first];
  for (const device of devices) {
    recover(context, device);
    // Firing must actually have dropped the cache; otherwise the rebuild below
    // never runs and this test would pass by doing nothing.
    assert.equal(
      context._webgpuPipelineCache,
      null,
      "the invalidation subscriber must null the cache",
    );
    const rebuilt = renderCacheGetter.call(context);
    assert.equal(rebuilt.device, device, "the rebuild must use the new device");
    caches.push(rebuilt);
    assert.equal(
      context._deviceInvalidationBus.size,
      baseline,
      `subscriber count grew after recovering onto ${device.name}`,
    );
  }

  // Every recovery produced a genuinely new cache, so the count above is
  // constant across real rebuilds rather than across a getter that short-
  // circuited.
  assert.equal(new Set(caches).size, 3);
});

test("the compute pipeline cache holds one subscription across repeated recoveries", () => {
  const context = makeContext({ name: "device-0" });

  const first = computeCacheGetter.call(context);
  assert.ok(first instanceof WebGPUComputePipelineCache);
  const baseline = context._deviceInvalidationBus.size;

  const caches = [first];
  for (const device of [{ name: "device-1" }, { name: "device-2" }]) {
    recover(context, device);
    assert.equal(context._webgpuComputePipelineCache, null);
    const rebuilt = computeCacheGetter.call(context);
    assert.equal(rebuilt.device, device);
    caches.push(rebuilt);
    assert.equal(
      context._deviceInvalidationBus.size,
      baseline,
      `subscriber count grew after recovering onto ${device.name}`,
    );
  }
  assert.equal(new Set(caches).size, 3);
});

test("both caches on one context stay at two subscriptions, not two per recovery", () => {
  // The realistic shape: a context that uses render and compute pipelines both.
  // A per-rebuild leak would add two entries per recovery here, so this is the
  // case where the old behaviour grew fastest.
  const context = makeContext({ name: "device-0" });
  renderCacheGetter.call(context);
  computeCacheGetter.call(context);
  const baseline = context._deviceInvalidationBus.size;

  for (let recovery = 1; recovery <= 4; recovery++) {
    recover(context, { name: `device-${recovery}` });
    renderCacheGetter.call(context);
    computeCacheGetter.call(context);
    assert.equal(
      context._deviceInvalidationBus.size,
      baseline,
      `subscriber count grew by recovery ${recovery}`,
    );
  }
});

test("the surviving subscriber is the live one, so recovery still works after four losses", () => {
  // A fix that merely stopped subscribing after the first build would keep the
  // count flat and quietly stop dropping the cache. Prove the retained
  // subscription is the one bound to the CURRENT cache by firing once more and
  // requiring the drop.
  const context = makeContext({ name: "device-0" });
  renderCacheGetter.call(context);
  computeCacheGetter.call(context);

  for (let recovery = 1; recovery <= 4; recovery++) {
    recover(context, { name: `device-${recovery}` });
    renderCacheGetter.call(context);
    computeCacheGetter.call(context);
  }

  const liveRender = context._webgpuPipelineCache;
  const liveCompute = context._webgpuComputePipelineCache;
  assert.ok(liveRender !== null && liveCompute !== null);

  context._deviceInvalidationBus.fire();
  assert.equal(
    context._webgpuPipelineCache,
    null,
    "the retained render subscriber must still drop the live cache",
  );
  assert.equal(
    context._webgpuComputePipelineCache,
    null,
    "the retained compute subscriber must still drop the live cache",
  );

  context._device = { name: "device-final" };
  assert.notEqual(renderCacheGetter.call(context), liveRender);
  assert.notEqual(computeCacheGetter.call(context), liveCompute);
});

test("an unavailable device is refused without touching the bus", () => {
  // The refusal arm is above the lazy branch, so it must not subscribe. The
  // device is made unavailable through the engine's own loss registry, which
  // is what `_isDeviceUnavailable` consults.
  const context = makeContext({ name: "device-0" });
  markDeviceLost(context._device);
  assert.equal(renderCacheGetter.call(context), null);
  assert.equal(computeCacheGetter.call(context), null);
  assert.equal(context._deviceInvalidationBus.size, 0);
});

// ───────────────────────────────────────────────────────────────────────────
// The same defect in the six sibling getters, and the hazard the shared fix
// introduces
// ───────────────────────────────────────────────────────────────────────────
//
// The two pipeline caches are not the only lazy getters on this class that
// null a device-bound field and re-subscribe on rebuild — `renderBundleManager`,
// `computeEngine`, `timestampProfiler`, `storageBufferPool`,
// `indirectDrawManager` and `bufferMapper` had the identical shape, and the
// identical leak. A fix that covered only the two rows that were reported would
// leave the class of defect live in the same file.
//
// Routing all eight through one shared helper closes the class, and introduces
// its own failure mode: the helper keys a retained handler by slot, so two
// getters given the SAME slot would share one handler and only one of the two
// fields would ever be dropped. A subscriber count alone cannot see that — it
// would be one lower and look better. So the test below asserts the count AND
// that every one of the eight fields is actually nulled by a fire.

/** A device stubbed just far enough for all eight constructors to run. */
function makeRicherContext(device) {
  const context = makeContext(device);
  context._featureFlags = new Set(["timestamp-query"]);
  return context;
}

const LAZY_DEVICE_SLOTS = [
  ["renderBundleManager", "_renderBundleManager"],
  ["computeEngine", "_computeEngine"],
  ["timestampProfiler", "_timestampProfiler"],
  ["storageBufferPool", "_storageBufferPool"],
  ["indirectDrawManager", "_indirectDrawManager"],
  ["bufferMapper", "_bufferMapper"],
  ["webgpuPipelineCache", "_webgpuPipelineCache"],
  ["webgpuComputePipelineCache", "_webgpuComputePipelineCache"],
];

function makeDevice(name) {
  return {
    name,
    createBuffer: () => ({ destroy() {} }),
    // Empty on purpose: the profiler getter is gated on the CONTEXT's feature
    // flags, which is what decides whether it subscribes, while the profiler
    // itself consults the DEVICE and disables cheaply. That is the shortest
    // path through the getter that still registers a subscription.
    features: new Set(),
  };
}

function readAll(context) {
  for (const [getterName] of LAZY_DEVICE_SLOTS) {
    const getter = Object.getOwnPropertyDescriptor(
      WebGPUContext.prototype,
      getterName,
    ).get;
    getter.call(context);
  }
}

test("every device-bound lazy getter holds one subscription, and its own", () => {
  const context = makeRicherContext(makeDevice("device-0"));
  readAll(context);

  // Each getter must actually have produced something, or the recoveries below
  // would be exercising nothing.
  for (const [getterName, field] of LAZY_DEVICE_SLOTS) {
    assert.ok(
      context[field] !== null && context[field] !== undefined,
      `${getterName} did not build`,
    );
  }
  const baseline = context._deviceInvalidationBus.size;

  for (let recovery = 1; recovery <= 4; recovery++) {
    context._deviceInvalidationBus.fire();
    // A slot shared between two getters shows up here and nowhere else: the
    // count would be low rather than high, and one field would survive.
    for (const [getterName, field] of LAZY_DEVICE_SLOTS) {
      assert.equal(
        context[field],
        null,
        `${getterName} was not dropped on recovery ${recovery}`,
      );
    }
    context._device = makeDevice(`device-${recovery}`);
    readAll(context);
    assert.equal(
      context._deviceInvalidationBus.size,
      baseline,
      `subscriber count grew by recovery ${recovery}`,
    );
  }
});
